#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-power-leaf

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - globalnetconnect.tcl
  - power-strategy-dualmesh.tcl

tests:
  - description: power analysis
    test_node: cadence-voltus-static-power-analysis
    default: True
    attach_points:
      - POWER
      - PLACE
      - CTS
      - ROUTE
      - SIGNOFF 
