#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-power-leaf

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - globalnetconnect.tcl
  - power-strategy-dualmesh.tcl

tests:
  - description: power-analysis
    test_graph: ir_test
    unit_test_graph: GcdUnit 
    attach_points:
      - PLACE
      - CTS
      - ROUTE
      - SIGNOFF 
