#=========================================================================
# Custom Scripts -- Tile Array CTS sink_type overrides
#=========================================================================

name: custom-cts-overrides

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
  - mkdir -p outputs
  - bash replace_array_width.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  array_width: undefined

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - cts-overrides.tcl
