name: sim

commands:
  - bash run_sim.sh

inputs:
  - design.v
  - header

outputs:
  - sim.log

postconditions:
  - assert File( 'outputs/sim.log' )      # must exist

  # Basic error checking
  - assert 'Error,' not in File( 'outputs/sim.log' )
