#=========================================================================
# Custom Scripts -- LVS SVRF Rules
#=========================================================================

name: custom-lvs-rules

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - rules.svrf
