name: cgra_sim_build

commands:
  - bash test_build.sh

outputs:
  - meta

parameters:
  array_width: 12
  array_height: 12
  pipeline_config_interval: 8
  interconnect_only: False
  soc_only: False
  PWR_AWARE: False
  use_container: True
  cgra_apps: ["tests/conv_1_2"]

postconditions:
  - assert File( 'outputs/meta' )        # must exist
