#=========================================================================
# Cadence Innovus Plugins
#=========================================================================

name: cadence-innovus-plugins

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - innovus-plugins

