#=========================================================================
# Cadence Innovus Plugins
#=========================================================================

name: cadence-innovus-plugins

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk

outputs:
  - innovus-plugins

