
name: cadence-innovus-genlib


#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - innovus-foundation-flow
  - design.checkpoint

outputs:
  - design.lib
  - design.db

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
- ln -sf inputs/innovus-foundation-flow
- innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log
- cd outputs
- ln -sf ../checkpoints/design.checkpoint
- ln -sf ../design.lib design.lib
# use Synopsys DC to convert lib to db
- cd ../
- mkdir -p lib2db && cd lib2db
- dc_shell-xg-t -64bit -output_log_file lib2db.log -f ../scripts/lib2db.tcl | tee lib2db_build.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: design
  order:
  - extract_model.tcl
  corner: typical

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64
    -init innovus-foundation-flow/custom-scripts/run-debug.tcl
    -log logs/debug.log

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'innovus' )                         # tool check
  - assert Tool( 'dc_shell-xg-t' )                   # tool check
  - assert File( 'inputs/innovus-foundation-flow' )  # must exist
  - assert File( 'inputs/adk' )                      # must exist
  - assert File( 'inputs/design.checkpoint' )        # must exist

postconditions:

  - assert File( 'outputs/design.lib' )      # must exist
  - assert File( 'outputs/design.db' )      # must exist

