#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - place-macros.tcl
  - dont-touch.tcl
  - innovus-pnr-config.tcl
  - create-rows.tcl
  - add-tracks.tcl
  - create-boundary-blockage.tcl
  - create-special-grid.tcl
  # - insert-input-antenna-diodes.tcl
