#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - stylus-compatibility-procs.tcl
  - floorplan.tcl
  - create-route-blockage-io-pads.tcl
  - io-fillers.tcl
  - create-rows.tcl
  - add-tracks.tcl
  - gen-bumps.tcl
  - route-bumps.tcl
  - innovus-pnr-config.tcl
  - place-macros.tcl
  - place-soc-mem.tcl
  - place-glb-top.tcl
  - place-io-tile.tcl
  - place-matrix-unit.tcl
  - place-tile-array.tcl
  - add-welltaps-for-pad-latchup.tcl
  - create-special-grid.tcl
  - carve-out-special-grid-fullchip.tcl
