dist: xenial
language: minimal
service: docker

install:
    - docker pull keyiz/garnet-flow
    - docker run -d -it --name garnet keyiz/garnet-flow bash
    - docker cp ../garnet garnet:/
    - docker exec -i garnet bash -c "pip install -r /garnet/requirements.txt" 
    - docker exec -i garnet bash -c "pip install pytest python-coveralls"
    - docker exec -i garnet bash -c "pip install pytest-cov pytest-codestyle z3-solver" 
    # check CoSA dependencies
    - docker exec -i garnet bash -c "pysmt-install --check"

    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    - docker cp Genesis2 garnet:/Genesis2
    # Set env variables for genesis (installed earlier)
    - docker exec -i garnet bash -c 'source /garnet/.travis/genesis_env.sh'

script:
    - docker exec -i garnet bash -c "source /garnet/.travis/genesis_env.sh && \
                                     cd /garnet/ && pytest --codestyle
                                     --cov global_controller
                                     --cov io_core
                                     --cov memory_core
                                     --ignore=filecmp.py
                                     --ignore=Genesis2/
                                     -v --cov-report term-missing tests"


after_success:
    - docker exec -i garnet bash -c "cd /garnet/ && coveralls"
