language: python
python:
    - "3.6"

install:
    # Convenience script for installing coreir on travis
    - wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
    - source install_coreir.sh
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8
    - pip install -e .

    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    # Set env variables for genesis (installed earlier)
    - export GENESIS_HOME=`pwd`/Genesis2/Genesis2Tools
    - export PATH=$GENESIS_HOME/bin:$GENESIS_HOME/gui/bin:$PATH
    - export PERL5LIB=$GENESIS_HOME/PerlLibs/ExtrasForOldPerlDistributions:$PERL5LIB

    # For some reason, we get
    # >   import filecmp
    # E   ModuleNotFoundError: No module named 'filecmp'
    # see https://travis-ci.com/rsetaluri/magma_connect_box/builds/78883000
    - wget https://raw.githubusercontent.com/python/cpython/master/Lib/filecmp.py
    - export PYTHONPATH=.:$PYTHONPATH

script:
    - pytest --cov connect_box -v -s --cov-report term-missing tests
    - pytest --pep8 connect_box

after_success:
    - coveralls
