language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - verilator
    - verilog
    - g++-4.9
python:
    - "3.6"

install:
    # Convenience script for installing coreir on travis
    - wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
    - source install_coreir.sh

    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest-cov pytest-codestyle
    # NOTE(rsetaluri): We no longer need to install this directory.
    #- pip install -e .

    # Begin setup CoSA dependencies
    - pysmt-install --z3 --confirm-agreement
    - export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.6:${PYTHONPATH}"
    - export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.6:${LD_LIBRARY_PATH}"
    - pysmt-install --check
    # End setup CoSA dependencies


    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    # Set env variables for genesis (installed earlier)
    - export GENESIS_HOME=`pwd`/Genesis2/Genesis2Tools
    - export PATH=$GENESIS_HOME/bin:$GENESIS_HOME/gui/bin:$PATH
    - export PERL5LIB=$GENESIS_HOME/PerlLibs/ExtrasForOldPerlDistributions:$PERL5LIB

script:
    - python -m pytest --codestyle
             --cov global_controller
             --cov io_core
             --cov memory_core
             --cov pe_core
             --cov simple_pe
             --ignore=filecmp.py
             --ignore=Genesis2/
             -v --cov-report term-missing .


after_success:
    - coveralls
