language: python
python:
    - "3.6"

install:
    - git clone https://github.com/phanrahan/magma
    - pip install -e magma
    - source magma/.travis/install_coreir.sh
    - git clone https://github.com/phanrahan/mantle
    - pip install -e mantle
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8

script:
    - py.test --cov connect_box --pep8 connect_box -v --cov-report term-missing tests
