dist: xenial
language: minimal
service: docker

install:
    - docker pull keyiz/garnet-flow
    - docker run -d -it --name garnet keyiz/garnet-flow bash
    - docker cp ../garnet garnet:/
    - docker exec -i garnet bash -c "pip install -r /garnet/requirements.txt"
    - docker exec -i garnet bash -c "pip install pytest python-coveralls"
    - docker exec -i garnet bash -c "pip install pytest-cov pytest-pycodestyle z3-solver"
      #- docker exec -i garnet bash -c "wget https://web.stanford.edu/~makaim/files/yosys-static -O ./bin/yosys"
      #- docker exec -i garnet bash -c "chmod +x ./bin/yosys"
      #- docker exec -i garnet bash -c "pysmt-install --confirm-agreement --msat"
    - docker exec -i garnet bash -c "pysmt-install --check"

    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    - docker cp Genesis2 garnet:/Genesis2

script:
    - docker exec -i garnet bash -c "/garnet/.travis/run.sh"

after_success:
    - docker exec -i garnet bash -c "cd /garnet/ && coveralls"
