language: python
python:
    - "3.6"

install:
    # Convenience script for installing coreir on travis
    - wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
    - source install_coreir.sh
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8
    - pip install -e .

script:
    - py.test --cov connect_box --pep8 connect_box -v --cov-report term-missing tests
