#=========================================================================
# Constraints
#=========================================================================
# Author : Alex Carsello
# Date   : Nov 1, 2019
#
# Edited by
# Gedeon Nyengele
# May 14, 2020
#-------------------------------------------------------------------------

name: constraints

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------
outputs:
  - constraints.tcl
  - cons_scripts

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
- cp -L cons_scripts/constraints.tcl outputs
- cp -RL cons_scripts outputs
