//   Ordt 190524.01 autogenerated file 
//   Input: /aha/garnet/global_buffer/systemRDL/glb.rdl
//   Parms: /aha/garnet/global_buffer/systemRDL/ordt_params/glb.parms
//   Date: Wed Oct 02 13:47:47 PDT 2024
//

//
//---------- module glb_jrdl_decode
//
module glb_jrdl_decode
(
  clk,
  reset,
  h2d_pio_dec_address,
  h2d_pio_dec_write_data,
  h2d_pio_dec_write,
  h2d_pio_dec_read,
  l2d_data_network_ctrl_r,
  l2d_data_network_latency_r,
  l2d_pcfg_network_ctrl_r,
  l2d_pcfg_network_latency_r,
  l2d_st_dma_ctrl_r,
  l2d_st_dma_num_blocks_r,
  l2d_st_dma_rv_seg_mode_r,
  l2d_st_dma_header_0_dim_r,
  l2d_st_dma_header_0_start_addr_r,
  l2d_st_dma_header_0_cycle_start_addr_r,
  l2d_st_dma_header_0_range_0_r,
  l2d_st_dma_header_0_stride_0_r,
  l2d_st_dma_header_0_cycle_stride_0_r,
  l2d_st_dma_header_0_range_1_r,
  l2d_st_dma_header_0_stride_1_r,
  l2d_st_dma_header_0_cycle_stride_1_r,
  l2d_st_dma_header_0_range_2_r,
  l2d_st_dma_header_0_stride_2_r,
  l2d_st_dma_header_0_cycle_stride_2_r,
  l2d_st_dma_header_0_range_3_r,
  l2d_st_dma_header_0_stride_3_r,
  l2d_st_dma_header_0_cycle_stride_3_r,
  l2d_st_dma_header_0_range_4_r,
  l2d_st_dma_header_0_stride_4_r,
  l2d_st_dma_header_0_cycle_stride_4_r,
  l2d_st_dma_header_0_range_5_r,
  l2d_st_dma_header_0_stride_5_r,
  l2d_st_dma_header_0_cycle_stride_5_r,
  l2d_st_dma_header_0_range_6_r,
  l2d_st_dma_header_0_stride_6_r,
  l2d_st_dma_header_0_cycle_stride_6_r,
  l2d_ld_dma_ctrl_r,
  l2d_ld_dma_header_0_dim_r,
  l2d_ld_dma_header_0_start_addr_r,
  l2d_ld_dma_header_0_cycle_start_addr_r,
  l2d_ld_dma_header_0_range_0_r,
  l2d_ld_dma_header_0_stride_0_r,
  l2d_ld_dma_header_0_cycle_stride_0_r,
  l2d_ld_dma_header_0_range_1_r,
  l2d_ld_dma_header_0_stride_1_r,
  l2d_ld_dma_header_0_cycle_stride_1_r,
  l2d_ld_dma_header_0_range_2_r,
  l2d_ld_dma_header_0_stride_2_r,
  l2d_ld_dma_header_0_cycle_stride_2_r,
  l2d_ld_dma_header_0_range_3_r,
  l2d_ld_dma_header_0_stride_3_r,
  l2d_ld_dma_header_0_cycle_stride_3_r,
  l2d_ld_dma_header_0_range_4_r,
  l2d_ld_dma_header_0_stride_4_r,
  l2d_ld_dma_header_0_cycle_stride_4_r,
  l2d_ld_dma_header_0_range_5_r,
  l2d_ld_dma_header_0_stride_5_r,
  l2d_ld_dma_header_0_cycle_stride_5_r,
  l2d_ld_dma_header_0_range_6_r,
  l2d_ld_dma_header_0_stride_6_r,
  l2d_ld_dma_header_0_cycle_stride_6_r,
  l2d_ld_dma_header_0_range_7_r,
  l2d_ld_dma_header_0_stride_7_r,
  l2d_ld_dma_header_0_cycle_stride_7_r,
  l2d_pcfg_dma_ctrl_r,
  l2d_pcfg_dma_header_start_addr_r,
  l2d_pcfg_dma_header_num_cfg_r,
  l2d_pcfg_broadcast_mux_r,

  d2h_dec_pio_read_data,
  d2h_dec_pio_ack,
  d2h_dec_pio_nack,
  d2l_data_network_ctrl_w,
  d2l_data_network_ctrl_we,
  d2l_data_network_ctrl_re,
  d2l_data_network_latency_w,
  d2l_data_network_latency_we,
  d2l_data_network_latency_re,
  d2l_pcfg_network_ctrl_w,
  d2l_pcfg_network_ctrl_we,
  d2l_pcfg_network_ctrl_re,
  d2l_pcfg_network_latency_w,
  d2l_pcfg_network_latency_we,
  d2l_pcfg_network_latency_re,
  d2l_st_dma_ctrl_w,
  d2l_st_dma_ctrl_we,
  d2l_st_dma_ctrl_re,
  d2l_st_dma_num_blocks_w,
  d2l_st_dma_num_blocks_we,
  d2l_st_dma_num_blocks_re,
  d2l_st_dma_rv_seg_mode_w,
  d2l_st_dma_rv_seg_mode_we,
  d2l_st_dma_rv_seg_mode_re,
  d2l_st_dma_header_0_dim_w,
  d2l_st_dma_header_0_dim_we,
  d2l_st_dma_header_0_dim_re,
  d2l_st_dma_header_0_start_addr_w,
  d2l_st_dma_header_0_start_addr_we,
  d2l_st_dma_header_0_start_addr_re,
  d2l_st_dma_header_0_cycle_start_addr_w,
  d2l_st_dma_header_0_cycle_start_addr_we,
  d2l_st_dma_header_0_cycle_start_addr_re,
  d2l_st_dma_header_0_range_0_w,
  d2l_st_dma_header_0_range_0_we,
  d2l_st_dma_header_0_range_0_re,
  d2l_st_dma_header_0_stride_0_w,
  d2l_st_dma_header_0_stride_0_we,
  d2l_st_dma_header_0_stride_0_re,
  d2l_st_dma_header_0_cycle_stride_0_w,
  d2l_st_dma_header_0_cycle_stride_0_we,
  d2l_st_dma_header_0_cycle_stride_0_re,
  d2l_st_dma_header_0_range_1_w,
  d2l_st_dma_header_0_range_1_we,
  d2l_st_dma_header_0_range_1_re,
  d2l_st_dma_header_0_stride_1_w,
  d2l_st_dma_header_0_stride_1_we,
  d2l_st_dma_header_0_stride_1_re,
  d2l_st_dma_header_0_cycle_stride_1_w,
  d2l_st_dma_header_0_cycle_stride_1_we,
  d2l_st_dma_header_0_cycle_stride_1_re,
  d2l_st_dma_header_0_range_2_w,
  d2l_st_dma_header_0_range_2_we,
  d2l_st_dma_header_0_range_2_re,
  d2l_st_dma_header_0_stride_2_w,
  d2l_st_dma_header_0_stride_2_we,
  d2l_st_dma_header_0_stride_2_re,
  d2l_st_dma_header_0_cycle_stride_2_w,
  d2l_st_dma_header_0_cycle_stride_2_we,
  d2l_st_dma_header_0_cycle_stride_2_re,
  d2l_st_dma_header_0_range_3_w,
  d2l_st_dma_header_0_range_3_we,
  d2l_st_dma_header_0_range_3_re,
  d2l_st_dma_header_0_stride_3_w,
  d2l_st_dma_header_0_stride_3_we,
  d2l_st_dma_header_0_stride_3_re,
  d2l_st_dma_header_0_cycle_stride_3_w,
  d2l_st_dma_header_0_cycle_stride_3_we,
  d2l_st_dma_header_0_cycle_stride_3_re,
  d2l_st_dma_header_0_range_4_w,
  d2l_st_dma_header_0_range_4_we,
  d2l_st_dma_header_0_range_4_re,
  d2l_st_dma_header_0_stride_4_w,
  d2l_st_dma_header_0_stride_4_we,
  d2l_st_dma_header_0_stride_4_re,
  d2l_st_dma_header_0_cycle_stride_4_w,
  d2l_st_dma_header_0_cycle_stride_4_we,
  d2l_st_dma_header_0_cycle_stride_4_re,
  d2l_st_dma_header_0_range_5_w,
  d2l_st_dma_header_0_range_5_we,
  d2l_st_dma_header_0_range_5_re,
  d2l_st_dma_header_0_stride_5_w,
  d2l_st_dma_header_0_stride_5_we,
  d2l_st_dma_header_0_stride_5_re,
  d2l_st_dma_header_0_cycle_stride_5_w,
  d2l_st_dma_header_0_cycle_stride_5_we,
  d2l_st_dma_header_0_cycle_stride_5_re,
  d2l_st_dma_header_0_range_6_w,
  d2l_st_dma_header_0_range_6_we,
  d2l_st_dma_header_0_range_6_re,
  d2l_st_dma_header_0_stride_6_w,
  d2l_st_dma_header_0_stride_6_we,
  d2l_st_dma_header_0_stride_6_re,
  d2l_st_dma_header_0_cycle_stride_6_w,
  d2l_st_dma_header_0_cycle_stride_6_we,
  d2l_st_dma_header_0_cycle_stride_6_re,
  d2l_ld_dma_ctrl_w,
  d2l_ld_dma_ctrl_we,
  d2l_ld_dma_ctrl_re,
  d2l_ld_dma_header_0_dim_w,
  d2l_ld_dma_header_0_dim_we,
  d2l_ld_dma_header_0_dim_re,
  d2l_ld_dma_header_0_start_addr_w,
  d2l_ld_dma_header_0_start_addr_we,
  d2l_ld_dma_header_0_start_addr_re,
  d2l_ld_dma_header_0_cycle_start_addr_w,
  d2l_ld_dma_header_0_cycle_start_addr_we,
  d2l_ld_dma_header_0_cycle_start_addr_re,
  d2l_ld_dma_header_0_range_0_w,
  d2l_ld_dma_header_0_range_0_we,
  d2l_ld_dma_header_0_range_0_re,
  d2l_ld_dma_header_0_stride_0_w,
  d2l_ld_dma_header_0_stride_0_we,
  d2l_ld_dma_header_0_stride_0_re,
  d2l_ld_dma_header_0_cycle_stride_0_w,
  d2l_ld_dma_header_0_cycle_stride_0_we,
  d2l_ld_dma_header_0_cycle_stride_0_re,
  d2l_ld_dma_header_0_range_1_w,
  d2l_ld_dma_header_0_range_1_we,
  d2l_ld_dma_header_0_range_1_re,
  d2l_ld_dma_header_0_stride_1_w,
  d2l_ld_dma_header_0_stride_1_we,
  d2l_ld_dma_header_0_stride_1_re,
  d2l_ld_dma_header_0_cycle_stride_1_w,
  d2l_ld_dma_header_0_cycle_stride_1_we,
  d2l_ld_dma_header_0_cycle_stride_1_re,
  d2l_ld_dma_header_0_range_2_w,
  d2l_ld_dma_header_0_range_2_we,
  d2l_ld_dma_header_0_range_2_re,
  d2l_ld_dma_header_0_stride_2_w,
  d2l_ld_dma_header_0_stride_2_we,
  d2l_ld_dma_header_0_stride_2_re,
  d2l_ld_dma_header_0_cycle_stride_2_w,
  d2l_ld_dma_header_0_cycle_stride_2_we,
  d2l_ld_dma_header_0_cycle_stride_2_re,
  d2l_ld_dma_header_0_range_3_w,
  d2l_ld_dma_header_0_range_3_we,
  d2l_ld_dma_header_0_range_3_re,
  d2l_ld_dma_header_0_stride_3_w,
  d2l_ld_dma_header_0_stride_3_we,
  d2l_ld_dma_header_0_stride_3_re,
  d2l_ld_dma_header_0_cycle_stride_3_w,
  d2l_ld_dma_header_0_cycle_stride_3_we,
  d2l_ld_dma_header_0_cycle_stride_3_re,
  d2l_ld_dma_header_0_range_4_w,
  d2l_ld_dma_header_0_range_4_we,
  d2l_ld_dma_header_0_range_4_re,
  d2l_ld_dma_header_0_stride_4_w,
  d2l_ld_dma_header_0_stride_4_we,
  d2l_ld_dma_header_0_stride_4_re,
  d2l_ld_dma_header_0_cycle_stride_4_w,
  d2l_ld_dma_header_0_cycle_stride_4_we,
  d2l_ld_dma_header_0_cycle_stride_4_re,
  d2l_ld_dma_header_0_range_5_w,
  d2l_ld_dma_header_0_range_5_we,
  d2l_ld_dma_header_0_range_5_re,
  d2l_ld_dma_header_0_stride_5_w,
  d2l_ld_dma_header_0_stride_5_we,
  d2l_ld_dma_header_0_stride_5_re,
  d2l_ld_dma_header_0_cycle_stride_5_w,
  d2l_ld_dma_header_0_cycle_stride_5_we,
  d2l_ld_dma_header_0_cycle_stride_5_re,
  d2l_ld_dma_header_0_range_6_w,
  d2l_ld_dma_header_0_range_6_we,
  d2l_ld_dma_header_0_range_6_re,
  d2l_ld_dma_header_0_stride_6_w,
  d2l_ld_dma_header_0_stride_6_we,
  d2l_ld_dma_header_0_stride_6_re,
  d2l_ld_dma_header_0_cycle_stride_6_w,
  d2l_ld_dma_header_0_cycle_stride_6_we,
  d2l_ld_dma_header_0_cycle_stride_6_re,
  d2l_ld_dma_header_0_range_7_w,
  d2l_ld_dma_header_0_range_7_we,
  d2l_ld_dma_header_0_range_7_re,
  d2l_ld_dma_header_0_stride_7_w,
  d2l_ld_dma_header_0_stride_7_we,
  d2l_ld_dma_header_0_stride_7_re,
  d2l_ld_dma_header_0_cycle_stride_7_w,
  d2l_ld_dma_header_0_cycle_stride_7_we,
  d2l_ld_dma_header_0_cycle_stride_7_re,
  d2l_pcfg_dma_ctrl_w,
  d2l_pcfg_dma_ctrl_we,
  d2l_pcfg_dma_ctrl_re,
  d2l_pcfg_dma_header_start_addr_w,
  d2l_pcfg_dma_header_start_addr_we,
  d2l_pcfg_dma_header_start_addr_re,
  d2l_pcfg_dma_header_num_cfg_w,
  d2l_pcfg_dma_header_num_cfg_we,
  d2l_pcfg_dma_header_num_cfg_re,
  d2l_pcfg_broadcast_mux_w,
  d2l_pcfg_broadcast_mux_we,
  d2l_pcfg_broadcast_mux_re );

  //------- inputs
  input    clk;
  input    reset;
  input     [7:2] h2d_pio_dec_address;
  input     [31:0] h2d_pio_dec_write_data;
  input    h2d_pio_dec_write;
  input    h2d_pio_dec_read;
  input     [31:0] l2d_data_network_ctrl_r;
  input     [31:0] l2d_data_network_latency_r;
  input     [31:0] l2d_pcfg_network_ctrl_r;
  input     [31:0] l2d_pcfg_network_latency_r;
  input     [31:0] l2d_st_dma_ctrl_r;
  input     [31:0] l2d_st_dma_num_blocks_r;
  input     [31:0] l2d_st_dma_rv_seg_mode_r;
  input     [31:0] l2d_st_dma_header_0_dim_r;
  input     [31:0] l2d_st_dma_header_0_start_addr_r;
  input     [31:0] l2d_st_dma_header_0_cycle_start_addr_r;
  input     [31:0] l2d_st_dma_header_0_range_0_r;
  input     [31:0] l2d_st_dma_header_0_stride_0_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_0_r;
  input     [31:0] l2d_st_dma_header_0_range_1_r;
  input     [31:0] l2d_st_dma_header_0_stride_1_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_1_r;
  input     [31:0] l2d_st_dma_header_0_range_2_r;
  input     [31:0] l2d_st_dma_header_0_stride_2_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_2_r;
  input     [31:0] l2d_st_dma_header_0_range_3_r;
  input     [31:0] l2d_st_dma_header_0_stride_3_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_3_r;
  input     [31:0] l2d_st_dma_header_0_range_4_r;
  input     [31:0] l2d_st_dma_header_0_stride_4_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_4_r;
  input     [31:0] l2d_st_dma_header_0_range_5_r;
  input     [31:0] l2d_st_dma_header_0_stride_5_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_5_r;
  input     [31:0] l2d_st_dma_header_0_range_6_r;
  input     [31:0] l2d_st_dma_header_0_stride_6_r;
  input     [31:0] l2d_st_dma_header_0_cycle_stride_6_r;
  input     [31:0] l2d_ld_dma_ctrl_r;
  input     [31:0] l2d_ld_dma_header_0_dim_r;
  input     [31:0] l2d_ld_dma_header_0_start_addr_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_start_addr_r;
  input     [31:0] l2d_ld_dma_header_0_range_0_r;
  input     [31:0] l2d_ld_dma_header_0_stride_0_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_0_r;
  input     [31:0] l2d_ld_dma_header_0_range_1_r;
  input     [31:0] l2d_ld_dma_header_0_stride_1_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_1_r;
  input     [31:0] l2d_ld_dma_header_0_range_2_r;
  input     [31:0] l2d_ld_dma_header_0_stride_2_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_2_r;
  input     [31:0] l2d_ld_dma_header_0_range_3_r;
  input     [31:0] l2d_ld_dma_header_0_stride_3_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_3_r;
  input     [31:0] l2d_ld_dma_header_0_range_4_r;
  input     [31:0] l2d_ld_dma_header_0_stride_4_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_4_r;
  input     [31:0] l2d_ld_dma_header_0_range_5_r;
  input     [31:0] l2d_ld_dma_header_0_stride_5_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_5_r;
  input     [31:0] l2d_ld_dma_header_0_range_6_r;
  input     [31:0] l2d_ld_dma_header_0_stride_6_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_6_r;
  input     [31:0] l2d_ld_dma_header_0_range_7_r;
  input     [31:0] l2d_ld_dma_header_0_stride_7_r;
  input     [31:0] l2d_ld_dma_header_0_cycle_stride_7_r;
  input     [31:0] l2d_pcfg_dma_ctrl_r;
  input     [31:0] l2d_pcfg_dma_header_start_addr_r;
  input     [31:0] l2d_pcfg_dma_header_num_cfg_r;
  input     [31:0] l2d_pcfg_broadcast_mux_r;

  //------- outputs
  output     [31:0] d2h_dec_pio_read_data;
  output    d2h_dec_pio_ack;
  output    d2h_dec_pio_nack;
  output     [31:0] d2l_data_network_ctrl_w;
  output    d2l_data_network_ctrl_we;
  output    d2l_data_network_ctrl_re;
  output     [31:0] d2l_data_network_latency_w;
  output    d2l_data_network_latency_we;
  output    d2l_data_network_latency_re;
  output     [31:0] d2l_pcfg_network_ctrl_w;
  output    d2l_pcfg_network_ctrl_we;
  output    d2l_pcfg_network_ctrl_re;
  output     [31:0] d2l_pcfg_network_latency_w;
  output    d2l_pcfg_network_latency_we;
  output    d2l_pcfg_network_latency_re;
  output     [31:0] d2l_st_dma_ctrl_w;
  output    d2l_st_dma_ctrl_we;
  output    d2l_st_dma_ctrl_re;
  output     [31:0] d2l_st_dma_num_blocks_w;
  output    d2l_st_dma_num_blocks_we;
  output    d2l_st_dma_num_blocks_re;
  output     [31:0] d2l_st_dma_rv_seg_mode_w;
  output    d2l_st_dma_rv_seg_mode_we;
  output    d2l_st_dma_rv_seg_mode_re;
  output     [31:0] d2l_st_dma_header_0_dim_w;
  output    d2l_st_dma_header_0_dim_we;
  output    d2l_st_dma_header_0_dim_re;
  output     [31:0] d2l_st_dma_header_0_start_addr_w;
  output    d2l_st_dma_header_0_start_addr_we;
  output    d2l_st_dma_header_0_start_addr_re;
  output     [31:0] d2l_st_dma_header_0_cycle_start_addr_w;
  output    d2l_st_dma_header_0_cycle_start_addr_we;
  output    d2l_st_dma_header_0_cycle_start_addr_re;
  output     [31:0] d2l_st_dma_header_0_range_0_w;
  output    d2l_st_dma_header_0_range_0_we;
  output    d2l_st_dma_header_0_range_0_re;
  output     [31:0] d2l_st_dma_header_0_stride_0_w;
  output    d2l_st_dma_header_0_stride_0_we;
  output    d2l_st_dma_header_0_stride_0_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_0_w;
  output    d2l_st_dma_header_0_cycle_stride_0_we;
  output    d2l_st_dma_header_0_cycle_stride_0_re;
  output     [31:0] d2l_st_dma_header_0_range_1_w;
  output    d2l_st_dma_header_0_range_1_we;
  output    d2l_st_dma_header_0_range_1_re;
  output     [31:0] d2l_st_dma_header_0_stride_1_w;
  output    d2l_st_dma_header_0_stride_1_we;
  output    d2l_st_dma_header_0_stride_1_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_1_w;
  output    d2l_st_dma_header_0_cycle_stride_1_we;
  output    d2l_st_dma_header_0_cycle_stride_1_re;
  output     [31:0] d2l_st_dma_header_0_range_2_w;
  output    d2l_st_dma_header_0_range_2_we;
  output    d2l_st_dma_header_0_range_2_re;
  output     [31:0] d2l_st_dma_header_0_stride_2_w;
  output    d2l_st_dma_header_0_stride_2_we;
  output    d2l_st_dma_header_0_stride_2_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_2_w;
  output    d2l_st_dma_header_0_cycle_stride_2_we;
  output    d2l_st_dma_header_0_cycle_stride_2_re;
  output     [31:0] d2l_st_dma_header_0_range_3_w;
  output    d2l_st_dma_header_0_range_3_we;
  output    d2l_st_dma_header_0_range_3_re;
  output     [31:0] d2l_st_dma_header_0_stride_3_w;
  output    d2l_st_dma_header_0_stride_3_we;
  output    d2l_st_dma_header_0_stride_3_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_3_w;
  output    d2l_st_dma_header_0_cycle_stride_3_we;
  output    d2l_st_dma_header_0_cycle_stride_3_re;
  output     [31:0] d2l_st_dma_header_0_range_4_w;
  output    d2l_st_dma_header_0_range_4_we;
  output    d2l_st_dma_header_0_range_4_re;
  output     [31:0] d2l_st_dma_header_0_stride_4_w;
  output    d2l_st_dma_header_0_stride_4_we;
  output    d2l_st_dma_header_0_stride_4_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_4_w;
  output    d2l_st_dma_header_0_cycle_stride_4_we;
  output    d2l_st_dma_header_0_cycle_stride_4_re;
  output     [31:0] d2l_st_dma_header_0_range_5_w;
  output    d2l_st_dma_header_0_range_5_we;
  output    d2l_st_dma_header_0_range_5_re;
  output     [31:0] d2l_st_dma_header_0_stride_5_w;
  output    d2l_st_dma_header_0_stride_5_we;
  output    d2l_st_dma_header_0_stride_5_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_5_w;
  output    d2l_st_dma_header_0_cycle_stride_5_we;
  output    d2l_st_dma_header_0_cycle_stride_5_re;
  output     [31:0] d2l_st_dma_header_0_range_6_w;
  output    d2l_st_dma_header_0_range_6_we;
  output    d2l_st_dma_header_0_range_6_re;
  output     [31:0] d2l_st_dma_header_0_stride_6_w;
  output    d2l_st_dma_header_0_stride_6_we;
  output    d2l_st_dma_header_0_stride_6_re;
  output     [31:0] d2l_st_dma_header_0_cycle_stride_6_w;
  output    d2l_st_dma_header_0_cycle_stride_6_we;
  output    d2l_st_dma_header_0_cycle_stride_6_re;
  output     [31:0] d2l_ld_dma_ctrl_w;
  output    d2l_ld_dma_ctrl_we;
  output    d2l_ld_dma_ctrl_re;
  output     [31:0] d2l_ld_dma_header_0_dim_w;
  output    d2l_ld_dma_header_0_dim_we;
  output    d2l_ld_dma_header_0_dim_re;
  output     [31:0] d2l_ld_dma_header_0_start_addr_w;
  output    d2l_ld_dma_header_0_start_addr_we;
  output    d2l_ld_dma_header_0_start_addr_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_start_addr_w;
  output    d2l_ld_dma_header_0_cycle_start_addr_we;
  output    d2l_ld_dma_header_0_cycle_start_addr_re;
  output     [31:0] d2l_ld_dma_header_0_range_0_w;
  output    d2l_ld_dma_header_0_range_0_we;
  output    d2l_ld_dma_header_0_range_0_re;
  output     [31:0] d2l_ld_dma_header_0_stride_0_w;
  output    d2l_ld_dma_header_0_stride_0_we;
  output    d2l_ld_dma_header_0_stride_0_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_0_w;
  output    d2l_ld_dma_header_0_cycle_stride_0_we;
  output    d2l_ld_dma_header_0_cycle_stride_0_re;
  output     [31:0] d2l_ld_dma_header_0_range_1_w;
  output    d2l_ld_dma_header_0_range_1_we;
  output    d2l_ld_dma_header_0_range_1_re;
  output     [31:0] d2l_ld_dma_header_0_stride_1_w;
  output    d2l_ld_dma_header_0_stride_1_we;
  output    d2l_ld_dma_header_0_stride_1_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_1_w;
  output    d2l_ld_dma_header_0_cycle_stride_1_we;
  output    d2l_ld_dma_header_0_cycle_stride_1_re;
  output     [31:0] d2l_ld_dma_header_0_range_2_w;
  output    d2l_ld_dma_header_0_range_2_we;
  output    d2l_ld_dma_header_0_range_2_re;
  output     [31:0] d2l_ld_dma_header_0_stride_2_w;
  output    d2l_ld_dma_header_0_stride_2_we;
  output    d2l_ld_dma_header_0_stride_2_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_2_w;
  output    d2l_ld_dma_header_0_cycle_stride_2_we;
  output    d2l_ld_dma_header_0_cycle_stride_2_re;
  output     [31:0] d2l_ld_dma_header_0_range_3_w;
  output    d2l_ld_dma_header_0_range_3_we;
  output    d2l_ld_dma_header_0_range_3_re;
  output     [31:0] d2l_ld_dma_header_0_stride_3_w;
  output    d2l_ld_dma_header_0_stride_3_we;
  output    d2l_ld_dma_header_0_stride_3_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_3_w;
  output    d2l_ld_dma_header_0_cycle_stride_3_we;
  output    d2l_ld_dma_header_0_cycle_stride_3_re;
  output     [31:0] d2l_ld_dma_header_0_range_4_w;
  output    d2l_ld_dma_header_0_range_4_we;
  output    d2l_ld_dma_header_0_range_4_re;
  output     [31:0] d2l_ld_dma_header_0_stride_4_w;
  output    d2l_ld_dma_header_0_stride_4_we;
  output    d2l_ld_dma_header_0_stride_4_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_4_w;
  output    d2l_ld_dma_header_0_cycle_stride_4_we;
  output    d2l_ld_dma_header_0_cycle_stride_4_re;
  output     [31:0] d2l_ld_dma_header_0_range_5_w;
  output    d2l_ld_dma_header_0_range_5_we;
  output    d2l_ld_dma_header_0_range_5_re;
  output     [31:0] d2l_ld_dma_header_0_stride_5_w;
  output    d2l_ld_dma_header_0_stride_5_we;
  output    d2l_ld_dma_header_0_stride_5_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_5_w;
  output    d2l_ld_dma_header_0_cycle_stride_5_we;
  output    d2l_ld_dma_header_0_cycle_stride_5_re;
  output     [31:0] d2l_ld_dma_header_0_range_6_w;
  output    d2l_ld_dma_header_0_range_6_we;
  output    d2l_ld_dma_header_0_range_6_re;
  output     [31:0] d2l_ld_dma_header_0_stride_6_w;
  output    d2l_ld_dma_header_0_stride_6_we;
  output    d2l_ld_dma_header_0_stride_6_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_6_w;
  output    d2l_ld_dma_header_0_cycle_stride_6_we;
  output    d2l_ld_dma_header_0_cycle_stride_6_re;
  output     [31:0] d2l_ld_dma_header_0_range_7_w;
  output    d2l_ld_dma_header_0_range_7_we;
  output    d2l_ld_dma_header_0_range_7_re;
  output     [31:0] d2l_ld_dma_header_0_stride_7_w;
  output    d2l_ld_dma_header_0_stride_7_we;
  output    d2l_ld_dma_header_0_stride_7_re;
  output     [31:0] d2l_ld_dma_header_0_cycle_stride_7_w;
  output    d2l_ld_dma_header_0_cycle_stride_7_we;
  output    d2l_ld_dma_header_0_cycle_stride_7_re;
  output     [31:0] d2l_pcfg_dma_ctrl_w;
  output    d2l_pcfg_dma_ctrl_we;
  output    d2l_pcfg_dma_ctrl_re;
  output     [31:0] d2l_pcfg_dma_header_start_addr_w;
  output    d2l_pcfg_dma_header_start_addr_we;
  output    d2l_pcfg_dma_header_start_addr_re;
  output     [31:0] d2l_pcfg_dma_header_num_cfg_w;
  output    d2l_pcfg_dma_header_num_cfg_we;
  output    d2l_pcfg_dma_header_num_cfg_re;
  output     [31:0] d2l_pcfg_broadcast_mux_w;
  output    d2l_pcfg_broadcast_mux_we;
  output    d2l_pcfg_broadcast_mux_re;


  //------- wire defines
  logic   [7:2] pio_dec_address;
  logic   [31:0] pio_dec_write_data;
  logic  pio_dec_read;
  logic  pio_dec_write;
  
  //------- reg defines
  logic   [31:0] d2l_data_network_ctrl_w;
  logic  d2l_data_network_ctrl_we;
  logic  d2l_data_network_ctrl_re;
  logic   [31:0] d2l_data_network_latency_w;
  logic  d2l_data_network_latency_we;
  logic  d2l_data_network_latency_re;
  logic   [31:0] d2l_pcfg_network_ctrl_w;
  logic  d2l_pcfg_network_ctrl_we;
  logic  d2l_pcfg_network_ctrl_re;
  logic   [31:0] d2l_pcfg_network_latency_w;
  logic  d2l_pcfg_network_latency_we;
  logic  d2l_pcfg_network_latency_re;
  logic   [31:0] d2l_st_dma_ctrl_w;
  logic  d2l_st_dma_ctrl_we;
  logic  d2l_st_dma_ctrl_re;
  logic   [31:0] d2l_st_dma_num_blocks_w;
  logic  d2l_st_dma_num_blocks_we;
  logic  d2l_st_dma_num_blocks_re;
  logic   [31:0] d2l_st_dma_rv_seg_mode_w;
  logic  d2l_st_dma_rv_seg_mode_we;
  logic  d2l_st_dma_rv_seg_mode_re;
  logic   [31:0] d2l_st_dma_header_0_dim_w;
  logic  d2l_st_dma_header_0_dim_we;
  logic  d2l_st_dma_header_0_dim_re;
  logic   [31:0] d2l_st_dma_header_0_start_addr_w;
  logic  d2l_st_dma_header_0_start_addr_we;
  logic  d2l_st_dma_header_0_start_addr_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_start_addr_w;
  logic  d2l_st_dma_header_0_cycle_start_addr_we;
  logic  d2l_st_dma_header_0_cycle_start_addr_re;
  logic   [31:0] d2l_st_dma_header_0_range_0_w;
  logic  d2l_st_dma_header_0_range_0_we;
  logic  d2l_st_dma_header_0_range_0_re;
  logic   [31:0] d2l_st_dma_header_0_stride_0_w;
  logic  d2l_st_dma_header_0_stride_0_we;
  logic  d2l_st_dma_header_0_stride_0_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_0_w;
  logic  d2l_st_dma_header_0_cycle_stride_0_we;
  logic  d2l_st_dma_header_0_cycle_stride_0_re;
  logic   [31:0] d2l_st_dma_header_0_range_1_w;
  logic  d2l_st_dma_header_0_range_1_we;
  logic  d2l_st_dma_header_0_range_1_re;
  logic   [31:0] d2l_st_dma_header_0_stride_1_w;
  logic  d2l_st_dma_header_0_stride_1_we;
  logic  d2l_st_dma_header_0_stride_1_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_1_w;
  logic  d2l_st_dma_header_0_cycle_stride_1_we;
  logic  d2l_st_dma_header_0_cycle_stride_1_re;
  logic   [31:0] d2l_st_dma_header_0_range_2_w;
  logic  d2l_st_dma_header_0_range_2_we;
  logic  d2l_st_dma_header_0_range_2_re;
  logic   [31:0] d2l_st_dma_header_0_stride_2_w;
  logic  d2l_st_dma_header_0_stride_2_we;
  logic  d2l_st_dma_header_0_stride_2_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_2_w;
  logic  d2l_st_dma_header_0_cycle_stride_2_we;
  logic  d2l_st_dma_header_0_cycle_stride_2_re;
  logic   [31:0] d2l_st_dma_header_0_range_3_w;
  logic  d2l_st_dma_header_0_range_3_we;
  logic  d2l_st_dma_header_0_range_3_re;
  logic   [31:0] d2l_st_dma_header_0_stride_3_w;
  logic  d2l_st_dma_header_0_stride_3_we;
  logic  d2l_st_dma_header_0_stride_3_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_3_w;
  logic  d2l_st_dma_header_0_cycle_stride_3_we;
  logic  d2l_st_dma_header_0_cycle_stride_3_re;
  logic   [31:0] d2l_st_dma_header_0_range_4_w;
  logic  d2l_st_dma_header_0_range_4_we;
  logic  d2l_st_dma_header_0_range_4_re;
  logic   [31:0] d2l_st_dma_header_0_stride_4_w;
  logic  d2l_st_dma_header_0_stride_4_we;
  logic  d2l_st_dma_header_0_stride_4_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_4_w;
  logic  d2l_st_dma_header_0_cycle_stride_4_we;
  logic  d2l_st_dma_header_0_cycle_stride_4_re;
  logic   [31:0] d2l_st_dma_header_0_range_5_w;
  logic  d2l_st_dma_header_0_range_5_we;
  logic  d2l_st_dma_header_0_range_5_re;
  logic   [31:0] d2l_st_dma_header_0_stride_5_w;
  logic  d2l_st_dma_header_0_stride_5_we;
  logic  d2l_st_dma_header_0_stride_5_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_5_w;
  logic  d2l_st_dma_header_0_cycle_stride_5_we;
  logic  d2l_st_dma_header_0_cycle_stride_5_re;
  logic   [31:0] d2l_st_dma_header_0_range_6_w;
  logic  d2l_st_dma_header_0_range_6_we;
  logic  d2l_st_dma_header_0_range_6_re;
  logic   [31:0] d2l_st_dma_header_0_stride_6_w;
  logic  d2l_st_dma_header_0_stride_6_we;
  logic  d2l_st_dma_header_0_stride_6_re;
  logic   [31:0] d2l_st_dma_header_0_cycle_stride_6_w;
  logic  d2l_st_dma_header_0_cycle_stride_6_we;
  logic  d2l_st_dma_header_0_cycle_stride_6_re;
  logic   [31:0] d2l_ld_dma_ctrl_w;
  logic  d2l_ld_dma_ctrl_we;
  logic  d2l_ld_dma_ctrl_re;
  logic   [31:0] d2l_ld_dma_header_0_dim_w;
  logic  d2l_ld_dma_header_0_dim_we;
  logic  d2l_ld_dma_header_0_dim_re;
  logic   [31:0] d2l_ld_dma_header_0_start_addr_w;
  logic  d2l_ld_dma_header_0_start_addr_we;
  logic  d2l_ld_dma_header_0_start_addr_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_start_addr_w;
  logic  d2l_ld_dma_header_0_cycle_start_addr_we;
  logic  d2l_ld_dma_header_0_cycle_start_addr_re;
  logic   [31:0] d2l_ld_dma_header_0_range_0_w;
  logic  d2l_ld_dma_header_0_range_0_we;
  logic  d2l_ld_dma_header_0_range_0_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_0_w;
  logic  d2l_ld_dma_header_0_stride_0_we;
  logic  d2l_ld_dma_header_0_stride_0_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_0_w;
  logic  d2l_ld_dma_header_0_cycle_stride_0_we;
  logic  d2l_ld_dma_header_0_cycle_stride_0_re;
  logic   [31:0] d2l_ld_dma_header_0_range_1_w;
  logic  d2l_ld_dma_header_0_range_1_we;
  logic  d2l_ld_dma_header_0_range_1_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_1_w;
  logic  d2l_ld_dma_header_0_stride_1_we;
  logic  d2l_ld_dma_header_0_stride_1_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_1_w;
  logic  d2l_ld_dma_header_0_cycle_stride_1_we;
  logic  d2l_ld_dma_header_0_cycle_stride_1_re;
  logic   [31:0] d2l_ld_dma_header_0_range_2_w;
  logic  d2l_ld_dma_header_0_range_2_we;
  logic  d2l_ld_dma_header_0_range_2_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_2_w;
  logic  d2l_ld_dma_header_0_stride_2_we;
  logic  d2l_ld_dma_header_0_stride_2_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_2_w;
  logic  d2l_ld_dma_header_0_cycle_stride_2_we;
  logic  d2l_ld_dma_header_0_cycle_stride_2_re;
  logic   [31:0] d2l_ld_dma_header_0_range_3_w;
  logic  d2l_ld_dma_header_0_range_3_we;
  logic  d2l_ld_dma_header_0_range_3_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_3_w;
  logic  d2l_ld_dma_header_0_stride_3_we;
  logic  d2l_ld_dma_header_0_stride_3_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_3_w;
  logic  d2l_ld_dma_header_0_cycle_stride_3_we;
  logic  d2l_ld_dma_header_0_cycle_stride_3_re;
  logic   [31:0] d2l_ld_dma_header_0_range_4_w;
  logic  d2l_ld_dma_header_0_range_4_we;
  logic  d2l_ld_dma_header_0_range_4_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_4_w;
  logic  d2l_ld_dma_header_0_stride_4_we;
  logic  d2l_ld_dma_header_0_stride_4_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_4_w;
  logic  d2l_ld_dma_header_0_cycle_stride_4_we;
  logic  d2l_ld_dma_header_0_cycle_stride_4_re;
  logic   [31:0] d2l_ld_dma_header_0_range_5_w;
  logic  d2l_ld_dma_header_0_range_5_we;
  logic  d2l_ld_dma_header_0_range_5_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_5_w;
  logic  d2l_ld_dma_header_0_stride_5_we;
  logic  d2l_ld_dma_header_0_stride_5_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_5_w;
  logic  d2l_ld_dma_header_0_cycle_stride_5_we;
  logic  d2l_ld_dma_header_0_cycle_stride_5_re;
  logic   [31:0] d2l_ld_dma_header_0_range_6_w;
  logic  d2l_ld_dma_header_0_range_6_we;
  logic  d2l_ld_dma_header_0_range_6_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_6_w;
  logic  d2l_ld_dma_header_0_stride_6_we;
  logic  d2l_ld_dma_header_0_stride_6_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_6_w;
  logic  d2l_ld_dma_header_0_cycle_stride_6_we;
  logic  d2l_ld_dma_header_0_cycle_stride_6_re;
  logic   [31:0] d2l_ld_dma_header_0_range_7_w;
  logic  d2l_ld_dma_header_0_range_7_we;
  logic  d2l_ld_dma_header_0_range_7_re;
  logic   [31:0] d2l_ld_dma_header_0_stride_7_w;
  logic  d2l_ld_dma_header_0_stride_7_we;
  logic  d2l_ld_dma_header_0_stride_7_re;
  logic   [31:0] d2l_ld_dma_header_0_cycle_stride_7_w;
  logic  d2l_ld_dma_header_0_cycle_stride_7_we;
  logic  d2l_ld_dma_header_0_cycle_stride_7_re;
  logic   [31:0] d2l_pcfg_dma_ctrl_w;
  logic  d2l_pcfg_dma_ctrl_we;
  logic  d2l_pcfg_dma_ctrl_re;
  logic   [31:0] d2l_pcfg_dma_header_start_addr_w;
  logic  d2l_pcfg_dma_header_start_addr_we;
  logic  d2l_pcfg_dma_header_start_addr_re;
  logic   [31:0] d2l_pcfg_dma_header_num_cfg_w;
  logic  d2l_pcfg_dma_header_num_cfg_we;
  logic  d2l_pcfg_dma_header_num_cfg_re;
  logic   [31:0] d2l_pcfg_broadcast_mux_w;
  logic  d2l_pcfg_broadcast_mux_we;
  logic  d2l_pcfg_broadcast_mux_re;
  logic  pio_write_active;
  logic  pio_read_active;
  logic   [7:2] pio_dec_address_d1;
  logic   [31:0] pio_dec_write_data_d1;
  logic   [31:0] dec_pio_read_data;
  logic   [31:0] dec_pio_read_data_d1;
  logic  dec_pio_ack;
  logic  dec_pio_nack;
  logic  dec_pio_ack_next;
  logic  dec_pio_nack_next;
  logic  pio_internal_ack;
  logic  pio_internal_nack;
  logic  pio_external_ack;
  logic  pio_external_nack;
  logic  pio_external_ack_next;
  logic  pio_external_nack_next;
  logic  pio_no_acks;
  logic  pio_activate_write;
  logic  pio_activate_read;
  logic   [31:0] dec_pio_read_data_next;
  logic  external_transaction_active;
  
  
  //------- assigns
  assign  pio_dec_address = h2d_pio_dec_address;
  assign  pio_dec_write_data = h2d_pio_dec_write_data;
  assign  pio_dec_read = h2d_pio_dec_read;
  assign  pio_dec_write = h2d_pio_dec_write;
  assign  d2h_dec_pio_read_data = dec_pio_read_data;
  assign  d2h_dec_pio_ack = dec_pio_ack;
  assign  d2h_dec_pio_nack = dec_pio_nack;
  
  //------- combinatorial assigns for pio read data
  always_comb begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end
  
  //------- reg assigns for pio read data
  always_ff @ (posedge clk or posedge reset) begin
    if (reset) begin
      dec_pio_read_data_d1 <=  32'b0;
    end
    else begin
      dec_pio_read_data_d1 <= dec_pio_read_data_next;
    end
  end
  
  //------- reg assigns for pio i/f
  always_ff @ (posedge clk or posedge reset) begin
    if (reset) begin
      pio_write_active <=  1'b0;
      pio_read_active <=  1'b0;
      pio_dec_address_d1 <= 0;
      pio_dec_write_data_d1 <= 0;
    end
    else begin
      pio_write_active <=  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <=  pio_read_active ? pio_no_acks : pio_activate_read;
      pio_dec_address_d1 <=   pio_dec_address;
      pio_dec_write_data_d1 <=  pio_dec_write_data;
    end
  end
  
  //------- combinatorial assigns for pio ack/nack
  always_comb begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end
  
  //------- reg assigns for pio ack/nack
  always_ff @ (posedge clk or posedge reset) begin
    if (reset) begin
      dec_pio_ack <= 1'b0;
      dec_pio_nack <= 1'b0;
      pio_external_ack <=  1'b0;
      pio_external_nack <=  1'b0;
    end
    else begin
      dec_pio_ack <= dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= pio_external_ack_next;
      pio_external_nack <= pio_external_nack_next;
    end
  end
  
  
  //------- address decode
  always_comb begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 32'b0;
    
    d2l_data_network_ctrl_w = pio_dec_write_data_d1  [31:0] ;
    d2l_data_network_ctrl_we = 1'b0;
    d2l_data_network_ctrl_re = 1'b0;
    d2l_data_network_latency_w = pio_dec_write_data_d1  [31:0] ;
    d2l_data_network_latency_we = 1'b0;
    d2l_data_network_latency_re = 1'b0;
    d2l_pcfg_network_ctrl_w = pio_dec_write_data_d1  [31:0] ;
    d2l_pcfg_network_ctrl_we = 1'b0;
    d2l_pcfg_network_ctrl_re = 1'b0;
    d2l_pcfg_network_latency_w = pio_dec_write_data_d1  [31:0] ;
    d2l_pcfg_network_latency_we = 1'b0;
    d2l_pcfg_network_latency_re = 1'b0;
    d2l_st_dma_ctrl_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_ctrl_we = 1'b0;
    d2l_st_dma_ctrl_re = 1'b0;
    d2l_st_dma_num_blocks_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_num_blocks_we = 1'b0;
    d2l_st_dma_num_blocks_re = 1'b0;
    d2l_st_dma_rv_seg_mode_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_rv_seg_mode_we = 1'b0;
    d2l_st_dma_rv_seg_mode_re = 1'b0;
    d2l_st_dma_header_0_dim_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_dim_we = 1'b0;
    d2l_st_dma_header_0_dim_re = 1'b0;
    d2l_st_dma_header_0_start_addr_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_start_addr_we = 1'b0;
    d2l_st_dma_header_0_start_addr_re = 1'b0;
    d2l_st_dma_header_0_cycle_start_addr_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_start_addr_we = 1'b0;
    d2l_st_dma_header_0_cycle_start_addr_re = 1'b0;
    d2l_st_dma_header_0_range_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_0_we = 1'b0;
    d2l_st_dma_header_0_range_0_re = 1'b0;
    d2l_st_dma_header_0_stride_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_0_we = 1'b0;
    d2l_st_dma_header_0_stride_0_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_0_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_0_re = 1'b0;
    d2l_st_dma_header_0_range_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_1_we = 1'b0;
    d2l_st_dma_header_0_range_1_re = 1'b0;
    d2l_st_dma_header_0_stride_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_1_we = 1'b0;
    d2l_st_dma_header_0_stride_1_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_1_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_1_re = 1'b0;
    d2l_st_dma_header_0_range_2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_2_we = 1'b0;
    d2l_st_dma_header_0_range_2_re = 1'b0;
    d2l_st_dma_header_0_stride_2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_2_we = 1'b0;
    d2l_st_dma_header_0_stride_2_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_2_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_2_re = 1'b0;
    d2l_st_dma_header_0_range_3_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_3_we = 1'b0;
    d2l_st_dma_header_0_range_3_re = 1'b0;
    d2l_st_dma_header_0_stride_3_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_3_we = 1'b0;
    d2l_st_dma_header_0_stride_3_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_3_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_3_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_3_re = 1'b0;
    d2l_st_dma_header_0_range_4_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_4_we = 1'b0;
    d2l_st_dma_header_0_range_4_re = 1'b0;
    d2l_st_dma_header_0_stride_4_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_4_we = 1'b0;
    d2l_st_dma_header_0_stride_4_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_4_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_4_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_4_re = 1'b0;
    d2l_st_dma_header_0_range_5_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_5_we = 1'b0;
    d2l_st_dma_header_0_range_5_re = 1'b0;
    d2l_st_dma_header_0_stride_5_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_5_we = 1'b0;
    d2l_st_dma_header_0_stride_5_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_5_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_5_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_5_re = 1'b0;
    d2l_st_dma_header_0_range_6_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_range_6_we = 1'b0;
    d2l_st_dma_header_0_range_6_re = 1'b0;
    d2l_st_dma_header_0_stride_6_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_stride_6_we = 1'b0;
    d2l_st_dma_header_0_stride_6_re = 1'b0;
    d2l_st_dma_header_0_cycle_stride_6_w = pio_dec_write_data_d1  [31:0] ;
    d2l_st_dma_header_0_cycle_stride_6_we = 1'b0;
    d2l_st_dma_header_0_cycle_stride_6_re = 1'b0;
    d2l_ld_dma_ctrl_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_ctrl_we = 1'b0;
    d2l_ld_dma_ctrl_re = 1'b0;
    d2l_ld_dma_header_0_dim_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_dim_we = 1'b0;
    d2l_ld_dma_header_0_dim_re = 1'b0;
    d2l_ld_dma_header_0_start_addr_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_start_addr_we = 1'b0;
    d2l_ld_dma_header_0_start_addr_re = 1'b0;
    d2l_ld_dma_header_0_cycle_start_addr_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_start_addr_we = 1'b0;
    d2l_ld_dma_header_0_cycle_start_addr_re = 1'b0;
    d2l_ld_dma_header_0_range_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_0_we = 1'b0;
    d2l_ld_dma_header_0_range_0_re = 1'b0;
    d2l_ld_dma_header_0_stride_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_0_we = 1'b0;
    d2l_ld_dma_header_0_stride_0_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_0_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_0_re = 1'b0;
    d2l_ld_dma_header_0_range_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_1_we = 1'b0;
    d2l_ld_dma_header_0_range_1_re = 1'b0;
    d2l_ld_dma_header_0_stride_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_1_we = 1'b0;
    d2l_ld_dma_header_0_stride_1_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_1_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_1_re = 1'b0;
    d2l_ld_dma_header_0_range_2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_2_we = 1'b0;
    d2l_ld_dma_header_0_range_2_re = 1'b0;
    d2l_ld_dma_header_0_stride_2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_2_we = 1'b0;
    d2l_ld_dma_header_0_stride_2_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_2_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_2_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_2_re = 1'b0;
    d2l_ld_dma_header_0_range_3_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_3_we = 1'b0;
    d2l_ld_dma_header_0_range_3_re = 1'b0;
    d2l_ld_dma_header_0_stride_3_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_3_we = 1'b0;
    d2l_ld_dma_header_0_stride_3_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_3_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_3_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_3_re = 1'b0;
    d2l_ld_dma_header_0_range_4_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_4_we = 1'b0;
    d2l_ld_dma_header_0_range_4_re = 1'b0;
    d2l_ld_dma_header_0_stride_4_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_4_we = 1'b0;
    d2l_ld_dma_header_0_stride_4_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_4_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_4_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_4_re = 1'b0;
    d2l_ld_dma_header_0_range_5_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_5_we = 1'b0;
    d2l_ld_dma_header_0_range_5_re = 1'b0;
    d2l_ld_dma_header_0_stride_5_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_5_we = 1'b0;
    d2l_ld_dma_header_0_stride_5_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_5_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_5_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_5_re = 1'b0;
    d2l_ld_dma_header_0_range_6_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_6_we = 1'b0;
    d2l_ld_dma_header_0_range_6_re = 1'b0;
    d2l_ld_dma_header_0_stride_6_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_6_we = 1'b0;
    d2l_ld_dma_header_0_stride_6_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_6_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_6_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_6_re = 1'b0;
    d2l_ld_dma_header_0_range_7_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_range_7_we = 1'b0;
    d2l_ld_dma_header_0_range_7_re = 1'b0;
    d2l_ld_dma_header_0_stride_7_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_stride_7_we = 1'b0;
    d2l_ld_dma_header_0_stride_7_re = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_7_w = pio_dec_write_data_d1  [31:0] ;
    d2l_ld_dma_header_0_cycle_stride_7_we = 1'b0;
    d2l_ld_dma_header_0_cycle_stride_7_re = 1'b0;
    d2l_pcfg_dma_ctrl_w = pio_dec_write_data_d1  [31:0] ;
    d2l_pcfg_dma_ctrl_we = 1'b0;
    d2l_pcfg_dma_ctrl_re = 1'b0;
    d2l_pcfg_dma_header_start_addr_w = pio_dec_write_data_d1  [31:0] ;
    d2l_pcfg_dma_header_start_addr_we = 1'b0;
    d2l_pcfg_dma_header_start_addr_re = 1'b0;
    d2l_pcfg_dma_header_num_cfg_w = pio_dec_write_data_d1  [31:0] ;
    d2l_pcfg_dma_header_num_cfg_we = 1'b0;
    d2l_pcfg_dma_header_num_cfg_re = 1'b0;
    d2l_pcfg_broadcast_mux_w = pio_dec_write_data_d1  [31:0] ;
    d2l_pcfg_broadcast_mux_we = 1'b0;
    d2l_pcfg_broadcast_mux_re = 1'b0;
    
    casez(pio_dec_address_d1)
    //  Register: data_network_ctrl     Address: 0x0     External: false
    6'b000000:
      begin
        d2l_data_network_ctrl_we = pio_write_active & ~dec_pio_ack;
        d2l_data_network_ctrl_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_data_network_ctrl_r;
      end
    //  Register: data_network_latency     Address: 0x4     External: false
    6'b000001:
      begin
        d2l_data_network_latency_we = pio_write_active & ~dec_pio_ack;
        d2l_data_network_latency_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_data_network_latency_r;
      end
    //  Register: pcfg_network_ctrl     Address: 0x8     External: false
    6'b000010:
      begin
        d2l_pcfg_network_ctrl_we = pio_write_active & ~dec_pio_ack;
        d2l_pcfg_network_ctrl_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_pcfg_network_ctrl_r;
      end
    //  Register: pcfg_network_latency     Address: 0xc     External: false
    6'b000011:
      begin
        d2l_pcfg_network_latency_we = pio_write_active & ~dec_pio_ack;
        d2l_pcfg_network_latency_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_pcfg_network_latency_r;
      end
    //  Register: st_dma_ctrl     Address: 0x10     External: false
    6'b000100:
      begin
        d2l_st_dma_ctrl_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_ctrl_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_ctrl_r;
      end
    //  Register: st_dma_num_blocks     Address: 0x14     External: false
    6'b000101:
      begin
        d2l_st_dma_num_blocks_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_num_blocks_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_num_blocks_r;
      end
    //  Register: st_dma_rv_seg_mode     Address: 0x18     External: false
    6'b000110:
      begin
        d2l_st_dma_rv_seg_mode_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_rv_seg_mode_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_rv_seg_mode_r;
      end
    //  Register: st_dma_header_0.dim     Address: 0x1c     External: false
    6'b000111:
      begin
        d2l_st_dma_header_0_dim_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_dim_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_dim_r;
      end
    //  Register: st_dma_header_0.start_addr     Address: 0x20     External: false
    6'b001000:
      begin
        d2l_st_dma_header_0_start_addr_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_start_addr_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_start_addr_r;
      end
    //  Register: st_dma_header_0.cycle_start_addr     Address: 0x24     External: false
    6'b001001:
      begin
        d2l_st_dma_header_0_cycle_start_addr_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_start_addr_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_start_addr_r;
      end
    //  Register: st_dma_header_0.range_0     Address: 0x28     External: false
    6'b001010:
      begin
        d2l_st_dma_header_0_range_0_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_0_r;
      end
    //  Register: st_dma_header_0.stride_0     Address: 0x2c     External: false
    6'b001011:
      begin
        d2l_st_dma_header_0_stride_0_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_0_r;
      end
    //  Register: st_dma_header_0.cycle_stride_0     Address: 0x30     External: false
    6'b001100:
      begin
        d2l_st_dma_header_0_cycle_stride_0_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_0_r;
      end
    //  Register: st_dma_header_0.range_1     Address: 0x34     External: false
    6'b001101:
      begin
        d2l_st_dma_header_0_range_1_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_1_r;
      end
    //  Register: st_dma_header_0.stride_1     Address: 0x38     External: false
    6'b001110:
      begin
        d2l_st_dma_header_0_stride_1_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_1_r;
      end
    //  Register: st_dma_header_0.cycle_stride_1     Address: 0x3c     External: false
    6'b001111:
      begin
        d2l_st_dma_header_0_cycle_stride_1_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_1_r;
      end
    //  Register: st_dma_header_0.range_2     Address: 0x40     External: false
    6'b010000:
      begin
        d2l_st_dma_header_0_range_2_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_2_r;
      end
    //  Register: st_dma_header_0.stride_2     Address: 0x44     External: false
    6'b010001:
      begin
        d2l_st_dma_header_0_stride_2_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_2_r;
      end
    //  Register: st_dma_header_0.cycle_stride_2     Address: 0x48     External: false
    6'b010010:
      begin
        d2l_st_dma_header_0_cycle_stride_2_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_2_r;
      end
    //  Register: st_dma_header_0.range_3     Address: 0x4c     External: false
    6'b010011:
      begin
        d2l_st_dma_header_0_range_3_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_3_r;
      end
    //  Register: st_dma_header_0.stride_3     Address: 0x50     External: false
    6'b010100:
      begin
        d2l_st_dma_header_0_stride_3_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_3_r;
      end
    //  Register: st_dma_header_0.cycle_stride_3     Address: 0x54     External: false
    6'b010101:
      begin
        d2l_st_dma_header_0_cycle_stride_3_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_3_r;
      end
    //  Register: st_dma_header_0.range_4     Address: 0x58     External: false
    6'b010110:
      begin
        d2l_st_dma_header_0_range_4_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_4_r;
      end
    //  Register: st_dma_header_0.stride_4     Address: 0x5c     External: false
    6'b010111:
      begin
        d2l_st_dma_header_0_stride_4_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_4_r;
      end
    //  Register: st_dma_header_0.cycle_stride_4     Address: 0x60     External: false
    6'b011000:
      begin
        d2l_st_dma_header_0_cycle_stride_4_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_4_r;
      end
    //  Register: st_dma_header_0.range_5     Address: 0x64     External: false
    6'b011001:
      begin
        d2l_st_dma_header_0_range_5_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_5_r;
      end
    //  Register: st_dma_header_0.stride_5     Address: 0x68     External: false
    6'b011010:
      begin
        d2l_st_dma_header_0_stride_5_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_5_r;
      end
    //  Register: st_dma_header_0.cycle_stride_5     Address: 0x6c     External: false
    6'b011011:
      begin
        d2l_st_dma_header_0_cycle_stride_5_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_5_r;
      end
    //  Register: st_dma_header_0.range_6     Address: 0x70     External: false
    6'b011100:
      begin
        d2l_st_dma_header_0_range_6_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_range_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_range_6_r;
      end
    //  Register: st_dma_header_0.stride_6     Address: 0x74     External: false
    6'b011101:
      begin
        d2l_st_dma_header_0_stride_6_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_stride_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_stride_6_r;
      end
    //  Register: st_dma_header_0.cycle_stride_6     Address: 0x78     External: false
    6'b011110:
      begin
        d2l_st_dma_header_0_cycle_stride_6_we = pio_write_active & ~dec_pio_ack;
        d2l_st_dma_header_0_cycle_stride_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_st_dma_header_0_cycle_stride_6_r;
      end
    //  Register: ld_dma_ctrl     Address: 0x7c     External: false
    6'b011111:
      begin
        d2l_ld_dma_ctrl_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_ctrl_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_ctrl_r;
      end
    //  Register: ld_dma_header_0.dim     Address: 0x80     External: false
    6'b100000:
      begin
        d2l_ld_dma_header_0_dim_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_dim_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_dim_r;
      end
    //  Register: ld_dma_header_0.start_addr     Address: 0x84     External: false
    6'b100001:
      begin
        d2l_ld_dma_header_0_start_addr_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_start_addr_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_start_addr_r;
      end
    //  Register: ld_dma_header_0.cycle_start_addr     Address: 0x88     External: false
    6'b100010:
      begin
        d2l_ld_dma_header_0_cycle_start_addr_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_start_addr_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_start_addr_r;
      end
    //  Register: ld_dma_header_0.range_0     Address: 0x8c     External: false
    6'b100011:
      begin
        d2l_ld_dma_header_0_range_0_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_0_r;
      end
    //  Register: ld_dma_header_0.stride_0     Address: 0x90     External: false
    6'b100100:
      begin
        d2l_ld_dma_header_0_stride_0_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_0_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_0     Address: 0x94     External: false
    6'b100101:
      begin
        d2l_ld_dma_header_0_cycle_stride_0_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_0_r;
      end
    //  Register: ld_dma_header_0.range_1     Address: 0x98     External: false
    6'b100110:
      begin
        d2l_ld_dma_header_0_range_1_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_1_r;
      end
    //  Register: ld_dma_header_0.stride_1     Address: 0x9c     External: false
    6'b100111:
      begin
        d2l_ld_dma_header_0_stride_1_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_1_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_1     Address: 0xa0     External: false
    6'b101000:
      begin
        d2l_ld_dma_header_0_cycle_stride_1_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_1_r;
      end
    //  Register: ld_dma_header_0.range_2     Address: 0xa4     External: false
    6'b101001:
      begin
        d2l_ld_dma_header_0_range_2_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_2_r;
      end
    //  Register: ld_dma_header_0.stride_2     Address: 0xa8     External: false
    6'b101010:
      begin
        d2l_ld_dma_header_0_stride_2_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_2_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_2     Address: 0xac     External: false
    6'b101011:
      begin
        d2l_ld_dma_header_0_cycle_stride_2_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_2_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_2_r;
      end
    //  Register: ld_dma_header_0.range_3     Address: 0xb0     External: false
    6'b101100:
      begin
        d2l_ld_dma_header_0_range_3_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_3_r;
      end
    //  Register: ld_dma_header_0.stride_3     Address: 0xb4     External: false
    6'b101101:
      begin
        d2l_ld_dma_header_0_stride_3_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_3_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_3     Address: 0xb8     External: false
    6'b101110:
      begin
        d2l_ld_dma_header_0_cycle_stride_3_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_3_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_3_r;
      end
    //  Register: ld_dma_header_0.range_4     Address: 0xbc     External: false
    6'b101111:
      begin
        d2l_ld_dma_header_0_range_4_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_4_r;
      end
    //  Register: ld_dma_header_0.stride_4     Address: 0xc0     External: false
    6'b110000:
      begin
        d2l_ld_dma_header_0_stride_4_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_4_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_4     Address: 0xc4     External: false
    6'b110001:
      begin
        d2l_ld_dma_header_0_cycle_stride_4_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_4_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_4_r;
      end
    //  Register: ld_dma_header_0.range_5     Address: 0xc8     External: false
    6'b110010:
      begin
        d2l_ld_dma_header_0_range_5_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_5_r;
      end
    //  Register: ld_dma_header_0.stride_5     Address: 0xcc     External: false
    6'b110011:
      begin
        d2l_ld_dma_header_0_stride_5_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_5_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_5     Address: 0xd0     External: false
    6'b110100:
      begin
        d2l_ld_dma_header_0_cycle_stride_5_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_5_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_5_r;
      end
    //  Register: ld_dma_header_0.range_6     Address: 0xd4     External: false
    6'b110101:
      begin
        d2l_ld_dma_header_0_range_6_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_6_r;
      end
    //  Register: ld_dma_header_0.stride_6     Address: 0xd8     External: false
    6'b110110:
      begin
        d2l_ld_dma_header_0_stride_6_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_6_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_6     Address: 0xdc     External: false
    6'b110111:
      begin
        d2l_ld_dma_header_0_cycle_stride_6_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_6_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_6_r;
      end
    //  Register: ld_dma_header_0.range_7     Address: 0xe0     External: false
    6'b111000:
      begin
        d2l_ld_dma_header_0_range_7_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_range_7_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_range_7_r;
      end
    //  Register: ld_dma_header_0.stride_7     Address: 0xe4     External: false
    6'b111001:
      begin
        d2l_ld_dma_header_0_stride_7_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_stride_7_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_stride_7_r;
      end
    //  Register: ld_dma_header_0.cycle_stride_7     Address: 0xe8     External: false
    6'b111010:
      begin
        d2l_ld_dma_header_0_cycle_stride_7_we = pio_write_active & ~dec_pio_ack;
        d2l_ld_dma_header_0_cycle_stride_7_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_ld_dma_header_0_cycle_stride_7_r;
      end
    //  Register: pcfg_dma_ctrl     Address: 0xec     External: false
    6'b111011:
      begin
        d2l_pcfg_dma_ctrl_we = pio_write_active & ~dec_pio_ack;
        d2l_pcfg_dma_ctrl_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_pcfg_dma_ctrl_r;
      end
    //  Register: pcfg_dma_header.start_addr     Address: 0xf0     External: false
    6'b111100:
      begin
        d2l_pcfg_dma_header_start_addr_we = pio_write_active & ~dec_pio_ack;
        d2l_pcfg_dma_header_start_addr_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_pcfg_dma_header_start_addr_r;
      end
    //  Register: pcfg_dma_header.num_cfg     Address: 0xf4     External: false
    6'b111101:
      begin
        d2l_pcfg_dma_header_num_cfg_we = pio_write_active & ~dec_pio_ack;
        d2l_pcfg_dma_header_num_cfg_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_pcfg_dma_header_num_cfg_r;
      end
    //  Register: pcfg_broadcast_mux     Address: 0xf8     External: false
    6'b111110:
      begin
        d2l_pcfg_broadcast_mux_we = pio_write_active & ~dec_pio_ack;
        d2l_pcfg_broadcast_mux_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_pcfg_broadcast_mux_r;
      end
    endcase
  end
  
endmodule

