#=========================================================================
# Synopsys IC Validator Calibre DRC
#=========================================================================

name: intel16-synopsys-icv-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design-merged.oas

outputs:
  - antenna.results
  - collat.results
  - drc-drcd.results
  - drc-lu.results
  - drc-denall.results
  - drc-cden-lden-collat.results
  # - drc-fullchip.results

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source inputs/adk/run-icv-antenna.sh
  - source inputs/adk/run-icv-collat.sh
  - source inputs/adk/run-icv-drc-drcd.sh
  - source inputs/adk/run-icv-drc-lu.sh
  - source inputs/adk/run-icv-drc-denall.sh
  - source inputs/adk/run-icv-drc-cden-lden-collat.sh
  # - source inputs/adk/run-icv-drc-fullchip.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:
  - assert Tool( 'icv' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design-merged.oas' )
