#=========================================================================
# Synopsys IC Validator Calibre DRC
#=========================================================================

name: intel16-synopsys-icv-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design-merged.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source inputs/adk/run-drc-drcd.sh
  - source inputs/adk/run-drc-denall.sh
  - source inputs/adk/run-drc-IPall.sh
  - source inputs/adk/run-drc-IL.sh
  - source inputs/adk/run-drc-LU.sh
  - source inputs/adk/run-drc-TUC.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:
  - assert Tool( 'icv' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design-merged.gds' )
