#=========================================================================
# Synopsys IC Validator Calibre DRC
#=========================================================================

name: intel16-synopsys-icv-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design-merged.oas

outputs:
  - antenna.results
  - collat.results
  - drc-drcd.results
  - drc-lu.results
  - drc-denall.results
  - drc-cden-lden-collat.results

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - for rule_deck in $(echo "$rule_decks" | tr ',' '\n')
  - do
  -     bash ./inputs/adk/run-icv-$rule_deck.sh
  - done

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  rule_decks:
    - antenna
    - collat
    - drc-drcd
    - drc-lu
    - drc-denall
    - drc-cden-lden-collat

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:
  - assert Tool( 'icv' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design-merged.oas' )
