#=========================================================================
# custom-hack-lef-antenna
#=========================================================================

name: custom-hack-lef-antenna

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - hack_lef_antenna.py
