name: e2e_testbench

commands:
  - bash gen_testbench.sh
  # Script extract noteworthy tiles

outputs:
  - testbench.sv
  - input.raw
  - tiles_Tile_MemCore.list
  - tiles_Tile_PE.list
  - cmd.tcl

parameters:
  array_width: 12
  array_height: 12
  pipeline_config_interval: 8
  interconnect_only: False
  soc_only: False
  PWR_AWARE: False
  use_container: True
  use_local_garnet: True
  app_to_run: "tests/conv_3_3"
  waves: False
  clock_period: 1.1

postconditions:
  - assert File( 'outputs/testbench.sv' )        # must exist
