#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-post-place-blockage

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - custom-post-place-blockage.tcl

