name: sim-run

parameters:
  waveform: False
  tool: "XCELIUM"
  rtl_testvectors: ["test1", "test2", "test3", "test4"]

commands:
  - bash run_sim.sh

outputs:
  - run.log

postconditions:
  - assert File( 'outputs/run.log' )      # must exist

  - assert 'Error,' not in File( 'outputs/run.log' )
  - assert '*E,' not in File( 'outputs/run.log' )
