name: gen_sram_macro

commands:
  - bash gen_srams.sh

outputs:
  - sram.v
  - sram_pwr.v
  - sram.lef
  - sram.lib
  - sram.db
  - sram.gds

parameters:
  num_words: 512
  word_size: 16
  mux_size: 8
  corner: "tt0p8v25c"
