# =============================================================================
# Compile Test
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: build_test

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh

# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  TEST_NAME: undefined
  ARM_IP_DIR: undefined
