#=========================================================================
# Create garnet testbench for memcore
#=========================================================================
#
# Author : Maxwell Strange
# Date   : August 6, 2020
#

name: gen_testbench

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - testbench.sv
  - array_rtl.v
  - DW_fp_add.v
  - DW_fp_mult.v
  - design.args

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source run.sh
#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

#parameters:
#  design_name: undefined
#  strip_path: th/dut


