#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-power-mu

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - globalnetconnect.tcl
  - power-strategy.tcl
