#=========================================================================
# Netlist Fixing
#=========================================================================
# Author : Alex Carsello
# Date   : April 17, 2020
#

name: netlist-fixing

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - netlist-fixing.tcl

