
name: pwr-aware-gls 


#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.pg.v


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p logs
  - source ./run_sim.sh 
  - cp mflowgen-run.log logs/gls.log 
#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

postconditions:

  - assert 'PASS' not in File( 'logs/gls.log' )

