//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /sim/ajcars/aha-arm-soc-june-2019/components/pad_frame/GarnetSOC_pad_frame.svp
//  Source template: GarnetSOC_pad_frame
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// Garnet SoC top level with pads
// IO_LIST (_GENESIS2_IMMUTABLE_PRIORITY_) = 
//	[ { direction=>input, name=>tlx_resetn_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>tlx_fwd_clk_ref_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>output, name=>tlx_fwd_clk_ref_o, pad=>digital, side=>left, width=>1 },
//	  { direction=>output, name=>tlx_fwd_toggle_o, pad=>digital, side=>left, width=>1 },
//	  { direction=>output, name=>tlx_fwd_tvalid_p_o, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>tlx_fwd_tready_p_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>output, name=>tlx_fwd_tdata_lo_p_o, pad=>digital, side=>bottom, width=>16 },
//	  { direction=>output, name=>tlx_fwd_tdata_hi_p_o, pad=>digital, side=>left, width=>24 },
//	  { direction=>output, name=>tlx_fwd_tvalid_t_o, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>tlx_fwd_tready_t_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>cgra_clk_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>output, name=>tlx_fwd_tdata_t_o, pad=>digital, side=>left, width=>2 },
//	  { direction=>input, name=>tlx_rev_clk_ref_i, pad=>digital, side=>right, width=>1 },
//	  { direction=>input, name=>tlx_rev_toggle_i, pad=>digital, side=>right, width=>1 },
//	  { direction=>output, name=>tlx_rev_toggle_o, pad=>digital, side=>right, width=>1 },
//	  { direction=>input, name=>tlx_rev_tvalid_p_i, pad=>digital, side=>right, width=>1 },
//	  { direction=>output, name=>tlx_rev_tready_p_o, pad=>digital, side=>right, width=>1 },
//	  { direction=>input, name=>tlx_rev_tdata_lo_p_i, pad=>digital, side=>right, width=>45 },
//	  { direction=>input, name=>master_clk_i, pad=>digital, side=>right, width=>1 },
//	  { direction=>input, name=>tlx_rev_tdata_hi_p_i, pad=>digital, side=>bottom, width=>35 },
//	  { direction=>input, name=>tlx_rev_tvalid_t_i, pad=>digital, side=>right, width=>1 },
//	  { direction=>output, name=>tlx_rev_tready_t_o, pad=>digital, side=>right, width=>1 },
//	  { direction=>input, name=>tlx_rev_tdata_t_i, pad=>digital, side=>left, width=>3 },
//	  { direction=>output, name=>trace_clk_o, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>output, name=>trace_data_o, pad=>digital, side=>bottom, width=>4 },
//	  { direction=>output, name=>trace_swo_o, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>input, name=>dap_tdi_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>dap_ntrst_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>dap_tck_i, pad=>digital, side=>left, width=>1 },
//	  { direction=>inout, inport=>dap_tms_i, io_ctrl=>dap_swdo_en_o, name=>dap_tms_io, outport=>dap_swdo_o, pad=>digital, side=>left, width=>1 },
//	  { direction=>output, name=>dap_tdo_o, pad=>digital, side=>left, width=>1 },
//	  { direction=>input, name=>uart0_rx_i, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>output, name=>uart0_tx_o, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>output, name=>uart0_txen_o, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>input, name=>uart1_rx_i, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>output, name=>uart1_tx_o, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>output, name=>uart1_txen_o, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>input, name=>po_resetn_i, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>input, name=>sys_resetn_i, pad=>digital, side=>bottom, width=>1 },
//	  { direction=>output, name=>doorbell_clk_o, pad=>digital, side=>right, width=>1 }
//	]
//

// BUTTERPHY_IO_LIST (_GENESIS2_IMMUTABLE_PRIORITY_) = 
//	[ { domain=>0, is_power=>0, name=>ext_clk_async_p, pad=>PDB2ANA_V, type=>analog },
//	  { domain=>0, is_power=>0, name=>ext_clk_async_n, pad=>PDB2ANA_V, type=>analog },
//	  { domain=>1, is_power=>0, name=>ext_clkn, pad=>PDB3AC_V, type=>analog },
//	  { domain=>1, is_power=>0, name=>ext_clkp, pad=>PDB3AC_V, type=>analog },
//	  { domain=>1, is_power=>1, name=>CVDD, pad=>PVDD3ACM_V, type=>analog },
//	  { domain=>1, is_power=>1, name=>CVSS, pad=>PVDD3ACM_V, type=>analog },
//	  { domain=>2, is_power=>1, name=>AVDD, pad=>PVDD3ACM_V, type=>analog },
//	  { domain=>2, is_power=>1, name=>AVSS, pad=>PVDD3ACM_V, type=>analog },
//	  { domain=>2, is_power=>0, name=>ext_Vcm, pad=>PDB3AC_V, type=>analog },
//	  { domain=>2, is_power=>0, name=>ext_Vcal, pad=>PDB3AC_V, type=>analog },
//	  { domain=>3, is_power=>0, name=>ext_clk_test0_n, pad=>PDB2ANA_V, type=>analog },
//	  { domain=>3, is_power=>0, name=>ext_clk_test0_p, pad=>PDB2ANA_V, type=>analog },
//	  { domain=>3, is_power=>0, name=>ext_clk_test1_p, pad=>PDB2ANA_V, type=>analog },
//	  { domain=>3, is_power=>0, name=>ext_clk_test1_n, pad=>PDB2ANA_V, type=>analog },
//	  { direction=>input, domain=>3, is_power=>0, name=>jtag_intf_i_phy_tck, pad=>PDDWUWSWCDG_V, type=>digital },
//	  { direction=>input, domain=>3, is_power=>0, name=>jtag_intf_i_phy_tdi, pad=>PDDWUWSWCDG_V, type=>digital },
//	  { direction=>output, domain=>3, is_power=>0, name=>jtag_intf_i_phy_tdo, pad=>PDDWUWSWCDG_V, type=>digital },
//	  { direction=>input, domain=>3, is_power=>0, name=>jtag_intf_i_phy_tms, pad=>PDDWUWSWCDG_V, type=>digital },
//	  { direction=>input, domain=>3, is_power=>0, name=>jtag_intf_i_phy_trst_n, pad=>PDDWUWSWCDG_V, type=>digital },
//	  { direction=>input, domain=>3, is_power=>0, name=>ext_rstb, pad=>PDDWUWSWCDG_V, type=>digital },
//	  { direction=>input, domain=>3, is_power=>0, name=>ext_dump_start, pad=>PDDWUWSWCDG_V, type=>digital }
//	]
//



module GarnetSOC_pad_frame (
    input pad_jtag_intf_i_phy_tck,
    input pad_jtag_intf_i_phy_tdi,
    output pad_jtag_intf_i_phy_tdo,
    input pad_jtag_intf_i_phy_tms,
    input pad_jtag_intf_i_phy_trst_n,
    input pad_ext_rstb,
    input pad_ext_dump_start,
    input [0:0] pad_tlx_resetn_i,
    input [0:0] pad_tlx_fwd_clk_ref_i,
    output [0:0] pad_tlx_fwd_clk_ref_o,
    output [0:0] pad_tlx_fwd_toggle_o,
    output [0:0] pad_tlx_fwd_tvalid_p_o,
    input [0:0] pad_tlx_fwd_tready_p_i,
    output [15:0] pad_tlx_fwd_tdata_lo_p_o,
    output [23:0] pad_tlx_fwd_tdata_hi_p_o,
    output [0:0] pad_tlx_fwd_tvalid_t_o,
    input [0:0] pad_tlx_fwd_tready_t_i,
    input [0:0] pad_cgra_clk_i,
    output [1:0] pad_tlx_fwd_tdata_t_o,
    input [0:0] pad_tlx_rev_clk_ref_i,
    input [0:0] pad_tlx_rev_toggle_i,
    output [0:0] pad_tlx_rev_toggle_o,
    input [0:0] pad_tlx_rev_tvalid_p_i,
    output [0:0] pad_tlx_rev_tready_p_o,
    input [44:0] pad_tlx_rev_tdata_lo_p_i,
    input [0:0] pad_master_clk_i,
    input [34:0] pad_tlx_rev_tdata_hi_p_i,
    input [0:0] pad_tlx_rev_tvalid_t_i,
    output [0:0] pad_tlx_rev_tready_t_o,
    input [2:0] pad_tlx_rev_tdata_t_i,
    output [0:0] pad_trace_clk_o,
    output [3:0] pad_trace_data_o,
    output [0:0] pad_trace_swo_o,
    input [0:0] pad_dap_tdi_i,
    input [0:0] pad_dap_ntrst_i,
    input [0:0] pad_dap_tck_i,
    inout [0:0] pad_dap_tms_io,
    output [0:0] pad_dap_tdo_o,
    input [0:0] pad_uart0_rx_i,
    output [0:0] pad_uart0_tx_o,
    output [0:0] pad_uart0_txen_o,
    input [0:0] pad_uart1_rx_i,
    output [0:0] pad_uart1_tx_o,
    output [0:0] pad_uart1_txen_o,
    input [0:0] pad_po_resetn_i,
    input [0:0] pad_sys_resetn_i,
    output [0:0] pad_doorbell_clk_o
);

// Now create wires that will connect from pads to core module
  wire [0:0] tlx_resetn_i_int;
  wire [0:0] tlx_fwd_clk_ref_i_int;
  wire [0:0] tlx_fwd_clk_ref_o_int;
  wire [0:0] tlx_fwd_toggle_o_int;
  wire [0:0] tlx_fwd_tvalid_p_o_int;
  wire [0:0] tlx_fwd_tready_p_i_int;
  wire [15:0] tlx_fwd_tdata_lo_p_o_int;
  wire [23:0] tlx_fwd_tdata_hi_p_o_int;
  wire [0:0] tlx_fwd_tvalid_t_o_int;
  wire [0:0] tlx_fwd_tready_t_i_int;
  wire [0:0] cgra_clk_i_int;
  wire [1:0] tlx_fwd_tdata_t_o_int;
  wire [0:0] tlx_rev_clk_ref_i_int;
  wire [0:0] tlx_rev_toggle_i_int;
  wire [0:0] tlx_rev_toggle_o_int;
  wire [0:0] tlx_rev_tvalid_p_i_int;
  wire [0:0] tlx_rev_tready_p_o_int;
  wire [44:0] tlx_rev_tdata_lo_p_i_int;
  wire [0:0] master_clk_i_int;
  wire [34:0] tlx_rev_tdata_hi_p_i_int;
  wire [0:0] tlx_rev_tvalid_t_i_int;
  wire [0:0] tlx_rev_tready_t_o_int;
  wire [2:0] tlx_rev_tdata_t_i_int;
  wire [0:0] trace_clk_o_int;
  wire [3:0] trace_data_o_int;
  wire [0:0] trace_swo_o_int;
  wire [0:0] dap_tdi_i_int;
  wire [0:0] dap_ntrst_i_int;
  wire [0:0] dap_tck_i_int;
  wire dap_swdo_en_o;
  wire dap_tms_i;
  wire dap_swdo_o;
  wire [0:0] dap_tdo_o_int;
  wire [0:0] uart0_rx_i_int;
  wire [0:0] uart0_tx_o_int;
  wire [0:0] uart0_txen_o_int;
  wire [0:0] uart1_rx_i_int;
  wire [0:0] uart1_tx_o_int;
  wire [0:0] uart1_txen_o_int;
  wire [0:0] po_resetn_i_int;
  wire [0:0] sys_resetn_i_int;
  wire [0:0] doorbell_clk_o_int;
  wire rte;
  wire out_pad_ds0;
  wire out_pad_ds1;
  wire out_pad_ds2;

  // Corner cells
  PCORNER corner_ll(.RTE(rte));
  PCORNER corner_lr(.RTE(rte));
  PCORNER corner_ul(.RTE(rte));
  PCORNER corner_ur(.RTE(rte));
  // RTE stuff
  PCBRTE_V    IOPAD_bottom_RTE_DIG(.IRTE(1'b0), .RTE(rte));
  PCBRTE_H    IOPAD_left_RTE_DIG(.IRTE(1'b0), .RTE(rte));
  PCBRTE_H    IOPAD_right_RTE_DIG(.IRTE(1'b0), .RTE(rte));
  // POC stuff
  PVDD2POCM_V IOPAD_bottom_POC_DIG(.RTE(rte));
  //PVDD2POCM_H IOPAD_left_POC_DIG(.RTE(rte));
  //PVDD2POCM_H IOPAD_right_POC_DIG(.RTE(rte));






// Now instantiate all pads
  PRWDWUWSWCDGH_H IOPAD_left_tlx_resetn_i_0 (
    .PAD(pad_tlx_resetn_i[0]),
    .C(tlx_resetn_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_clk_ref_i_0 (
    .PAD(pad_tlx_fwd_clk_ref_i[0]),
    .C(tlx_fwd_clk_ref_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_clk_ref_o_0 (
    .PAD(pad_tlx_fwd_clk_ref_o[0]),
    .I(tlx_fwd_clk_ref_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_toggle_o_0 (
    .PAD(pad_tlx_fwd_toggle_o[0]),
    .I(tlx_fwd_toggle_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tvalid_p_o_0 (
    .PAD(pad_tlx_fwd_tvalid_p_o[0]),
    .I(tlx_fwd_tvalid_p_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tready_p_i_0 (
    .PAD(pad_tlx_fwd_tready_p_i[0]),
    .C(tlx_fwd_tready_p_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_0 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[0]),
    .I(tlx_fwd_tdata_lo_p_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_1 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[1]),
    .I(tlx_fwd_tdata_lo_p_o_int[1]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_2 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[2]),
    .I(tlx_fwd_tdata_lo_p_o_int[2]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_3 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[3]),
    .I(tlx_fwd_tdata_lo_p_o_int[3]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_4 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[4]),
    .I(tlx_fwd_tdata_lo_p_o_int[4]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_5 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[5]),
    .I(tlx_fwd_tdata_lo_p_o_int[5]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_6 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[6]),
    .I(tlx_fwd_tdata_lo_p_o_int[6]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_7 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[7]),
    .I(tlx_fwd_tdata_lo_p_o_int[7]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_8 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[8]),
    .I(tlx_fwd_tdata_lo_p_o_int[8]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_9 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[9]),
    .I(tlx_fwd_tdata_lo_p_o_int[9]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_10 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[10]),
    .I(tlx_fwd_tdata_lo_p_o_int[10]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_11 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[11]),
    .I(tlx_fwd_tdata_lo_p_o_int[11]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_12 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[12]),
    .I(tlx_fwd_tdata_lo_p_o_int[12]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_13 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[13]),
    .I(tlx_fwd_tdata_lo_p_o_int[13]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_14 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[14]),
    .I(tlx_fwd_tdata_lo_p_o_int[14]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_fwd_tdata_lo_p_o_15 (
    .PAD(pad_tlx_fwd_tdata_lo_p_o[15]),
    .I(tlx_fwd_tdata_lo_p_o_int[15]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_0 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[0]),
    .I(tlx_fwd_tdata_hi_p_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_1 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[1]),
    .I(tlx_fwd_tdata_hi_p_o_int[1]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_2 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[2]),
    .I(tlx_fwd_tdata_hi_p_o_int[2]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_3 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[3]),
    .I(tlx_fwd_tdata_hi_p_o_int[3]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_4 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[4]),
    .I(tlx_fwd_tdata_hi_p_o_int[4]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_5 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[5]),
    .I(tlx_fwd_tdata_hi_p_o_int[5]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_6 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[6]),
    .I(tlx_fwd_tdata_hi_p_o_int[6]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_7 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[7]),
    .I(tlx_fwd_tdata_hi_p_o_int[7]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_8 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[8]),
    .I(tlx_fwd_tdata_hi_p_o_int[8]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_9 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[9]),
    .I(tlx_fwd_tdata_hi_p_o_int[9]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_10 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[10]),
    .I(tlx_fwd_tdata_hi_p_o_int[10]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_11 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[11]),
    .I(tlx_fwd_tdata_hi_p_o_int[11]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_12 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[12]),
    .I(tlx_fwd_tdata_hi_p_o_int[12]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_13 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[13]),
    .I(tlx_fwd_tdata_hi_p_o_int[13]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_14 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[14]),
    .I(tlx_fwd_tdata_hi_p_o_int[14]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_15 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[15]),
    .I(tlx_fwd_tdata_hi_p_o_int[15]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_16 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[16]),
    .I(tlx_fwd_tdata_hi_p_o_int[16]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_17 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[17]),
    .I(tlx_fwd_tdata_hi_p_o_int[17]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_18 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[18]),
    .I(tlx_fwd_tdata_hi_p_o_int[18]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_19 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[19]),
    .I(tlx_fwd_tdata_hi_p_o_int[19]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_20 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[20]),
    .I(tlx_fwd_tdata_hi_p_o_int[20]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_21 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[21]),
    .I(tlx_fwd_tdata_hi_p_o_int[21]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_22 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[22]),
    .I(tlx_fwd_tdata_hi_p_o_int[22]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_hi_p_o_23 (
    .PAD(pad_tlx_fwd_tdata_hi_p_o[23]),
    .I(tlx_fwd_tdata_hi_p_o_int[23]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tvalid_t_o_0 (
    .PAD(pad_tlx_fwd_tvalid_t_o[0]),
    .I(tlx_fwd_tvalid_t_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tready_t_i_0 (
    .PAD(pad_tlx_fwd_tready_t_i[0]),
    .C(tlx_fwd_tready_t_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_cgra_clk_i_0 (
    .PAD(pad_cgra_clk_i[0]),
    .C(cgra_clk_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_t_o_0 (
    .PAD(pad_tlx_fwd_tdata_t_o[0]),
    .I(tlx_fwd_tdata_t_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_fwd_tdata_t_o_1 (
    .PAD(pad_tlx_fwd_tdata_t_o[1]),
    .I(tlx_fwd_tdata_t_o_int[1]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_clk_ref_i_0 (
    .PAD(pad_tlx_rev_clk_ref_i[0]),
    .C(tlx_rev_clk_ref_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_toggle_i_0 (
    .PAD(pad_tlx_rev_toggle_i[0]),
    .C(tlx_rev_toggle_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_toggle_o_0 (
    .PAD(pad_tlx_rev_toggle_o[0]),
    .I(tlx_rev_toggle_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tvalid_p_i_0 (
    .PAD(pad_tlx_rev_tvalid_p_i[0]),
    .C(tlx_rev_tvalid_p_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tready_p_o_0 (
    .PAD(pad_tlx_rev_tready_p_o[0]),
    .I(tlx_rev_tready_p_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_0 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[0]),
    .C(tlx_rev_tdata_lo_p_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_1 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[1]),
    .C(tlx_rev_tdata_lo_p_i_int[1]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_2 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[2]),
    .C(tlx_rev_tdata_lo_p_i_int[2]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_3 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[3]),
    .C(tlx_rev_tdata_lo_p_i_int[3]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_4 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[4]),
    .C(tlx_rev_tdata_lo_p_i_int[4]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_5 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[5]),
    .C(tlx_rev_tdata_lo_p_i_int[5]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_6 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[6]),
    .C(tlx_rev_tdata_lo_p_i_int[6]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_7 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[7]),
    .C(tlx_rev_tdata_lo_p_i_int[7]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_8 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[8]),
    .C(tlx_rev_tdata_lo_p_i_int[8]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_9 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[9]),
    .C(tlx_rev_tdata_lo_p_i_int[9]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_10 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[10]),
    .C(tlx_rev_tdata_lo_p_i_int[10]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_11 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[11]),
    .C(tlx_rev_tdata_lo_p_i_int[11]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_12 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[12]),
    .C(tlx_rev_tdata_lo_p_i_int[12]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_13 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[13]),
    .C(tlx_rev_tdata_lo_p_i_int[13]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_14 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[14]),
    .C(tlx_rev_tdata_lo_p_i_int[14]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_15 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[15]),
    .C(tlx_rev_tdata_lo_p_i_int[15]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_16 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[16]),
    .C(tlx_rev_tdata_lo_p_i_int[16]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_17 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[17]),
    .C(tlx_rev_tdata_lo_p_i_int[17]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_18 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[18]),
    .C(tlx_rev_tdata_lo_p_i_int[18]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_19 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[19]),
    .C(tlx_rev_tdata_lo_p_i_int[19]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_20 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[20]),
    .C(tlx_rev_tdata_lo_p_i_int[20]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_21 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[21]),
    .C(tlx_rev_tdata_lo_p_i_int[21]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_22 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[22]),
    .C(tlx_rev_tdata_lo_p_i_int[22]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_23 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[23]),
    .C(tlx_rev_tdata_lo_p_i_int[23]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_24 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[24]),
    .C(tlx_rev_tdata_lo_p_i_int[24]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_25 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[25]),
    .C(tlx_rev_tdata_lo_p_i_int[25]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_26 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[26]),
    .C(tlx_rev_tdata_lo_p_i_int[26]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_27 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[27]),
    .C(tlx_rev_tdata_lo_p_i_int[27]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_28 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[28]),
    .C(tlx_rev_tdata_lo_p_i_int[28]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_29 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[29]),
    .C(tlx_rev_tdata_lo_p_i_int[29]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_30 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[30]),
    .C(tlx_rev_tdata_lo_p_i_int[30]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_31 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[31]),
    .C(tlx_rev_tdata_lo_p_i_int[31]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_32 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[32]),
    .C(tlx_rev_tdata_lo_p_i_int[32]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_33 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[33]),
    .C(tlx_rev_tdata_lo_p_i_int[33]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_34 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[34]),
    .C(tlx_rev_tdata_lo_p_i_int[34]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_35 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[35]),
    .C(tlx_rev_tdata_lo_p_i_int[35]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_36 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[36]),
    .C(tlx_rev_tdata_lo_p_i_int[36]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_37 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[37]),
    .C(tlx_rev_tdata_lo_p_i_int[37]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_38 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[38]),
    .C(tlx_rev_tdata_lo_p_i_int[38]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_39 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[39]),
    .C(tlx_rev_tdata_lo_p_i_int[39]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_40 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[40]),
    .C(tlx_rev_tdata_lo_p_i_int[40]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_41 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[41]),
    .C(tlx_rev_tdata_lo_p_i_int[41]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_42 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[42]),
    .C(tlx_rev_tdata_lo_p_i_int[42]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_43 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[43]),
    .C(tlx_rev_tdata_lo_p_i_int[43]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tdata_lo_p_i_44 (
    .PAD(pad_tlx_rev_tdata_lo_p_i[44]),
    .C(tlx_rev_tdata_lo_p_i_int[44]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_master_clk_i_0 (
    .PAD(pad_master_clk_i[0]),
    .C(master_clk_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_0 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[0]),
    .C(tlx_rev_tdata_hi_p_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_1 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[1]),
    .C(tlx_rev_tdata_hi_p_i_int[1]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_2 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[2]),
    .C(tlx_rev_tdata_hi_p_i_int[2]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_3 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[3]),
    .C(tlx_rev_tdata_hi_p_i_int[3]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_4 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[4]),
    .C(tlx_rev_tdata_hi_p_i_int[4]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_5 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[5]),
    .C(tlx_rev_tdata_hi_p_i_int[5]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_6 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[6]),
    .C(tlx_rev_tdata_hi_p_i_int[6]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_7 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[7]),
    .C(tlx_rev_tdata_hi_p_i_int[7]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_8 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[8]),
    .C(tlx_rev_tdata_hi_p_i_int[8]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_9 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[9]),
    .C(tlx_rev_tdata_hi_p_i_int[9]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_10 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[10]),
    .C(tlx_rev_tdata_hi_p_i_int[10]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_11 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[11]),
    .C(tlx_rev_tdata_hi_p_i_int[11]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_12 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[12]),
    .C(tlx_rev_tdata_hi_p_i_int[12]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_13 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[13]),
    .C(tlx_rev_tdata_hi_p_i_int[13]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_14 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[14]),
    .C(tlx_rev_tdata_hi_p_i_int[14]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_15 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[15]),
    .C(tlx_rev_tdata_hi_p_i_int[15]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_16 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[16]),
    .C(tlx_rev_tdata_hi_p_i_int[16]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_17 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[17]),
    .C(tlx_rev_tdata_hi_p_i_int[17]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_18 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[18]),
    .C(tlx_rev_tdata_hi_p_i_int[18]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_19 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[19]),
    .C(tlx_rev_tdata_hi_p_i_int[19]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_20 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[20]),
    .C(tlx_rev_tdata_hi_p_i_int[20]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_21 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[21]),
    .C(tlx_rev_tdata_hi_p_i_int[21]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_22 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[22]),
    .C(tlx_rev_tdata_hi_p_i_int[22]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_23 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[23]),
    .C(tlx_rev_tdata_hi_p_i_int[23]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_24 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[24]),
    .C(tlx_rev_tdata_hi_p_i_int[24]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_25 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[25]),
    .C(tlx_rev_tdata_hi_p_i_int[25]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_26 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[26]),
    .C(tlx_rev_tdata_hi_p_i_int[26]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_27 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[27]),
    .C(tlx_rev_tdata_hi_p_i_int[27]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_28 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[28]),
    .C(tlx_rev_tdata_hi_p_i_int[28]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_29 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[29]),
    .C(tlx_rev_tdata_hi_p_i_int[29]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_30 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[30]),
    .C(tlx_rev_tdata_hi_p_i_int[30]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_31 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[31]),
    .C(tlx_rev_tdata_hi_p_i_int[31]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_32 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[32]),
    .C(tlx_rev_tdata_hi_p_i_int[32]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_33 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[33]),
    .C(tlx_rev_tdata_hi_p_i_int[33]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_tlx_rev_tdata_hi_p_i_34 (
    .PAD(pad_tlx_rev_tdata_hi_p_i[34]),
    .C(tlx_rev_tdata_hi_p_i_int[34]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tvalid_t_i_0 (
    .PAD(pad_tlx_rev_tvalid_t_i[0]),
    .C(tlx_rev_tvalid_t_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_tlx_rev_tready_t_o_0 (
    .PAD(pad_tlx_rev_tready_t_o[0]),
    .I(tlx_rev_tready_t_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_rev_tdata_t_i_0 (
    .PAD(pad_tlx_rev_tdata_t_i[0]),
    .C(tlx_rev_tdata_t_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_rev_tdata_t_i_1 (
    .PAD(pad_tlx_rev_tdata_t_i[1]),
    .C(tlx_rev_tdata_t_i_int[1]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_tlx_rev_tdata_t_i_2 (
    .PAD(pad_tlx_rev_tdata_t_i[2]),
    .C(tlx_rev_tdata_t_i_int[2]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_trace_clk_o_0 (
    .PAD(pad_trace_clk_o[0]),
    .I(trace_clk_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_trace_data_o_0 (
    .PAD(pad_trace_data_o[0]),
    .I(trace_data_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_trace_data_o_1 (
    .PAD(pad_trace_data_o[1]),
    .I(trace_data_o_int[1]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_trace_data_o_2 (
    .PAD(pad_trace_data_o[2]),
    .I(trace_data_o_int[2]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_trace_data_o_3 (
    .PAD(pad_trace_data_o[3]),
    .I(trace_data_o_int[3]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_trace_swo_o_0 (
    .PAD(pad_trace_swo_o[0]),
    .I(trace_swo_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_dap_tdi_i_0 (
    .PAD(pad_dap_tdi_i[0]),
    .C(dap_tdi_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_dap_ntrst_i_0 (
    .PAD(pad_dap_ntrst_i[0]),
    .C(dap_ntrst_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_dap_tck_i_0 (
    .PAD(pad_dap_tck_i[0]),
    .C(dap_tck_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_dap_tms_io_0 (
    .PAD(pad_dap_tms_io[0]),
    .C(dap_tms_i),
    .I(dap_swdo_o),
    .IE(~dap_swdo_en_o),
    .OEN(~dap_swdo_en_o),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_left_dap_tdo_o_0 (
    .PAD(pad_dap_tdo_o[0]),
    .I(dap_tdo_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_uart0_rx_i_0 (
    .PAD(pad_uart0_rx_i[0]),
    .C(uart0_rx_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_uart0_tx_o_0 (
    .PAD(pad_uart0_tx_o[0]),
    .I(uart0_tx_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_uart0_txen_o_0 (
    .PAD(pad_uart0_txen_o[0]),
    .I(uart0_txen_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_uart1_rx_i_0 (
    .PAD(pad_uart1_rx_i[0]),
    .C(uart1_rx_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_uart1_tx_o_0 (
    .PAD(pad_uart1_tx_o[0]),
    .I(uart1_tx_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_uart1_txen_o_0 (
    .PAD(pad_uart1_txen_o[0]),
    .I(uart1_txen_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_po_resetn_i_0 (
    .PAD(pad_po_resetn_i[0]),
    .C(po_resetn_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_V IOPAD_bottom_sys_resetn_i_0 (
    .PAD(pad_sys_resetn_i[0]),
    .C(sys_resetn_i_int[0]),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );
  PRWDWUWSWCDGH_H IOPAD_right_doorbell_clk_o_0 (
    .PAD(pad_doorbell_clk_o[0]),
    .I(doorbell_clk_o_int[0]),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(out_pad_ds0),
    .DS1(out_pad_ds1),
    .DS2(out_pad_ds2),
    .PU(1'b0),
    .PD(1'b0),
    .ST(1'b0),
    .SL(1'b0),
    .RTE(rte)
  );

  GarnetSOC #(
    .TLX_REV_DATA_LO_WIDTH(45),
    .TLX_FWD_DATA_LO_WIDTH(16)
  ) core (
    .out_pad_ds0(out_pad_ds0),
    .out_pad_ds1(out_pad_ds1),
    .out_pad_ds2(out_pad_ds2),
    .test_mode_i(1'b0),
    .tlx_resetn_i(tlx_resetn_i_int),
    .tlx_fwd_clk_ref_i(tlx_fwd_clk_ref_i_int),
    .tlx_fwd_clk_ref_o(tlx_fwd_clk_ref_o_int),
    .tlx_fwd_toggle_o(tlx_fwd_toggle_o_int),
    .tlx_fwd_tvalid_p_o(tlx_fwd_tvalid_p_o_int),
    .tlx_fwd_tready_p_i(tlx_fwd_tready_p_i_int),
    .tlx_fwd_tdata_lo_p_o(tlx_fwd_tdata_lo_p_o_int),
    .tlx_fwd_tdata_hi_p_o(tlx_fwd_tdata_hi_p_o_int),
    .tlx_fwd_tvalid_t_o(tlx_fwd_tvalid_t_o_int),
    .tlx_fwd_tready_t_i(tlx_fwd_tready_t_i_int),
    .cgra_clk_i(cgra_clk_i_int),
    .tlx_fwd_tdata_t_o(tlx_fwd_tdata_t_o_int),
    .tlx_rev_clk_ref_i(tlx_rev_clk_ref_i_int),
    .tlx_rev_toggle_i(tlx_rev_toggle_i_int),
    .tlx_rev_toggle_o(tlx_rev_toggle_o_int),
    .tlx_rev_tvalid_p_i(tlx_rev_tvalid_p_i_int),
    .tlx_rev_tready_p_o(tlx_rev_tready_p_o_int),
    .tlx_rev_tdata_lo_p_i(tlx_rev_tdata_lo_p_i_int),
    .master_clk_i(master_clk_i_int),
    .tlx_rev_tdata_hi_p_i(tlx_rev_tdata_hi_p_i_int),
    .tlx_rev_tvalid_t_i(tlx_rev_tvalid_t_i_int),
    .tlx_rev_tready_t_o(tlx_rev_tready_t_o_int),
    .tlx_rev_tdata_t_i(tlx_rev_tdata_t_i_int),
    .trace_clk_o(trace_clk_o_int),
    .trace_data_o(trace_data_o_int),
    .trace_swo_o(trace_swo_o_int),
    .dap_tdi_i(dap_tdi_i_int),
    .dap_ntrst_i(dap_ntrst_i_int),
    .dap_tck_i(dap_tck_i_int),
    .dap_swdo_en_o(dap_swdo_en_o),
    .dap_swdo_o(dap_swdo_o),
    .dap_tms_i(dap_tms_i),
    .dap_tdo_o(dap_tdo_o_int),
    .uart0_rx_i(uart0_rx_i_int),
    .uart0_tx_o(uart0_tx_o_int),
    .uart0_txen_o(uart0_txen_o_int),
    .uart1_rx_i(uart1_rx_i_int),
    .uart1_tx_o(uart1_tx_o_int),
    .uart1_txen_o(uart1_txen_o_int),
    .po_resetn_i(po_resetn_i_int),
    .sys_resetn_i(sys_resetn_i_int),
    .doorbell_clk_o(doorbell_clk_o_int)
  );

  PVDD2CDGM_V IOPAD_bottom_VDDPST_0 (.RTE(rte));

  PVDD2CDGM_V IOPAD_bottom_VDDPST_1 (.RTE(rte));

  PVDD2CDGM_V IOPAD_bottom_VDDPST_2 (.RTE(rte));

  PVDD2CDGM_V IOPAD_bottom_VDDPST_3 (.RTE(rte));

  PVDD2CDGM_V IOPAD_bottom_VDDPST_4 (.RTE(rte));

  PVDD2CDGM_V IOPAD_bottom_VDDPST_5 (.RTE(rte));

  PVDD1CDGM_V IOPAD_bottom_VDD_0 (.RTE(rte));
  PVDD1CDGM_V IOPAD_bottom_VDD_1 (.RTE(rte));
  PVDD2CDGM_H IOPAD_left_VDDPST_0 (.RTE(rte));

  PVDD2CDGM_H IOPAD_left_VDDPST_1 (.RTE(rte));

  PVDD2CDGM_H IOPAD_left_VDDPST_2 (.RTE(rte));

  PVDD2CDGM_H IOPAD_left_VDDPST_3 (.RTE(rte));

  PVDD2CDGM_H IOPAD_left_VDDPST_4 (.RTE(rte));

  PVDD2CDGM_H IOPAD_left_VDDPST_5 (.RTE(rte));

  PVDD1CDGM_H IOPAD_left_VDD_0 (.RTE(rte));
  PVDD1CDGM_H IOPAD_left_VDD_1 (.RTE(rte));
  PVDD2CDGM_H IOPAD_right_VDDPST_0 (.RTE(rte));

  PVDD2CDGM_H IOPAD_right_VDDPST_1 (.RTE(rte));

  PVDD2CDGM_H IOPAD_right_VDDPST_2 (.RTE(rte));

  PVDD2CDGM_H IOPAD_right_VDDPST_3 (.RTE(rte));

  PVDD2CDGM_H IOPAD_right_VDDPST_4 (.RTE(rte));

  PVDD2CDGM_H IOPAD_right_VDDPST_5 (.RTE(rte));

  PVDD1CDGM_H IOPAD_right_VDD_0 (.RTE(rte));
  PVDD1CDGM_H IOPAD_right_VDD_1 (.RTE(rte));


  wire rte_0;
  wire rte_3;

  PDB2ANA_V ANAIOPAD_ext_clk_async_p (
    .RTE(rte_0)
  );

    
  PDB2ANA_V ANAIOPAD_ext_clk_async_n (
    .RTE(rte_0)
  );

    
  PRCUT_V IOPAD_top_cut_1(); 
  PDB3AC_V ANAIOPAD_ext_clkn (
  );

    
  PDB3AC_V ANAIOPAD_ext_clkp (
  );

    
  PVDD3ACM_V ANAIOPAD_CVDD (
  );

    
  PVDD3ACM_V ANAIOPAD_CVSS (
  );

    
  PRCUT_V IOPAD_top_cut_2(); 
  PVDD3ACM_V ANAIOPAD_AVDD (
  );

    
  PVDD3ACM_V ANAIOPAD_AVSS (
  );

    
  PDB3AC_V ANAIOPAD_ext_Vcm (
  );

    
  PDB3AC_V ANAIOPAD_ext_Vcal (
  );

    
  PRCUT_V IOPAD_top_cut_3(); 
  PDB2ANA_V ANAIOPAD_ext_clk_test0_n (
    .RTE(rte_3)
  );

    
  PDB2ANA_V ANAIOPAD_ext_clk_test0_p (
    .RTE(rte_3)
  );

    
  PDB2ANA_V ANAIOPAD_ext_clk_test1_p (
    .RTE(rte_3)
  );

    
  PDB2ANA_V ANAIOPAD_ext_clk_test1_n (
    .RTE(rte_3)
  );

    
   wire jtag_intf_i_phy_tck;
  PDDWUWSWCDG_V IOPAD_jtag_intf_i_phy_tck (
    .RTE(rte_3),
    .PAD(pad_jtag_intf_i_phy_tck),
    .C(jtag_intf_i_phy_tck),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    
   wire jtag_intf_i_phy_tdi;
  PDDWUWSWCDG_V IOPAD_jtag_intf_i_phy_tdi (
    .RTE(rte_3),
    .PAD(pad_jtag_intf_i_phy_tdi),
    .C(jtag_intf_i_phy_tdi),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    
   wire jtag_intf_i_phy_tdo;
  PDDWUWSWCDG_V IOPAD_jtag_intf_i_phy_tdo (
    .RTE(rte_3),
    .PAD(pad_jtag_intf_i_phy_tdo),
    .I(jtag_intf_i_phy_tdo),
    .IE(1'b0),
    .OEN(1'b0),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    
   wire jtag_intf_i_phy_tms;
  PDDWUWSWCDG_V IOPAD_jtag_intf_i_phy_tms (
    .RTE(rte_3),
    .PAD(pad_jtag_intf_i_phy_tms),
    .C(jtag_intf_i_phy_tms),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    
   wire jtag_intf_i_phy_trst_n;
  PDDWUWSWCDG_V IOPAD_jtag_intf_i_phy_trst_n (
    .RTE(rte_3),
    .PAD(pad_jtag_intf_i_phy_trst_n),
    .C(jtag_intf_i_phy_trst_n),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    
   wire ext_rstb;
  PDDWUWSWCDG_V IOPAD_ext_rstb (
    .RTE(rte_3),
    .PAD(pad_ext_rstb),
    .C(ext_rstb),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    
   wire ext_dump_start;
  PDDWUWSWCDG_V IOPAD_ext_dump_start (
    .RTE(rte_3),
    .PAD(pad_ext_dump_start),
    .C(ext_dump_start),
    .I(1'b0),
    .IE(1'b1),
    .OEN(1'b1),
    .DS0(1'b0),
    .DS1(1'b0),
    .DS2(1'b0),
    .PE(1'b0),
    .PS(1'b0),
    .ST(1'b0)
  );

    

  assign rte = rte_0;
  PVDD1CDGM_V IOPAD_top_VDD_dom3 (.RTE(rte));
  PVDD2POCM_V IOPAD_top_VDDPST_dom3(.RTE(rte_3));
  PCBRTE_V IOPAD_top_rte_dom3 (.IRTE(1'b0), .RTE(rte_3));
  butterphy_top iphy (
    .jtag_intf_i_phy_tck(jtag_intf_i_phy_tck),
    .jtag_intf_i_phy_tdi(jtag_intf_i_phy_tdi),
    .jtag_intf_i_phy_tdo(jtag_intf_i_phy_tdo),
    .jtag_intf_i_phy_tms(jtag_intf_i_phy_tms),
    .jtag_intf_i_phy_trst_n(jtag_intf_i_phy_trst_n),
    .ext_rstb(ext_rstb),
    .ext_dump_start(ext_dump_start)
  );


endmodule







