name: testbench

inputs:
  - run.vcd
  - tile_Tile_PE.list

outputs:
  - tile_tbs

commands:
  - ./run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  PWR_AWARE: True
