env:
  CONTAINER: deleteme_garnet_ci${BUILDKITE_BUILD_NUMBER}
  IMAGE: stanfordaha/garnet:latest

steps:

- label: "Get latest docker"
  agents:
    docker: "true"
  commands:
  - docker pull $IMAGE

- wait

# Lint step: check all python files for syntax consistency.
- label: "Lint"

  # For now at least; set soft_fail so failing lint does not fail pipeline
  soft_fail: true

  agents:
    docker: "true"

  commands:

  # Fire up the container
  - docker run -id --name $CONTAINER --rm $IMAGE bash

  # Replace default garnet with dev branch
  - docker exec $CONTAINER /bin/bash -c "rm -rf /aha/garnet"
  - docker cp . $CONTAINER:/aha/garnet
  - docker exec $CONTAINER /bin/bash -c "
      git config --global --add safe.directory /aha/garnet"
  - docker exec $CONTAINER /bin/bash -c "cd /aha/garnet; git branch"

  # Run the lint
  - docker exec $CONTAINER /bin/bash -c "
      source /aha/bin/activate; cd /aha/garnet; ./bin/lint.sh"

  # Clean up
  - docker kill $CONTAINER || true

- wait: { continue_on_failure: true }


- label: ":wrench: Aha regressions"
  agents:
    docker: "true"
  commands:

  # In case prior step failed to clean up correctly
  - docker ps
  - docker kill $CONTAINER || true
  # Sometimes it takes a second to die...
  - sleep 10
  - docker ps

  - docker run -id --name $CONTAINER --rm -v /cad:/cad $IMAGE bash
  - docker exec $CONTAINER /bin/bash -c "rm -rf /aha/garnet"
  - docker cp . $CONTAINER:/aha/garnet

  # For quick test of verilator-compatible code, remove "echo if TEST" below
  - docker exec $CONTAINER /bin/bash -c "
      source /aha/bin/activate;
      source /cad/modules/tcl/init/sh;
      module load base incisive xcelium/19.03.003 vcs/Q-2020.03-SP2;
      ls -l garnet/tests/test_app/dev/verilator-test.regress.py aha/util/regress.py;
      echo if TEST cp garnet/tests/test_app/dev/verilator-test.regress.py aha/util/regress.py;
      aha regress full;
    "

# ALWAYS clean up regardless of test success or failure
- wait: { continue_on_failure: true }

# 1. Delete our own docker container, which we are done with.
# 2. Look for old/stale containers and delete them as well.
# 3. Delete any and all unused docker images.

- label: "Delete container"
  agents:
    docker: "true"
  commands:
  - set -x; docker kill $CONTAINER || true
  - set -x; .buildkite/bin/docker-clean.sh || true
  - set -x; yes | docker image prune -a --filter=label='description=garnet' || true
