env:
  CONTAINER: deleteme_garnet_ci${BUILDKITE_BUILD_NUMBER}
  IMAGE: stanfordaha/garnet:latest

steps:

- label: "Get latest docker"
  agents:
    docker: "true"
  commands:
  - docker pull $IMAGE

- wait

# For now at least; set soft_fail so failing lint does not fail pipeline
- label: "Lint"
  soft_fail: true
  agents:
    docker: "true"
  commands:

  # Fire up the container
  - docker run -id --name $CONTAINER --rm $IMAGE bash

  # Replace default garnet with dev branch
  - docker exec $CONTAINER /bin/bash -c "rm -rf /aha/garnet"
  - docker cp . $CONTAINER:/aha/garnet
  - docker exec $CONTAINER /bin/bash -c "
      git config --global --add safe.directory /aha/garnet"

  - docker exec $CONTAINER /bin/bash -c "cd /aha/garnet; git branch"
  - docker exec $CONTAINER /bin/bash -c "cat -n /aha/garnet/bin/lint.sh"


  # Run the lint
  - docker exec $CONTAINER /bin/bash -c "
      source /aha/bin/activate;
      cd /aha/garnet; ./bin/lint.sh
    "
- wait: { continue_on_failure: true }


# - label: ":wrench: Aha regressions"
#   agents:
#     docker: "true"
#   commands:
#   - docker run -id --name $CONTAINER --rm -v /cad:/cad $IMAGE bash
#   - docker exec $CONTAINER /bin/bash -c "rm -rf /aha/garnet"
#   - docker cp . $CONTAINER:/aha/garnet
#   - docker exec $CONTAINER /bin/bash -c "
#       source /aha/bin/activate;
#       source /cad/modules/tcl/init/sh;
#       module load base incisive xcelium/19.03.003 vcs/Q-2020.03-SP2;
#       pwd; aha regress pr;
#     "
# 
# # ALWAYS clean up regardless of test success or failure
# - wait: { continue_on_failure: true }
# 
# - label: "Delete container"
#   agents:
#     docker: "true"
#   commands:
#   - docker kill $CONTAINER || true
#   - docker container prune --force --filter "until=24h" --filter=label='description=garnet' || true
#   - docker image prune -a  --force --filter "until=24h" --filter=label='description=garnet' || true
