steps:
- label: ":wrench: Build  and Test Garnet GLB + Fabric"
  commands:
  - source /aha/bin/activate
  - source /cad/modules/tcl/init/sh
  - module load base xcelium/19.03.003 vcs/Q-2020.03-SP2
  - echo "--- Pruning Docker Images"
  - yes | docker image prune -a --filter "until=24h" --filter=label='description=garnet' || true
    # make /bin/sh symlink to bash instead of dash:
  - echo "dash dash/sh boolean false" | debconf-set-selections
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash
  - apt update
  - apt install time
    # use the mounted garnet
  - rm -rf /aha/garnet
  - cp -r /workdir /aha/garnet
  - echo "--- Install requirements"
  - pip install -r /aha/garnet/requirements.txt
  - echo "--- Generating Garnet"
  - aha garnet -v --width 8 --height 4 --use_sim_sram
  - echo "--- Generating Apps"
  - aha halide tests/conv_1_2
  - export IO_DELAY=1
  - aha pipeline tests/conv_1_2 --width 4 --height 4 --no-pd
  - aha halide tests/conv_2_1
  - aha pipeline tests/conv_2_1 --width 4 --height 4 --no-pd
  - echo "--- Testing Single App"
  - aha glb tests/conv_1_2
  - aha glb tests/conv_2_1
  - echo "--- Testing Two Apps"
  - aha glb tests/conv_1_2 tests/conv_2_1
  plugins:
    - docker#v3.2.0:
        image: stanfordaha/garnet
        volumes:
          - "/cad/:/cad"
        shell: ["/bin/bash", "-e", "-c"]
  agents:
    docker: true
