steps:


- label: 'tile-array'
  commands:
  - FAIL=true
  - echo error foo > mflowgen-run.log
  - echo post-error info
  - 'echo a b c'\
'd e '



#   - if [ "$$FAIL" ]; then echo foo; fi

#   - if [ "$$FAIL" ]; then \
#         echo '+++ FAIL'; \
#         echo 'Looks like we failed, here are some errors maybe:'; \
#         echo grep -i error mflowgen-run.log; \
#         grep -i error mflowgen-run.log; \
#         exit 13; \
#     fi
# 



#   - gold=/sim/buildkite-agent/gold; test=`pwd`/mflowgen/test/test_module.sh
#   - $$test --debug full_chip tile_array --steps none
#   - wdir=mflowgen/test/full_chip/14-tile_array
#   - echo pwd=`pwd`
#   - echo gold=$$gold
#   - cp -rp $$gold/full_chip/*tile_array/0-Tile_MemCore $$wdir
#   - cp -rp $$gold/full_chip/*tile_array/1-Tile_PE $$wdir
#   - cd $$wdir; make -n rtl | grep 'mkdir.*output' | sed 's/.output.*//'
#   - cd $$wdir; make rtl |& tee make-rtl.log | awk -f $test/rtl-filter1.awk || set FAIL
#   - cd $$wdir; make synopsys-dc-synthesis |& tee make-syn.log | awk -f $test/post-rtl-filter1.awk || set FAIL
#   - cd $$wdir; make synopsys-dc-synthesis |& tee make-syn.log | awk -f $test/post-rtl-filter1.awk || set FAIL





# ###########################################################
# 
# - label: 'tile-array'
#   command: mflowgen/test/test_module.sh full_chip tile_array --debug \
#            --steps rtl,syn,init
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true







# Temporarily disabled while we try and get tile-array working
###########################################################
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh full_chip tile_array Tile_PE --steps synopsys-dc-synthesis --debug
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
# - label: 'Tile_MemCore'
#   command: mflowgen/test/test_module.sh full_chip tile_array Tile_MemCore --steps synopsys-dc-synthesis --debug
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
###########################################################






###########################################################
# Non-hierarchical version
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh --verbose Tile_MemCore --steps synthesis
#   agents: { jobsize: "hours" }

###########################################################
# FAILS after 5 hours as of 07/11/2020, see build 1719
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh --verbose Tile_PE
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true

###########################################################
# SUCCEEDS after 3h 17m as of 7/11/2020, see build 1719
# - label: 'Tile_MemCore'
#   command: mflowgen/test/test_module.sh Tile_MemCore
#   agents: { jobsize: "hours" }
# 
# 
# - wait: ~
#   continue_on_failure: true

###########################################################
# 
# - label: 'icovl'
#   command: mflowgen/test/test_module.sh icovl
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
# 
# - label: 'pad_frame'
#   command: mflowgen/test/test_module.sh pad_frame
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
# 
# - label: 'glb_tile'
#   command: mflowgen/test/test_module.sh glb_tile
#   agents: { jobsize: "hours" }
# 
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
