# (For per-build cache use cache.$$BUILDKITE_BUILD_NUMBER instead)
env:
  CACHEDIR: /sim/buildkite-agent/builds/cache


steps:

# # To disable pipeline, include this as first step
# # let's re-able for a bit and see what happens!
# - wait ###########################################################
# - label: 'Top-level flow temporarily DISABLED while debugging LVS and DRCa'
#   command: exit 13
#   # Note exit doesn't take effect until we hit this "wait" barrier
# - wait ###########################################################

# floorplan place cts fillers route eco
# jobsize:hours leaves an agent free for kathleen

# Start the two 7-hour jobs FIRST

# Expect floorplan and optdesign to take 7-8 hours each

- label: 'PNR1(plan)'
  command: .buildkite/TOP.sh -q floorplan
  agents: { jobsize: "hours" }

- label: 'PNR6(opt)'
  command: .buildkite/TOP.sh -q opt
  agents: { jobsize: "hours" }

# The rest should require about 2-3 hours each

- label: 'PNR2(place)'
  command: .buildkite/TOP.sh -q place
  agents: { jobsize: "hours" }

- label: 'PNR3(cts)'
  command: .buildkite/TOP.sh -q cts
  agents: { jobsize: "hours" }

- label: 'PNR4(fill)'
  command: .buildkite/TOP.sh -q fillers
  agents: { jobsize: "hours" }

- label: 'PNR5(route)'
  command: .buildkite/TOP.sh -q route
  agents: { jobsize: "hours" }

- label: 'PNR7(eco)'
  command: .buildkite/TOP.sh -q eco
  agents: { jobsize: "hours" }



# - label: 'DISABLED!'
#   command: exit 13
#   # Note exit doesn't take effect until next "wait" barrier
# - wait ###################################################################
# 
# - label: 'Generator'
#   command: .buildkite/GEN.sh -v
# 
# - wait ###################################################################
# 
# - label: 'Synthesis: PE tile'
#   command: .buildkite/SYN.sh -q PE
# 
# - label: 'Synthesis: Memory tile'
#   command: .buildkite/SYN.sh -q MemCore
# 
# - wait ###################################################################
# 
# - label: 'PNR: PE tile'
#   command: .buildkite/PNR.sh -q PE
# 
# - label: 'PNR: Memory tile'
#   command: .buildkite/PNR.sh -q MemCore
# 
# # Okay I guess this is broken now
# # - wait ###################################################################
# # 
# # - label: 'PNR: Top Level'
# #   commands:
# #   - .buildkite/TOP.sh -q
# 
# 
# 
# # - label: ":rocket: NO SPACE: Buildkite OFF until space issues resolved"
# #   commands:
# #   - echo "Temporarily suspending buildkite activies until space issue resolved"
# #   - df -h .
# #   - exit 13

