# (For per-build cache use cache.$$BUILDKITE_BUILD_NUMBER instead)
env:
  CACHEDIR: /sim/buildkite-agent/builds/cache


steps:

# let's re-able for a bit and see what happens!
# - label: 'DISABLED!'
#   command: exit 13
#   # Note exit doesn't take effect until we hit this "wait" barrier
# - wait ###########################################################



- label: 'Generator'
  command: .buildkite/GEN.sh -v

- wait #############################################################



- label: 'Synthesis: PE tile'
  command: .buildkite/SYN.sh -q PE

- label: 'Synthesis: Memory tile'
  command: .buildkite/SYN.sh -q MemCore

- wait #############################################################



- label: 'PNR: PE tile'
  command: .buildkite/PNR.sh -q PE

- label: 'PNR: Memory tile'
  command: .buildkite/PNR.sh -q MemCore
