# (For per-build cache use cache.$$BUILDKITE_BUILD_NUMBER instead)
env:
  CACHEDIR: /sim/buildkite-agent/builds/cache


steps:
# floorplan place cts fillers route eco

- label: 'PNR1(plan)'
  command: .buildkite/TOP.sh -q floorplan

- label: 'PNR2(place)'
  command: .buildkite/TOP.sh -q place

- label: 'PNR3(cts)'
  command: .buildkite/TOP.sh -q cts

- label: 'PNR4(fill)'
  command: .buildkite/TOP.sh -q fillers

- label: 'PNR5(route)'
  command: .buildkite/TOP.sh -q route

- label: 'PNR6(eco)'
  command: .buildkite/TOP.sh -q eco



# - label: 'DISABLED!'
#   command: exit 13
#   # Note exit doesn't take effect until next "wait" barrier
# - wait ###################################################################
# 
# - label: 'Generator'
#   command: .buildkite/GEN.sh -v
# 
# - wait ###################################################################
# 
# - label: 'Synthesis: PE tile'
#   command: .buildkite/SYN.sh -q PE
# 
# - label: 'Synthesis: Memory tile'
#   command: .buildkite/SYN.sh -q MemCore
# 
# - wait ###################################################################
# 
# - label: 'PNR: PE tile'
#   command: .buildkite/PNR.sh -q PE
# 
# - label: 'PNR: Memory tile'
#   command: .buildkite/PNR.sh -q MemCore
# 
# # Okay I guess this is broken now
# # - wait ###################################################################
# # 
# # - label: 'PNR: Top Level'
# #   commands:
# #   - .buildkite/TOP.sh -q
# 
# 
# 
# # - label: ":rocket: NO SPACE: Buildkite OFF until space issues resolved"
# #   commands:
# #   - echo "Temporarily suspending buildkite activies until space issue resolved"
# #   - df -h .
# #   - exit 13

