steps:

- label: 'tile-array'
  agents: { jobsize: "hours" }
  commands:
  - test="mflowgen/test/test_module.sh --debug"
  - cached=MemCore,PE,constraints,rtl,tsmc16,synthesis
  - steps=init
  - $$test full_chip tile_array --use_cached $$cached --steps $$steps
  # - $$test --debug full_chip tile_array --steps copy,rtl,syn,init

- wait: ~
  continue_on_failure: true





- label: 'Tile_MemCore'
  agents: { jobsize: "hours" }
  commands:
  - test=mflowgen/test/test_module.sh
  - $$test full_chip tile_array Tile_MemCore --steps synthesis --debug

- wait: ~
  continue_on_failure: true



- label: 'Tile_PE'
  agents: { jobsize: "hours" }
  commands:
  - test=mflowgen/test/test_module.sh
  - $$test full_chip tile_array Tile_PE --steps synthesis --debug

- wait: ~
  continue_on_failure: true











###########################################################
# Non-hierarchical version
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh --verbose Tile_MemCore --steps synthesis
#   agents: { jobsize: "hours" }

###########################################################
# FAILS after 5 hours as of 07/11/2020, see build 1719
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh --verbose Tile_PE
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true

###########################################################
# SUCCEEDS after 3h 17m as of 7/11/2020, see build 1719
# - label: 'Tile_MemCore'
#   command: mflowgen/test/test_module.sh Tile_MemCore
#   agents: { jobsize: "hours" }
# 
# 
# - wait: ~
#   continue_on_failure: true

###########################################################
# 
# - label: 'icovl'
#   command: mflowgen/test/test_module.sh icovl
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
# 
# - label: 'pad_frame'
#   command: mflowgen/test/test_module.sh pad_frame
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
# 
# - label: 'glb_tile'
#   command: mflowgen/test/test_module.sh glb_tile
#   agents: { jobsize: "hours" }
# 
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
