agents: { jobsize: "minutes", tech: "gf" }

##############################################################################
# Use this to test a specific branch/commit:
# Add to env:
#   NOV11: ee214ef77b827f969e4b5f056f5d866cf391be7a
# Add to commands:
# - pwd; git branch; git checkout $$NOV11

##############################################################################
# Note: "echo exit 13" prevents hang at genus/innovus prompt
env:
  TEST: 'echo exit 13 | mflowgen/test/test_module.sh'

steps:

##############################################################################
# INDIVIDUAL TILE RUNS
# Builds in dir e.g. mflowgen/full_chip/19-tile_array/16-Tile_MemCore

- label: '250MHz PE synth 12m'
  commands:
  - $TEST --need_space 30G full_chip tile_array Tile_PE --steps synthesis --debug
  - .buildkite/pipelines/check_pe_area.sh
  - mflowgen/bin/buildcheck.sh full_chip/*tile_array/*Tile_PE --show-all-errors
- wait: { continue_on_failure: true } # One step at a time + continue on failure

- label: 'MemCore synth 17m'
  commands:
  - $TEST --need_space 30G full_chip tile_array Tile_MemCore --steps synthesis --debug
  - mflowgen/bin/buildcheck.sh full_chip/*tile_array/*Tile_MemCore --show-all-errors
- wait: { continue_on_failure: true } # One step at a time + continue on failure
