# New pipeline does each mflowgen step as a separate buildkite step

steps:

- label: 'rtl'
  agents: { queue: "papers" }
  commands:
  - 'mflowgen/test/test_module.sh full_chip
       --debug
       --build_dir /build/gold.$${BUILDKITE_BUILD_NUMBER}
       --steps rtl'
- wait: ~

- label: 'tile_array'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make tile_array |& tee make-tile_array.log'
- wait: ~

- label: 'glb_top'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make glb_top |& tee make-glb_top.log'
- wait: ~

- label: 'glc'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make global_controller |& tee make-glc.log'
- wait: ~

- label: 'dragon'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make dragonphy |& tee make-dragon.log'
- wait: ~

- label: 'soc-rtl'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make soc-rtl |& tee make-soc-rtl.log'
- wait: ~

- label: 'syn'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make synopsys-dc-synthesis |& tee make-syn.log'
- wait: ~

- label: 'place'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make cadence-innovus-place |& tee make-place.log'
- wait: ~

- label: 'route'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make cadence-innovus-route |& tee make-route.log'
- wait: ~

- label: 'hold'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make cadence-innovus-postroute_hold |& tee make-hold.log'
- wait: ~

- label: 'lvs'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make mentor-calibre-lvs |& tee make-lvs.log'
- wait: ~

- label: 'drc'
  agents: { queue: "papers" }
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh
       --dir /build/gold.$${BUILDKITE_BUILD_NUMBER}/full_chip;
     make mentor-calibre-drc |& tee make-drc.log'
- wait: ~
