steps:

##############################################################################
# test new mflowgen links
# 
- label: 'mflowgen link test'
  agents: { jobsize: "hours" }
  commands:
  - build_dir=/sim/tmp/deleteme.buildkite-$$BUILDKITE_BUILD_NUMBER.array-init
  - 'mflowgen/test/test_module.sh --debug full_chip tile_array
       --build_dir $$build_dir
       --steps tsmc16'
  - echo /bin/rm -rf $$build_dir
  - /bin/rm -rf $$build_dir
