steps:


- label: 'tile-array'
  commands:
  - gold=/sim/buildkite-agent/gold; test=`pwd`/mflowgen/test/test_module.sh
  - $$test --debug full_chip tile_array --steps none
  - pwd
  - echo gold=$$gold
  - cp -rp $$gold/full_chip/*tile_array/0-Tile_MemCore .
  - cp -rp $$gold/full_chip/*tile_array/1-Tile_PE .





# ###########################################################
# 
# - label: 'tile-array'
#   command: mflowgen/test/test_module.sh full_chip tile_array --debug \
#            --steps rtl,syn,init
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true







# Temporarily disabled while we try and get tile-array working
###########################################################
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh full_chip tile_array Tile_PE --steps synopsys-dc-synthesis --debug
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
# - label: 'Tile_MemCore'
#   command: mflowgen/test/test_module.sh full_chip tile_array Tile_MemCore --steps synopsys-dc-synthesis --debug
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
###########################################################






###########################################################
# Non-hierarchical version
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh --verbose Tile_MemCore --steps synthesis
#   agents: { jobsize: "hours" }

###########################################################
# FAILS after 5 hours as of 07/11/2020, see build 1719
# - label: 'Tile_PE'
#   command: mflowgen/test/test_module.sh --verbose Tile_PE
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true

###########################################################
# SUCCEEDS after 3h 17m as of 7/11/2020, see build 1719
# - label: 'Tile_MemCore'
#   command: mflowgen/test/test_module.sh Tile_MemCore
#   agents: { jobsize: "hours" }
# 
# 
# - wait: ~
#   continue_on_failure: true

###########################################################
# 
# - label: 'icovl'
#   command: mflowgen/test/test_module.sh icovl
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
# 
# - label: 'pad_frame'
#   command: mflowgen/test/test_module.sh pad_frame
#   agents: { jobsize: "hours" }
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
# 
# - label: 'glb_tile'
#   command: mflowgen/test/test_module.sh glb_tile
#   agents: { jobsize: "hours" }
# 
# 
# - wait: ~
#   continue_on_failure: true
# 
###########################################################
