# (For per-build cache use cache.$$BUILDKITE_BUILD_NUMBER instead)
env:
  CACHEDIR: /sim/buildkite-agent/builds/cache


steps:
- label:   'GEN'
  command: .buildkite/GEN.sh -v

- wait ###################################################################

- label: 'SYN.Mem'
  commands:
  - .buildkite/SYN.sh MemCore

- label: 'SYN.PE'
  commands:
  - .buildkite/SYN.sh PE

- wait ###################################################################

- label: 'PNR.Mem'
  commands:
  - .buildkite/PNR.sh MemCore

- label: 'PNR.PE'
  commands:
  - .buildkite/PNR.sh PE
