env:
    ERRFILE: /tmp/bklog.$BUILDKITE_BUILD_NUMBER

# [sr 2002] Added waits between each step.
# Each one seems to try and max out resources.
# Why make them run in parallel??

steps:

- label: 'Tile_PE'
  command: mflowgen/test/test_module.sh --verbose Tile_PE \
      || echo $$BUILDKITE_LABEL FAILED >> $$ERRFILE'
  agents: { jobsize: "hours" }

- wait ###########################################################

- label: 'CHECK'
  command: grep FAIL $ERRFILE && exit 13

- wait ###########################################################

- label: 'icovl'
  command: mflowgen/test/test_module.sh icovl
  agents: { jobsize: "hours" }

- wait ###########################################################

- label: 'pad_frame'
  command: mflowgen/test/test_module.sh pad_frame
  agents: { jobsize: "hours" }

- wait ###########################################################

- label: 'Tile_MemCore'
  command: mflowgen/test/test_module.sh Tile_MemCore
  agents: { jobsize: "hours" }

# Not needed (yet)
# - wait ###########################################################
#
# - label: 'Summary'
#   command: echo final summary goes here
