#=========================================================================
# SOC RTL
#=========================================================================
# Author : Alex Carsello
# Date   : March 23, 2020
#

name: soc-rtl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - rtl
  - rtl-scripts
  - io_file

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

parameters:
  include_core: 1
