#=========================================================================
# create-final-database
#=========================================================================
# Author : Po-Han Chen
# Date   : Oct 30, 2023
#

name: create-final-database

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.oas

outputs:
  - final.oas
  - final_v.oas

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo | calibredrv ./scripts/create-poly-hori-database.tcl
  - echo | calibredrv ./scripts/create-poly-vert-database.tcl
  - cd outputs
  - ln -s {intel_database_name}_v.oas final_v.oas
  - ln -s {intel_database_name}.oas final.oas
  - tar -czvf {intel_database_name}.tar.gz {intel_database_name}.oas
  - cd ..

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: design
  intel_database_name: intel_database_name

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'calibredrv' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design.oas' )

postconditions:
  - assert File( 'outputs/final.oas' )
  - assert File( 'outputs/final_v.oas' )
