#=========================================================================
# Mentor Graphics Calibre LVS
#=========================================================================

name: intel16-mentor-calibre-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
# layout   : design-merged.gds
# schematic: design.lvs.v
inputs:
  - adk
  - design-merged.gds
  - design.lvs.v

outputs:
  - LVS.summary

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - python3 v2sp.py
  - source inputs/adk/run-calibre-lvs.sh

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m inputs/design-merged.gds \
               -rve -lvs svdb

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:
  - assert Tool( 'calibre' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design-merged.gds' )
  - assert File( 'inputs/design.lvs.v' )
