name: dragonphy

outputs:
  - dragonphy_top_tt.lib
  - dragonphy_top_tt.db
  - dragonphy_top.lef
  - dragonphy_top.gds
  - dragonphy_top.spi
  - dragonphy_RDL.gds
  - dragonphy_RDL.lef

commands:
  - bash fixup.sh
