# =============================================================================
# Run Test
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: run_test

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  TEST_NAME: undefined
