#=========================================================================
# Constraints
#=========================================================================
# Author : Alex Carsello
# Date   : Nov 1, 2019
#

name: io_file

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - io_file

outputs:
  - io_file


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
  - cp -L inputs/io_file outputs
