#=========================================================================
# Constraints
#=========================================================================
# Author : Alex Carsello
# Date   : Nov 1, 2019
#

name: io_file

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - io_file
  - io_pad_placement.tcl

outputs:
  - io_file
  - io_pad_placement.tcl


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
  - cp -L inputs/io_file outputs
  - cp -L inputs/io_pad_placement.tcl outputs
