#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - io_file

outputs:
  - add-endcaps-welltaps.tcl
  - floorplan.tcl
  - pin-assignments.tcl

