#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - io_file

# FIXME  I'm sure this is not how this is supposed to work...[sr02.2020]
commands:
  - cp inputs/io_file outputs/io_file

outputs:
  - add-endcaps-welltaps.tcl
  - floorplan.tcl
  - pin-assignments.tcl
  - io_file

