name: rtl

commands:
  - git clone http://gitlab.r7arm-aha.localdomain/nyengele/aha-arm-soc-june-2019.git
  - bash gen_rtl.sh

outputs:
  - design.v

parameters:
  array_width: 32
  array_height: 16
  interconnect_only: false
