# COPIED FROM:
#=========================================================================
# Mentor Calibre GDS Merge
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

# name: mentor-calibre-gdsmerge
name: init-gdsmerge

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.gds.gz
  - adk

outputs:
  - design_merged.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

# Okay well this is terrible.
# Prev step "cadence-innovus-init" does not copy gds result to
# outputs dir; so must change below switch from "-indir inputs"
# to "-indir ../*cadence-innovus-init/results"

commands:
  # For some reason, Calibre requires this directory to exist
  - mkdir -p $HOME/.calibrewb_workspace/tmp
  # Use calibredrv to merge gds files
  - ins=""; for f in inputs/adk/*.gds*; do ins="$ins -in $f"; done
  - calibredrv -a layout filemerge \
               -indir ../*cadence-innovus-init/results \
               $ins \
               -topcell {design_name} \
               -out design_merged.gds 2>&1 | tee merge.log
  - mkdir -p outputs && cd outputs
  - ln -sf ../design_merged.gds

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m design_merged.gds \
               -l inputs/adk/calibre.layerprops

