name: testbench

commands:
  - python ../../../tests/test_timing/generate_testbench.py outputs --width $array_width --height $array_height
  - mv outputs/Interconnect_tb.sv outputs/testbench.sv

outputs:
  - testbench.sv
