#=========================================================================
# Custom Scripts -- pre-signoff
#=========================================================================

name: custom-pre-signoff

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - pre-signoff.tcl
