//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /sim/ajcars/aha-arm-soc-june-2019/components/cgra/garnet/global_buffer/genesis/memory.svp
//  Source template: memory
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

module memory #(
    parameter DATA_WIDTH=64,
    parameter ADDR_WIDTH=14
)
(
    clk,
    clk_en,
    data_in,
    bit_sel,
    data_out,
    wen,
    addr
);

input wire                  clk;
input wire                  clk_en;
input wire                  wen;
input wire[DATA_WIDTH-1:0]  data_in;
input wire[DATA_WIDTH-1:0]  bit_sel;
input wire[ADDR_WIDTH-1:0]  addr;

output wire[DATA_WIDTH-1:0]      data_out;

sram_gen #(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
)
sram_gen (
    .Q(data_out),
    .CLK(clk),
    .CEB(~clk_en), 
    .WEB(~wen), 
    .BWEB(~bit_sel), 
    .A(addr), 
    .D(data_in)
);


endmodule
