#=========================================================================
# Synopsys DC Synthesis
#=========================================================================
# Author : Christopher Torng, Yanghui Ou
# Date   : June 7, 2019
#

name: synopsys-dc-synthesis

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.v
  - constraints.tcl
  - run.saif

outputs:
  - design.v
  - design.sdc
  - design.namemap

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  design_name: undefined
  flatten_effort: 0
  topographical: True
  nthreads: 16  # multithreading available to the tool

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - export DC_EXIT_AFTER_SETUP=1
  - ln -sf results/*.mapped.ddc debug.ddc
  - design_vision-xg -topographical -x "source dc.tcl; read_ddc debug.ddc"

