#=========================================================================
# Synopsys DC Synthesis
#=========================================================================
# Author : Christopher Torng, Yanghui Ou
# Date   : June 7, 2019
#

name: synopsys-dc-synthesis

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.v
  - cons_scripts
  - constraints.tcl
  - run.saif

outputs:
  - design.v
  - design.sdc
  - design.namemap

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period            : undefined
  design_name             : undefined
  flatten_effort          : undefined
  topographical           : undefined
  nthreads                : undefined
  TLX_FWD_DATA_LO_WIDTH   : undefined
  TLX_REV_DATA_LO_WIDTH   : undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - export DC_EXIT_AFTER_SETUP=1
  - ln -sf results/*.mapped.ddc debug.ddc
  - design_vision-xg -topographical -x "source dc.tcl; read_ddc debug.ddc"
