#=========================================================================
# Custom Scripts -- LVS SVRF Rules
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - rules.svrf
