#=========================================================================
# Constraints
#=========================================================================
# Author : Alex Carsello
# Date   : Nov 1, 2019
#
# This node introduces any DC commands we need to run after the compile
# step.

name: custom-dc-postcompile

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - custom-dc-postcompile.tcl

