#=========================================================================
# Constraints
#=========================================================================
# Author : Alex Carsello
# Date   : Nov 1, 2019
#

name: constraints

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - constraints.tcl
  - constraints

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------
commands:
  - cp scripts/constraints.tcl outputs/
  - cp -r scripts outputs/constraints

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  design_name: undefined
