calibre_pad_frame:
	./drc.sh ~/gds_files/pads_placed.gds GarnetSOC_pad_frame -nofullchip -noantenna

calibre_mem_tile:
	./drc.sh ~/gds_files/Tile_MemCore.gds Tile_MemCore -nofullchip -noantenna

calibre_pe_tile:
	./drc.sh ~/gds_files/Tile_PE.gds Tile_PE -nofullchip -noantenna

