#=========================================================================
# SOC RTL
#=========================================================================
# Author : Alex Carsello
# Date   : March 23, 2020
#

name: soc-rtl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - rtl
  - rtl-scripts

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - git clone git@r7arm-aha:nyengele/aha-arm-soc-june-2019.git 
  - cd aha-arm-soc-june-2019/components/pad_frame
  - Genesis2.pl -parse -generate -top GarnetSOC_pad_frame -input GarnetSOC_pad_frame.svp 
  - cd ../../../
  - ln -s ../aha-arm-soc-june-2019 outputs/rtl

