#=========================================================================
# Seal Ring
#=========================================================================
# Author : Alex Carsello
# Date   : March 26, 2020
#

name: sealring

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - add-sealring.tcl

