#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-power-hierarchical

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - globalnetconnect.tcl
  - power-strategy-dualmesh.tcl

