#=========================================================================
# custom-hack-sdc-unit
#=========================================================================

name: custom-hack-sdc-unit

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - hack_sdc_unit.py
