#=========================================================================
# Fill Density test checker
#=========================================================================
# Author : Alex Carsello
# Date   : Dec. 8, 2023
#

name: checker

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - drc.summary

outputs:
  - result


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - python gen_result.py

#-------------------------------------------------------------------------
# Preconditions and Postconditions
#-------------------------------------------------------------------------

preconditions:
  - assert File( 'inputs/drc.summary' )

postconditions:
  - assert File( 'outputs/result' )
