#=========================================================================
# Synopsys PTPX -- Gate-Level Power Estimation
#=========================================================================
# This step runs gate-level average power analysis with Synopsys PrimeTime
#
#

name: synopsys-ptpx-gl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - design.vcs.pg.v
  - design.pt.sdc
  - design.spef.gz
  - run.saif

outputs:
  - power.hier
  - power.cell

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source run_step.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  strip_path: top/dut
  PWR_AWARE: False
  instances: ["glb_tile_gen_0", "glb_tile_gen_1"]
  parse_modules: ["glb_cfg", "'(glb_switch|glb_proc_router|glb_strm_router)'", "'glb_core_(load|store|pcfg)_dma'", "glb_bank_memory", "sram_cfg_ctrl"]
  chkpt: False # Turn this on to save periodically during ptpx flow
