#=========================================================================
# Synopsys PTPX -- Gate-Level Power Estimation
#=========================================================================
# This step runs gate-level average power analysis with Synopsys PrimeTime
#
#

name: synopsys-ptpx-gl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.vcs.v
  - design.vcs.pg.v
  - design.pt.sdc
  - design.spef.gz
  - run.fsdb

outputs:
  - power.hier
  - power.cell

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source run_step.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  strip_path: top/dut
  PWR_AWARE: False
  instances: ["glb_tile_gen_0", "glb_tile_gen_2", "glb_tile_gen_3", "glb_tile_gen_15"]
  parse_modules: ["glb_cfg", "glb_sram_cfg_switch", "glb_bank_mux", "glb_bank_0", "glb_bank_1", "glb_proc_switch", "glb_strm_ring_switch", "glb_pcfg_ring_switch", "glb_load_dma", "glb_store_dma", "glb_pcfg_dma"]
  chkpt: False # Turn this on to save periodically during ptpx flow
