#=========================================================================
# SOC RTL
#=========================================================================
# Author : Alex Carsello
# Date   : March 23, 2020
#

name: soc-rtl

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - rtl
  - rtl-scripts

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - git clone http://gitlab.r7arm-aha.localdomain/nyengele/aha-arm-soc-june-2019.git
  - ln -s ../aha-arm-soc-june-2019 outputs/rtl

