#=========================================================================
# Custom read_design
#=========================================================================
# Author : Alex Carsello
# Date   : July 20, 2020
#-------------------------------------------------------------------------

name: custom-read-design

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------
outputs:
  - read-design.tcl

