#=========================================================================
# Checker
#=========================================================================

name: checker

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - lvs.report

outputs:
  - result


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - python gen_result.py
