#=========================================================================
# Custom Signoff for full chip
#=========================================================================

name: custom-signoff

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - bump-util.tcl
  - create-physical-pin.tcl
