#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-power-chip

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - globalnetconnect.tcl
  - power-strategy-dualmesh.tcl
  - attach-results-to-outputs.tcl
  - add-endcaps-welltaps.tcl

