#=========================================================================
# Custom Scripts -- Tile Array CTS sink_type overrides
#=========================================================================

name: custom-cts-overrides

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - cts-overrides.tcl
