#=========================================================================
# Custom DC Scripts
#=========================================================================

name: custom-dc-scripts

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - generate-results.tcl
  - reporting.tcl
  - scenarios.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  design_name: undefined
