#=========================================================================
# IR test checker
#=========================================================================
# Author : Alex Carsello
# Date   : Nov 17, 2023
#

name: checker

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - static_rail_analysis_results

outputs:
  - result


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - python gen_result.py

#-------------------------------------------------------------------------
# Preconditions and Postconditions
#-------------------------------------------------------------------------

preconditions:
  - assert File( 'inputs/static_rail_analysis_results' )

postconditions:
  - assert File( 'outputs/result' )
