#=========================================================================
# Parse gate-level power reports
#=========================================================================

name: parse-power

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - power.hier 
  - power.cell

outputs:
  - overall.summary
  - cell.summary

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/power.hier outputs/overall.summary
  - cp inputs/power.cell outputs/cell.summary

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
