#=========================================================================
# Loopbreaking test checker
#=========================================================================
# Author : Alex Carsello
# Date   : March 12, 2024
#

name: checker

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - lib_timing_arcs

outputs:
  - result


#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - python gen_result.py

#-------------------------------------------------------------------------
# Preconditions and Postconditions
#-------------------------------------------------------------------------

preconditions:
  - assert File( 'inputs/lib_timing_arcs' )

postconditions:
  - assert File( 'outputs/result' )
