name: rtl

commands:
  - bash gen_rtl.sh

outputs:
  - design.v

parameters:
  array_width: 4
  array_height: 2
  glb_tile_mem_size: 256
  pipeline_config_interval: 8
  interconnect_only: False
  soc_only: False
  PWR_AWARE: True

  # If true, use docker container for python environment
  use_container: True

  # If true, clone garnet locally and copy into the container
  use_local_garnet: True

  # To try out a new docker image e.g. 'stanfordaha/garnet:cst'
  # - set 'save_verilog_to_tmpdir' to "True", then build (latest) rtl
  # - set 'which_image' to "cst", then build (cst) rtl
  # - should see before-and-after designs in /tmp directory:
  # 
  #   % ls -lt /tmp/design.v.*
  #       1745336 Feb  5 10:47 design.v.cst.deleteme13246
  #       1785464 Feb  5 10:39 design.v.latest.deleteme9962
  #
  # which_image: cst              # If not set, defaults to 'latest'
  # save_verilog_to_tmpdir: True  # If true, copies final verilog to /tmp

postconditions:
  - assert File( 'outputs/design.v' )        # must exist
