name: rtl

commands:
  - bash gen_rtl.sh

outputs:
  - design.v

parameters:
  array_width: 4
  array_height: 2
  interconnect_only: False
  soc_only: False
  PWR_AWARE: True
  use_container: True
  use_local_garnet: True

postconditions:
  - assert File( 'outputs/design.v' )        # must exist
