#=========================================================================
# Mentor Graphics Calibre Smartfill
#=========================================================================

name: intel16-mentor-calibre-fill

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design-merged.oas

outputs:
  - design-merged.oas

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source inputs/adk/run-calibre-fill.sh
  - ln -sf ../design-merged.oas ./outputs/design-merged.oas

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:
  - assert Tool( 'calibre' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design-merged.oas' )
