#=========================================================================
# Custom Scripts -- Custom setup-ccopt.tcl for fullchip
#=========================================================================

name: custom-cts

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - setup-ccopt.tcl
