flow_dir=$(abspath .)
vlsi_dir=$(abspath ..)
base_dir=$(abspath ../..)
setup_dir=$(vlsi_dir)/setup
scripts_dir=$(flow_dir)/scripts
const_dir=$(vlsi_dir)/constraints

default: flow

include $(base_dir)/Makefrag
include $(flow_dir)/Makefrag
