# =============================================================================
# Run Test
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: garnet_rtl

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
outputs:
  - filelists

# -----------------------------------------------------------------------------
# Commands
# -----------------------------------------------------------------------------
commands:
  - bash run.sh


# -----------------------------------------------------------------------------
# Parameters
# -----------------------------------------------------------------------------

parameters:
  interconnect_only: False
  array_width: 4
  array_height: 4
  GARNET_HOME: undefined
