#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
parameters:
  num_glb_tiles: 16
  num_tile_array_cols: 32

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - add-endcaps-welltaps.tcl
  - floorplan.tcl
  - pin-assignments.tcl
  - dont-touch.tcl

