#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------
parameters:
  num_glb_tiles: 16
  array_width: 32

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - add-endcaps-welltaps.tcl
  - floorplan.tcl
  - pin-assignments.tcl
  - dont-touch.tcl
  - add-tracks.tcl
  - create-boundary-blockage.tcl
  - create-rows.tcl
  - create-special-grid.tcl
  - innovus-pnr-config.tcl
  - insert-input-antenna-diodes.tcl
  - enable-gmz-routing.tcl
