#=========================================================================
# Constraints
#=========================================================================
# Author : Alex Carsello
# Date   : Jan 24, 2020
#

name: custom-genlibdb-constraints

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - genlibdb-constraints.tcl

#-------------------------------------------------------------------------
# Tests
#-------------------------------------------------------------------------

tests:
  - description: loopbreaking
    test_graph: comb_path_check
    express_mode: low_effort
    attach_points:
      - GENLIB
