lvs_mem:
	@echo "Running MEM lvs"
	./lvs.sh ../synth/Tile_MemCore/pnr.gds ../synth/Tile_MemCore/pnr.lvs.v Tile_MemCore

lvs_pe:
	@echo "Running PE lvs"
	./lvs.sh ../synth/Tile_PE/pnr.gds ../synth/Tile_PE/pnr.lvs.v Tile_PE
