//   Ordt 190524.01 autogenerated file 
//   Input: /aha/garnet/global_controller/systemRDL/rdl_models/glc.rdl.final
//   Parms: /aha/garnet/global_controller/systemRDL/ordt_params/glc.parms
//   Date: Fri Jan 19 15:54:40 PST 2024
//

//
//---------- module glc_pio
//
module glc_pio
(
  clk,
  reset,
  h2l_global_reset_cnt_w,
  h2l_global_reset_cnt_we,
  h2l_strm_f2g_isr_tile_0_intr,
  h2l_strm_f2g_isr_tile_1_intr,
  h2l_strm_f2g_isr_tile_2_intr,
  h2l_strm_f2g_isr_tile_3_intr,
  h2l_strm_f2g_isr_tile_4_intr,
  h2l_strm_f2g_isr_tile_5_intr,
  h2l_strm_f2g_isr_tile_6_intr,
  h2l_strm_f2g_isr_tile_7_intr,
  h2l_strm_f2g_isr_tile_8_intr,
  h2l_strm_f2g_isr_tile_9_intr,
  h2l_strm_f2g_isr_tile_10_intr,
  h2l_strm_f2g_isr_tile_11_intr,
  h2l_strm_f2g_isr_tile_12_intr,
  h2l_strm_f2g_isr_tile_13_intr,
  h2l_strm_f2g_isr_tile_14_intr,
  h2l_strm_f2g_isr_tile_15_intr,
  h2l_strm_g2f_isr_tile_0_intr,
  h2l_strm_g2f_isr_tile_1_intr,
  h2l_strm_g2f_isr_tile_2_intr,
  h2l_strm_g2f_isr_tile_3_intr,
  h2l_strm_g2f_isr_tile_4_intr,
  h2l_strm_g2f_isr_tile_5_intr,
  h2l_strm_g2f_isr_tile_6_intr,
  h2l_strm_g2f_isr_tile_7_intr,
  h2l_strm_g2f_isr_tile_8_intr,
  h2l_strm_g2f_isr_tile_9_intr,
  h2l_strm_g2f_isr_tile_10_intr,
  h2l_strm_g2f_isr_tile_11_intr,
  h2l_strm_g2f_isr_tile_12_intr,
  h2l_strm_g2f_isr_tile_13_intr,
  h2l_strm_g2f_isr_tile_14_intr,
  h2l_strm_g2f_isr_tile_15_intr,
  h2l_par_cfg_g2f_isr_tile_0_intr,
  h2l_par_cfg_g2f_isr_tile_1_intr,
  h2l_par_cfg_g2f_isr_tile_2_intr,
  h2l_par_cfg_g2f_isr_tile_3_intr,
  h2l_par_cfg_g2f_isr_tile_4_intr,
  h2l_par_cfg_g2f_isr_tile_5_intr,
  h2l_par_cfg_g2f_isr_tile_6_intr,
  h2l_par_cfg_g2f_isr_tile_7_intr,
  h2l_par_cfg_g2f_isr_tile_8_intr,
  h2l_par_cfg_g2f_isr_tile_9_intr,
  h2l_par_cfg_g2f_isr_tile_10_intr,
  h2l_par_cfg_g2f_isr_tile_11_intr,
  h2l_par_cfg_g2f_isr_tile_12_intr,
  h2l_par_cfg_g2f_isr_tile_13_intr,
  h2l_par_cfg_g2f_isr_tile_14_intr,
  h2l_par_cfg_g2f_isr_tile_15_intr,
  h2l_global_isr_strm_f2g_w,
  h2l_global_isr_strm_g2f_w,
  h2l_global_isr_par_cfg_g2f_w,
  h2l_cgra_config_write_cnt_w,
  h2l_cgra_config_write_cnt_we,
  h2l_cgra_config_read_cnt_w,
  h2l_cgra_config_read_cnt_we,
  h2l_cgra_config_rd_data_data_w,
  h2l_cgra_config_rd_data_data_we,
  h2d_pio_dec_address,
  h2d_pio_dec_write_data,
  h2d_pio_dec_write,
  h2d_pio_dec_read,

  l2h_global_reset_cnt_r,
  l2h_cgra_stall_stall_r,
  l2h_glb_clk_en_master_clk_en_r,
  l2h_glb_clk_en_bank_master_clk_en_r,
  l2h_glb_pcfg_broadcast_stall_stall_r,
  l2h_stream_start_pulse_g2f_glb_tile_0_r,
  l2h_stream_start_pulse_g2f_glb_tile_1_r,
  l2h_stream_start_pulse_g2f_glb_tile_2_r,
  l2h_stream_start_pulse_g2f_glb_tile_3_r,
  l2h_stream_start_pulse_g2f_glb_tile_4_r,
  l2h_stream_start_pulse_g2f_glb_tile_5_r,
  l2h_stream_start_pulse_g2f_glb_tile_6_r,
  l2h_stream_start_pulse_g2f_glb_tile_7_r,
  l2h_stream_start_pulse_g2f_glb_tile_8_r,
  l2h_stream_start_pulse_g2f_glb_tile_9_r,
  l2h_stream_start_pulse_g2f_glb_tile_10_r,
  l2h_stream_start_pulse_g2f_glb_tile_11_r,
  l2h_stream_start_pulse_g2f_glb_tile_12_r,
  l2h_stream_start_pulse_g2f_glb_tile_13_r,
  l2h_stream_start_pulse_g2f_glb_tile_14_r,
  l2h_stream_start_pulse_g2f_glb_tile_15_r,
  l2h_stream_start_pulse_f2g_glb_tile_0_r,
  l2h_stream_start_pulse_f2g_glb_tile_1_r,
  l2h_stream_start_pulse_f2g_glb_tile_2_r,
  l2h_stream_start_pulse_f2g_glb_tile_3_r,
  l2h_stream_start_pulse_f2g_glb_tile_4_r,
  l2h_stream_start_pulse_f2g_glb_tile_5_r,
  l2h_stream_start_pulse_f2g_glb_tile_6_r,
  l2h_stream_start_pulse_f2g_glb_tile_7_r,
  l2h_stream_start_pulse_f2g_glb_tile_8_r,
  l2h_stream_start_pulse_f2g_glb_tile_9_r,
  l2h_stream_start_pulse_f2g_glb_tile_10_r,
  l2h_stream_start_pulse_f2g_glb_tile_11_r,
  l2h_stream_start_pulse_f2g_glb_tile_12_r,
  l2h_stream_start_pulse_f2g_glb_tile_13_r,
  l2h_stream_start_pulse_f2g_glb_tile_14_r,
  l2h_stream_start_pulse_f2g_glb_tile_15_r,
  l2h_pc_start_pulse_glb_tile_0_r,
  l2h_pc_start_pulse_glb_tile_1_r,
  l2h_pc_start_pulse_glb_tile_2_r,
  l2h_pc_start_pulse_glb_tile_3_r,
  l2h_pc_start_pulse_glb_tile_4_r,
  l2h_pc_start_pulse_glb_tile_5_r,
  l2h_pc_start_pulse_glb_tile_6_r,
  l2h_pc_start_pulse_glb_tile_7_r,
  l2h_pc_start_pulse_glb_tile_8_r,
  l2h_pc_start_pulse_glb_tile_9_r,
  l2h_pc_start_pulse_glb_tile_10_r,
  l2h_pc_start_pulse_glb_tile_11_r,
  l2h_pc_start_pulse_glb_tile_12_r,
  l2h_pc_start_pulse_glb_tile_13_r,
  l2h_pc_start_pulse_glb_tile_14_r,
  l2h_pc_start_pulse_glb_tile_15_r,
  l2h_strm_f2g_isr_intr_o,
  l2h_strm_g2f_isr_intr_o,
  l2h_par_cfg_g2f_isr_intr_o,
  l2h_global_isr_intr_o,
  l2h_cgra_config_addr_addr_r,
  l2h_cgra_config_wr_data_data_r,
  l2h_cgra_config_write_cnt_r,
  l2h_cgra_config_write_cnt_ored_o,
  l2h_cgra_config_read_cnt_r,
  l2h_cgra_config_read_cnt_ored_o,
  l2h_cgra_config_rd_data_data_r,
  l2h_glb_flush_crossbar_sel_r,
  d2h_dec_pio_read_data,
  d2h_dec_pio_ack,
  d2h_dec_pio_nack );

  //------- inputs
  input    clk;
  input    reset;
  input     [31:0] h2l_global_reset_cnt_w;
  input    h2l_global_reset_cnt_we;
  input    h2l_strm_f2g_isr_tile_0_intr;
  input    h2l_strm_f2g_isr_tile_1_intr;
  input    h2l_strm_f2g_isr_tile_2_intr;
  input    h2l_strm_f2g_isr_tile_3_intr;
  input    h2l_strm_f2g_isr_tile_4_intr;
  input    h2l_strm_f2g_isr_tile_5_intr;
  input    h2l_strm_f2g_isr_tile_6_intr;
  input    h2l_strm_f2g_isr_tile_7_intr;
  input    h2l_strm_f2g_isr_tile_8_intr;
  input    h2l_strm_f2g_isr_tile_9_intr;
  input    h2l_strm_f2g_isr_tile_10_intr;
  input    h2l_strm_f2g_isr_tile_11_intr;
  input    h2l_strm_f2g_isr_tile_12_intr;
  input    h2l_strm_f2g_isr_tile_13_intr;
  input    h2l_strm_f2g_isr_tile_14_intr;
  input    h2l_strm_f2g_isr_tile_15_intr;
  input    h2l_strm_g2f_isr_tile_0_intr;
  input    h2l_strm_g2f_isr_tile_1_intr;
  input    h2l_strm_g2f_isr_tile_2_intr;
  input    h2l_strm_g2f_isr_tile_3_intr;
  input    h2l_strm_g2f_isr_tile_4_intr;
  input    h2l_strm_g2f_isr_tile_5_intr;
  input    h2l_strm_g2f_isr_tile_6_intr;
  input    h2l_strm_g2f_isr_tile_7_intr;
  input    h2l_strm_g2f_isr_tile_8_intr;
  input    h2l_strm_g2f_isr_tile_9_intr;
  input    h2l_strm_g2f_isr_tile_10_intr;
  input    h2l_strm_g2f_isr_tile_11_intr;
  input    h2l_strm_g2f_isr_tile_12_intr;
  input    h2l_strm_g2f_isr_tile_13_intr;
  input    h2l_strm_g2f_isr_tile_14_intr;
  input    h2l_strm_g2f_isr_tile_15_intr;
  input    h2l_par_cfg_g2f_isr_tile_0_intr;
  input    h2l_par_cfg_g2f_isr_tile_1_intr;
  input    h2l_par_cfg_g2f_isr_tile_2_intr;
  input    h2l_par_cfg_g2f_isr_tile_3_intr;
  input    h2l_par_cfg_g2f_isr_tile_4_intr;
  input    h2l_par_cfg_g2f_isr_tile_5_intr;
  input    h2l_par_cfg_g2f_isr_tile_6_intr;
  input    h2l_par_cfg_g2f_isr_tile_7_intr;
  input    h2l_par_cfg_g2f_isr_tile_8_intr;
  input    h2l_par_cfg_g2f_isr_tile_9_intr;
  input    h2l_par_cfg_g2f_isr_tile_10_intr;
  input    h2l_par_cfg_g2f_isr_tile_11_intr;
  input    h2l_par_cfg_g2f_isr_tile_12_intr;
  input    h2l_par_cfg_g2f_isr_tile_13_intr;
  input    h2l_par_cfg_g2f_isr_tile_14_intr;
  input    h2l_par_cfg_g2f_isr_tile_15_intr;
  input    h2l_global_isr_strm_f2g_w;
  input    h2l_global_isr_strm_g2f_w;
  input    h2l_global_isr_par_cfg_g2f_w;
  input     [31:0] h2l_cgra_config_write_cnt_w;
  input    h2l_cgra_config_write_cnt_we;
  input     [31:0] h2l_cgra_config_read_cnt_w;
  input    h2l_cgra_config_read_cnt_we;
  input     [31:0] h2l_cgra_config_rd_data_data_w;
  input    h2l_cgra_config_rd_data_data_we;
  input     [6:2] h2d_pio_dec_address;
  input     [31:0] h2d_pio_dec_write_data;
  input    h2d_pio_dec_write;
  input    h2d_pio_dec_read;

  //------- outputs
  output     [31:0] l2h_global_reset_cnt_r;
  output     [31:0] l2h_cgra_stall_stall_r;
  output     [15:0] l2h_glb_clk_en_master_clk_en_r;
  output     [15:0] l2h_glb_clk_en_bank_master_clk_en_r;
  output     [15:0] l2h_glb_pcfg_broadcast_stall_stall_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_0_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_1_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_2_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_3_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_4_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_5_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_6_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_7_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_8_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_9_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_10_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_11_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_12_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_13_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_14_r;
  output    l2h_stream_start_pulse_g2f_glb_tile_15_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_0_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_1_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_2_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_3_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_4_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_5_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_6_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_7_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_8_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_9_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_10_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_11_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_12_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_13_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_14_r;
  output    l2h_stream_start_pulse_f2g_glb_tile_15_r;
  output    l2h_pc_start_pulse_glb_tile_0_r;
  output    l2h_pc_start_pulse_glb_tile_1_r;
  output    l2h_pc_start_pulse_glb_tile_2_r;
  output    l2h_pc_start_pulse_glb_tile_3_r;
  output    l2h_pc_start_pulse_glb_tile_4_r;
  output    l2h_pc_start_pulse_glb_tile_5_r;
  output    l2h_pc_start_pulse_glb_tile_6_r;
  output    l2h_pc_start_pulse_glb_tile_7_r;
  output    l2h_pc_start_pulse_glb_tile_8_r;
  output    l2h_pc_start_pulse_glb_tile_9_r;
  output    l2h_pc_start_pulse_glb_tile_10_r;
  output    l2h_pc_start_pulse_glb_tile_11_r;
  output    l2h_pc_start_pulse_glb_tile_12_r;
  output    l2h_pc_start_pulse_glb_tile_13_r;
  output    l2h_pc_start_pulse_glb_tile_14_r;
  output    l2h_pc_start_pulse_glb_tile_15_r;
  output    l2h_strm_f2g_isr_intr_o;
  output    l2h_strm_g2f_isr_intr_o;
  output    l2h_par_cfg_g2f_isr_intr_o;
  output    l2h_global_isr_intr_o;
  output     [31:0] l2h_cgra_config_addr_addr_r;
  output     [31:0] l2h_cgra_config_wr_data_data_r;
  output     [31:0] l2h_cgra_config_write_cnt_r;
  output    l2h_cgra_config_write_cnt_ored_o;
  output     [31:0] l2h_cgra_config_read_cnt_r;
  output    l2h_cgra_config_read_cnt_ored_o;
  output     [31:0] l2h_cgra_config_rd_data_data_r;
  output     [31:0] l2h_glb_flush_crossbar_sel_r;
  output     [31:0] d2h_dec_pio_read_data;
  output    d2h_dec_pio_ack;
  output    d2h_dec_pio_nack;


  //------- wire defines
  logic   [31:0] d2l_test_w;
  logic  d2l_test_we;
  logic  d2l_test_re;
  logic   [31:0] d2l_global_reset_w;
  logic  d2l_global_reset_we;
  logic  d2l_global_reset_re;
  logic   [31:0] d2l_cgra_stall_w;
  logic  d2l_cgra_stall_we;
  logic  d2l_cgra_stall_re;
  logic   [31:0] d2l_glb_clk_en_master_w;
  logic  d2l_glb_clk_en_master_we;
  logic  d2l_glb_clk_en_master_re;
  logic   [31:0] d2l_glb_clk_en_bank_master_w;
  logic  d2l_glb_clk_en_bank_master_we;
  logic  d2l_glb_clk_en_bank_master_re;
  logic   [31:0] d2l_glb_pcfg_broadcast_stall_w;
  logic  d2l_glb_pcfg_broadcast_stall_we;
  logic  d2l_glb_pcfg_broadcast_stall_re;
  logic   [31:0] d2l_stream_start_pulse_w;
  logic  d2l_stream_start_pulse_we;
  logic  d2l_stream_start_pulse_re;
  logic   [31:0] d2l_pc_start_pulse_w;
  logic  d2l_pc_start_pulse_we;
  logic  d2l_pc_start_pulse_re;
  logic   [31:0] d2l_strm_f2g_ier_w;
  logic  d2l_strm_f2g_ier_we;
  logic  d2l_strm_f2g_ier_re;
  logic   [31:0] d2l_strm_g2f_ier_w;
  logic  d2l_strm_g2f_ier_we;
  logic  d2l_strm_g2f_ier_re;
  logic   [31:0] d2l_par_cfg_g2f_ier_w;
  logic  d2l_par_cfg_g2f_ier_we;
  logic  d2l_par_cfg_g2f_ier_re;
  logic   [31:0] d2l_global_ier_w;
  logic  d2l_global_ier_we;
  logic  d2l_global_ier_re;
  logic   [31:0] d2l_strm_f2g_isr_w;
  logic  d2l_strm_f2g_isr_we;
  logic  d2l_strm_f2g_isr_re;
  logic   [31:0] d2l_strm_g2f_isr_w;
  logic  d2l_strm_g2f_isr_we;
  logic  d2l_strm_g2f_isr_re;
  logic   [31:0] d2l_par_cfg_g2f_isr_w;
  logic  d2l_par_cfg_g2f_isr_we;
  logic  d2l_par_cfg_g2f_isr_re;
  logic   [31:0] d2l_global_isr_w;
  logic  d2l_global_isr_we;
  logic  d2l_global_isr_re;
  logic   [31:0] d2l_cgra_config_addr_w;
  logic  d2l_cgra_config_addr_we;
  logic  d2l_cgra_config_addr_re;
  logic   [31:0] d2l_cgra_config_wr_data_w;
  logic  d2l_cgra_config_wr_data_we;
  logic  d2l_cgra_config_wr_data_re;
  logic   [31:0] d2l_cgra_config_write_w;
  logic  d2l_cgra_config_write_we;
  logic  d2l_cgra_config_write_re;
  logic   [31:0] d2l_cgra_config_read_w;
  logic  d2l_cgra_config_read_we;
  logic  d2l_cgra_config_read_re;
  logic   [31:0] d2l_cgra_config_rd_data_w;
  logic  d2l_cgra_config_rd_data_we;
  logic  d2l_cgra_config_rd_data_re;
  logic   [31:0] d2l_glb_flush_crossbar_w;
  logic  d2l_glb_flush_crossbar_we;
  logic  d2l_glb_flush_crossbar_re;
  logic   [31:0] l2d_test_r;
  logic   [31:0] l2d_global_reset_r;
  logic   [31:0] l2d_cgra_stall_r;
  logic   [31:0] l2d_glb_clk_en_master_r;
  logic   [31:0] l2d_glb_clk_en_bank_master_r;
  logic   [31:0] l2d_glb_pcfg_broadcast_stall_r;
  logic   [31:0] l2d_stream_start_pulse_r;
  logic   [31:0] l2d_pc_start_pulse_r;
  logic   [31:0] l2d_strm_f2g_ier_r;
  logic   [31:0] l2d_strm_g2f_ier_r;
  logic   [31:0] l2d_par_cfg_g2f_ier_r;
  logic   [31:0] l2d_global_ier_r;
  logic   [31:0] l2d_strm_f2g_isr_r;
  logic   [31:0] l2d_strm_g2f_isr_r;
  logic   [31:0] l2d_par_cfg_g2f_isr_r;
  logic   [31:0] l2d_global_isr_r;
  logic   [31:0] l2d_cgra_config_addr_r;
  logic   [31:0] l2d_cgra_config_wr_data_r;
  logic   [31:0] l2d_cgra_config_write_r;
  logic   [31:0] l2d_cgra_config_read_r;
  logic   [31:0] l2d_cgra_config_rd_data_r;
  logic   [31:0] l2d_glb_flush_crossbar_r;
  
  
  glc_jrdl_decode pio_decode ( .* );
    
  glc_jrdl_logic pio_logic ( .* );
    
endmodule

