#=========================================================================
# Custom Scripts -- short-fix
#=========================================================================

name: custom-short-fix

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - fix-shorts.tcl
