#=========================================================================
# Custom Genus Scripts
#=========================================================================

name: custom-genus-scripts

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - copy_sdc.tcl
  - generate-results.tcl
