name: garnet-requirements

commands:
  - $GARNET_HOME/bin/requirements_check.sh | tee requirements_check.log
  - egrep '^\*\*\*ERROR' requirements_check.log && exit 13 || echo requirements check GOOD

