name: synopsys-dc-lib2db

commands:
  - make

inputs:
  - adk
  - design.lib

outputs:
  - design.db

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'dc_shell' )                # tool check
  - assert File( 'inputs/adk' )              # must exist
  - assert File( 'inputs/design.lib' )       # must exist

postconditions:
  - assert File( 'outputs/design.db' )       # must exist

