#=========================================================================
# Custom Scripts -- Custom setup-ccopt.tcl for fullchip
#=========================================================================

name: custom-cts

#-------------------------------------------------------------------------
# inputs and outputs
#-------------------------------------------------------------------------

outputs:
  - setup-ccopt.tcl

#-------------------------------------------------------------------------
# Steps
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - cat setup-ccopt.tcl skew-groups.tcl > outputs/setup-ccopt.tcl

