#=========================================================================
# Synopsys IC Validator Calibre DRC
#=========================================================================

name: intel16-synopsys-icv-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
# layout   : design-merged.gds
# schematic: design.lvs.v
inputs:
  - adk
  - design-merged.gds
  - design.lvs.v

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - source v2sp.sh
  - source inputs/adk/run-lvs.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:
  - assert Tool( 'icv' )
  - assert Tool( 'calibre' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design-merged.gds' )
  - assert File( 'inputs/design.lvs.v' )
