#==============================================================
# Custom Flowgen Setup
#==============================================================

name: custom-flowgen-setup

#--------------------------------------------------------------
# Inputs and Outputs
#--------------------------------------------------------------

outputs:
  - setup.tcl

