#=========================================================================
# Custom Scripts -- Tile_PE ccopt property settings
#=========================================================================

name: custom-cts

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - setup-ccopt.tcl
