#=========================================================================
# put-kor
#=========================================================================
# Author : Po-Han Chen
# Date   : Oct 30, 2023
#

name: put-kor

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.oas

outputs:
  - design.oas

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo | calibredrv ./scripts/put-kor.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: design

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'calibredrv' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design.oas' )

postconditions:
  - assert File( 'outputs/design.oas' )
