name: testbench

inputs:
  - run.vcd
  - tiles_Tile_MemCore.list
  - tiles_Tile_PE.list

outputs:
  - cmd.tcl
  - testbench.sv
  - tile_tbs

commands:
  - ./run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  clock_period: 1.0
  PWR_AWARE: True
