# =============================================================================
# Final check for tests run
# =============================================================================
# Author  : Gedeon Nyengele
# Date    : April 5, 2020
# =============================================================================

name: verdict
