# Run full_chip setup stage only

env:
  # BDIR: .

  # Can optionally save results in /build ...
  BDIR: /build/mem${BUILDKITE_BUILD_NUMBER}

  # OVERRIDE_MFLOWGEN_BRANCH: silent_fail

steps:

##############################################################################
# INDIVIDUAL TILE RUNS - Mem tile only

steps:
- label: 'fc setup'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$BDIR;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip'
- wait: ~

- label: 'fc rtl'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$BDIR --need_space 100G;
     echo "--- MAKE RTL"; set -o pipefail;
     make rtl |& tee make-rtl.log'
- wait: ~

