# Use full-chip agents so as not to hamper per-check-in jobs
agents: { queue: "papers" }

env:
  GOLD: /build/glb${BUILDKITE_BUILD_NUMBER}/full_chip

steps:

# Build mflowgen framework for full-chip
- label: 'setup'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip'
- wait: ~

# Build RTL from scratch
- label: 'rtl'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
     echo "--- MAKE RTL"; set -o pipefail;
     make rtl |& tee make-rtl.log'
- wait: ~

# make glb_top
- label: 'glb_top'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
     echo "--- MAKE GLB_TOP"; set -o pipefail;
     make glb_top |& tee make-glb_top.log'
- wait: ~

