##############################################################################
# TO TEST A SPECIFIC BRANCH/COMMIT
# -------------------------------------------------
# Add to env:
#   NOV11: ee214ef77b827f969e4b5f056f5d866cf391be7a
# Add to commands:
#   - pwd; git branch; git checkout $$NOV11
# -------------------------------------------------

env:
  SETUP: source mflowgen/bin/setup-buildkite.sh

  # Env var used by test_module.sh :(
  TEST_MODULE_SBFLAGS: '--skip_mflowgen'

  # For debugging, use build_dir flag to save build in indicated local dir
  # TEST: echo exit 13 | mflowgen/test/test_module.sh
  TEST: echo exit 13 | mflowgen/test/test_module.sh --build_dir /build/glb${BUILDKITE_BUILD_NUMBER}

steps:

##############################################################################
# COMMON SETUP to initialize mflowgen

- label: 'setup 2m'
  commands:
  - '
     echo "--- SETUP";
     set -o pipefail;
     $$SETUP --dir .;
    '
- wait

- label: 'gtile init 20m'
  commands:
  - $TEST --need_space 30G full_chip glb_top glb_tile --steps lvs --debug
  - mflowgen/bin/buildcheck.sh full_chip/*glb_top/*glb_tile --show-all-errors

