# Agents are specified in "pipeline settings" now
# agents: { queue: "papers" }

env:
  GOLD: /build/glb${BUILDKITE_BUILD_NUMBER}/full_chip
  # OVERRIDE_MFLOWGEN_BRANCH: placementCheck

steps:

# Build mflowgen framework for full-chip
- label: 'setup'
  commands:
  - '
     : "Set up env and cd to GOLD (full_chip) dir";
     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
     set -x;
     grep mem_size  $$GARNET_HOME/mflowgen/glb_top/construct.py;
     grep mem_size .mflowgen/*glb_top/configure.yml;
     grep mem_size -r .mflowgen;
     '
- wait: ~

- label: 'full_chip rtl'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
     echo "--- MAKE RTL"; set -o pipefail;
     make rtl |& tee make-rtl.log'
- wait: ~

- label: 'glb_top rtl'
  commands:
  - '
     : "Set up env and cd to GOLD (full_chip) dir";
     echo "--- GLB_TOP setup"; set -o pipefail;
     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;

     echo "--- Build glb_top subdir using appropriate numbering scheme";
     stepname=$(cd .mflowgen; /bin/ls -d *glb_top | head -1);
     mkdir -p $$stepname; cd $$stepname;     
     mflowgen run --design $$GARNET_HOME/mflowgen/glb_top;

     echo "--- Early out if e.g. missing sram.spi input edge";
     $$GARNET_HOME/mflowgen/bin/find-unmatched-inputs.sh .mflowgen/graph.dot || exit 13;

     echo "--- Use full_chip rtl"; mkdir -p inputs;
     (cd inputs; ln -sf ../../*-rtl/outputs/design.v design.v && touch .stamp.design.v);
     (cd inputs; ln -sf ../../*-rtl/outputs/header   header   && touch .stamp.header);

     echo "--- MAKE RTL";
     make rtl |& tee make-rtl.log;
    '
- wait: ~

- label: 'glb_tile'
  commands:
  - '
     : "Set up env and cd to GOLD/glb_top dir";
     echo "--- MAKE GLB_TILE"; set -o pipefail;
     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;
     cd *-glb_top;

     : "Build the tile";
     echo exit 13 | make glb_tile |& tee make-glb_tile.log;
    '
- wait: ~

- label: 'glb_top'
  commands:
  - '
     : "Set up env and cd to GOLD/glb_top dir";
     echo "--- MAKE GLB_TOP"; set -o pipefail;
     source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 1G;

     : "Build everything up through LVS";
     cd *-glb_top;
     echo exit 13 | make mentor-calibre-lvs |& tee make-lvs.log;

     : "Double check to make sure nothing failed!";
     echo "egrep ^FAILED make-*.log && exit 13";
     egrep ^FAILED make-*.log && exit 13 || echo PASSED;
    '
- wait: ~

