# Use full-chip agents so as not to hamper per-check-in jobs
agents: { tech : "gf" }

env:
  GOLD: /build/glb${BUILDKITE_BUILD_NUMBER}/full_chip
  # OVERRIDE_MFLOWGEN_BRANCH: placementCheck

steps:

# Build mflowgen framework for full-chip
- label: 'setup'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
     set -x;
     grep mem_size  $$GARNET_HOME/mflowgen/glb_top/construct.py;
     grep mem_size .mflowgen/*glb_top/configure.yml;
     grep mem_size -r .mflowgen;
     '

- wait: ~

# Build RTL from scratch
- label: 'rtl'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
     echo "--- MAKE RTL"; set -o pipefail;
     make rtl |& tee make-rtl.log'
- wait: ~

# make glb_top
# Note: "echo exit 13" prevents hang at genus/innovus prompt, allows clean fail
- label: 'glb_top'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 10G;
     echo "--- MAKE GLB_TOP"; set -o pipefail;
     echo exit 13 | make glb_top |& tee make-glb_top.log;
     egrep ^FAILED make-glb_top.log && exit 13'
- wait: ~

