# Huh this worked
env:
  AFAR: boo

# agents: { queue: "papers" }
agents: { queue: "hours" }

steps:

- label: label1
#   agents: { queue: "papers" }
  commands:
  - set -x
  - echo hye
  - export AFOO=bar
  - ABOO=har
  - echo AFOO=$$AFOO ABOO=$$ABOO AFAR=$$AFAR
  - printenv | sort | head
- wait: { continue_on_failure: true } # One step at a time + continue on failure

- label: label2
  commands:
  - echo AFOO=$$AFOO ABOO=$$ABOO AFAR=$$AFAR
  - printenv | sort | head
