agents: { jobsize: "hours" }

env:
  GOLD: /build/bdgtc-memtile.${BUILDKITE_BUILD_NUMBER}

steps:

##############################################################################
# INDIVIDUAL TILE RUNS - PE tile only

- label: 'setup'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD;
     mflowgen run --design $$GARNET_HOME/mflowgen/tile_array'
- wait: ~

- label: 'MemTile'
  commands:
  - 'source mflowgen/bin/setup-buildkite.sh --dir $$GOLD --need_space 30G;
     set -o pipefail;
     make Tile_MemCore |& tee make-mem.log'


