# Run PE SYNTH ONLY in context of full_chip

agents: { jobsize: "hours" }

env:
  TEST: 'echo "+++ BEGIN"; echo exit 13 | mflowgen/test/test_module.sh'

steps:

##############################################################################
# INDIVIDUAL TILE RUNS
# 
- label: 'PE synth 45m'
  commands:
  - $TEST --need_space 30G full_chip tile_array Tile_PE --steps synthesis --debug
  - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 110

- wait: { continue_on_failure: true } # One step at a time + continue on failure
