agents: { jobsize: "hours" }

env:
  TEST: 'echo exit 13 | echo mflowgen/test/test_module.sh'

steps:

##############################################################################
# INDIVIDUAL TILE RUNS
# 
- label: 'PE synth 45m'
  commands:
  - echo "" x


- wait: { continue_on_failure: true } # One step at a time + continue on failure

########################################################################
# FULL CHIP RUNS - see pipeline_fullchip.yml

# For more see pipeline_notes.yml

# /sim/buildkite-agent/builds/bigjobs-1/tapeout-aha/mflowgen/

