agents: { jobsize: "hours" }

env:
  GOLD: /build/pm${BUILDKITE_BUILD_NUMBER}
  # OVERRIDE_MFLOWGEN_BRANCH: silent_fail
  TEST: 'echo exit 13 | mflowgen/test/test_module.sh'

steps:

- label: 'fc rtl'
  commands:
  - $TEST --need_space 30G --build_dir $GOLD full_chip tile_array         --steps rtl

- label: 'pe rtl'
  commands:
  - $TEST --need_space 30G --build_dir $GOLD full_chip tile_array Tile_PE --steps rtl

- label: 'pe syn'
  commands:
  - $TEST --need_space 30G --build_dir $GOLD full_chip tile_array Tile_PE --steps synthesis
