# Agents are specified in "pipeline settings", see e.g. buildkite.com/tapeout-aha/steps

##############################################################################
# TO TEST A SPECIFIC BRANCH/COMMIT
# -------------------------------------------------
# Add to env:
#   NOV11: ee214ef77b827f969e4b5f056f5d866cf391be7a
# Add to commands:
#   - pwd; git branch; git checkout $$NOV11
# -------------------------------------------------

env:
  WHICH_SOC: amber
  SETUP: source mflowgen/bin/setup-buildkite.sh

  # Env var used by test_module.sh :(
  TEST_MODULE_SBFLAGS: '--skip_mflowgen'

# For normal operation leave off build_dir flag to save disk space
  TEST: echo exit 13 | mflowgen/test/test_module.sh
  BDIR: .

# For debugging, use build_dir flag to save build in indicated local dir
#   TEST: echo exit 13 | mflowgen/test/test_module.sh --build_dir /build/pmg${BUILDKITE_BUILD_NUMBER}
#   BDIR: /build/pmg${BUILDKITE_BUILD_NUMBER}


  # Newer dockers use lake "sparse_strawman" branch offshoots :(
  # Note as of 10/10/2022 this is the default (see common/rtl/gen_rtl.sh)
  RTL_DOCKER_IMAGE: 'stanfordaha/garnet@sha256:dd688c7b98b034dadea9f7177781c97a7a030d737ae4751a78dbb97ae8b72af4'

  # TODO/FIXME Figure out how to use a top-level parm file :(

steps:

##############################################################################
# COMMON SETUP to initialize mflowgen

- label: 'setup 2m'
  commands:
  - '
     echo "--- SETUP";
     set -o pipefail;
     $$SETUP --dir .;
    '
- wait

##############################################################################
# INDIVIDUAL TILE RUNS
# Builds in dir e.g. mflowgen/full_chip/19-tile_array/16-Tile_MemCore

# For non-GF (TSMC) branches, run the usual three tile tests.
# But GF branches cannot run synthesis on my machine, so
# add if-condition to do a single RTL-only test for GF branches;


# PTILE through init
# Set pe max width to 112: fp limits to 110 but then lvs says 112 OK
- label: 'ptile init 20m'
  commands:
  - $TEST --need_space 30G full_chip tile_array Tile_PE --steps init --debug
  - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 112 $BDIR
  - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_PE --show-all-errors
  if: build.branch !~ /to-spv/ && build.branch !~ /spV/


# PTILE through LVS
# - label: 'ptile lvs 2h'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_PE --steps mentor-calibre-lvs --debug
#   - .buildkite/pipelines/check_tile_width.sh Tile_PE --max 112 $BDIR
#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_PE --show-all-errors
#   if: build.branch !~ /to-spv/ && build.branch !~ /spV/



# MTILE through init
# - label: 'mtile init 25m'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_MemCore --steps init --debug
#   - .buildkite/pipelines/check_tile_width.sh Tile_MemCore --max 250 $BDIR
#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
#   if: build.branch !~ /to-spv/ &&  build.branch !~ /spV/

# MTILE through LVS
# - label: 'mtile lvs 2h'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_MemCore --steps mentor-calibre-lvs --debug
#   - .buildkite/pipelines/check_tile_width.sh Tile_MemCore --max 250 $BDIR
#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
#   if: build.branch !~ /to-spv/ &&  build.branch !~ /spV/



# GTILE through init
# - label: 'gtile init 20m'
#   commands:
#   - $TEST --need_space 30G full_chip glb_top glb_tile --steps init --debug
#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top/*glb_tile --show-all-errors
#   if: build.branch !~ /to-spv/ &&  build.branch !~ /spV/

# GTILE through LVS
# - label: 'gtile lvs 3h'
#   commands:
#   - $TEST --need_space 30G full_chip glb_top glb_tile --steps mentor-calibre-lvs --debug
#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top/*glb_tile --show-all-errors
#   if: build.branch !~ /to-spv/ &&  build.branch !~ /spV/


# GTOP through LVS
# - label: 'gtop lvs 3h?'
#   commands:
#   - $TEST --need_space 30G full_chip glb_top --steps mentor-calibre-lvs --debug
#   - mflowgen/bin/buildcheck.sh $BDIR/full_chip/*glb_top --show-all-errors
#   if: build.branch !~ /to-spv/ &&  build.branch !~ /spV/



# ONYX BRANCHES ONLY
# GF branches cannot run synthesis on my machine, so do RTL only I guess
- label: 'RTL only 25m'
  commands:
  - 'export WHICH_SOC=onyx; export RTL_DOCKER_IMAGE=stanfordaha/garnet:latest;
    $TEST --need_space 30G full_chip --steps rtl --debug'
  if: build.branch =~ /to-spv/ || build.branch =~ /spV/ || build.branch =~ /sms/
