# Agents are specified in "pipeline settings" now
# agents: { queue: "papers" }

env:
  # OVERRIDE_MFLOWGEN_BRANCH: placementCheck
  # BDIR: '--dir /build/glb${BUILDKITE_BUILD_NUMBER}/full_chip'
  # BDIR: '.'
  FC: /sim/buildkite-agent/deleteme/CI${BUILDKITE_BUILD_NUMBER}/full_chip'

steps:

# 1. Build rtl in common area

- label: 'RTL'
  commands:
  - '
     echo "--- SETUP - full_chip";
     source mflowgen/bin/setup-buildkite.sh --dir $$FC;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;
     '

- wait: ~
