# Agents are specified in "pipeline settings" now
# agents: { queue: "papers" }

env:
  # OVERRIDE_MFLOWGEN_BRANCH: placementCheck
  # BDIR: '--dir /build/glb${BUILDKITE_BUILD_NUMBER}/full_chip'
  # BDIR: '.'
  FC: /sim/buildkite-agent/deleteme/CI${BUILDKITE_BUILD_NUMBER}/full_chip'

steps:

# 1. Build rtl in common area

- label: 'RTL'
  commands:
  - '
     echo "--- SETUP - full_chip";
     source mflowgen/bin/setup-buildkite.sh --dir $$FC;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;

     echo "--- SETUP - full_chip/glb_top";
     set -x;
     dir=$(cd .mflowgen; /bin/ls -1d *-glb_top); mkdir -p $$dir;
     (cd $$dir; mflowgen run --design $$GARNET_HOME/mflowgen/glb_top);
     set +x;

     echo "--- SETUP - full_chip/tile_array";
     set -x;
     dir=$(cd .mflowgen; /bin/ls -1d *-tile_array); mkdir -p $$dir;
     (cd $$dir; mflowgen run --design $$GARNET_HOME/mflowgen/tile_array);
     cd $$dir;
     set +x;

     echo "--- SETUP - full_chip/tile_array/Tile_PE$";
     set -x;
     dir=$(cd .mflowgen; /bin/ls -1d *-Tile_PE); mkdir -p $$dir;
     (cd $$dir; mflowgen run --design $$GARNET_HOME/mflowgen/Tile_PE);
     set +x;

     echo "--- SETUP - full_chip/tile_array/Tile_MemCore";
     set -x;
     dir=$(cd .mflowgen; /bin/ls -1d *-Tile_MemCore); mkdir -p $$dir;
     (cd $$dir; mflowgen run --design $$GARNET_HOME/mflowgen/Tile_MemCore);
     set +x;

     echo "--- MAKE RTL";
     set -o pipefail;
     cd $$FC; make rtl |& tee make-rtl.log;
     '

- wait: ~

