# Agents are specified in "pipeline settings" now
# agents: { queue: "papers" }

env:
  # OVERRIDE_MFLOWGEN_BRANCH: placementCheck
  # BDIR: '--dir /build/glb${BUILDKITE_BUILD_NUMBER}/full_chip'
  BDIR: '.'

steps:

- label: 'PE'
  commands:
  - '
     echo "--- SETUP";
     source mflowgen/bin/setup-buildkite.sh --dir $$BDIR/tile_array;
     mflowgen run --design $$GARNET_HOME/mflowgen/tile_array;

     echo "--- MAKE TILE_PE";
     set -o pipefail;
     make Tile_PE |& tee make-pe.log;
     '

- label: 'MemTile'
  commands:
  - '
     echo "--- SETUP";
     source mflowgen/bin/setup-buildkite.sh --dir $$BDIR/tile_array;
     mflowgen run --design $$GARNET_HOME/mflowgen/tile_array;

     echo "--- MAKE TILE_MEMCORE";
     set -o pipefail;
     make Tile_MemCore |& tee make-mem.log;
     '

- label: 'GLB'
  commands:
  - '
     echo "--- SETUP";
     source mflowgen/bin/setup-buildkite.sh --dir $$BDIR/full_chip;
     mflowgen run --design $$GARNET_HOME/mflowgen/full_chip;

     echo "--- MAKE RTL";
     set -o pipefail; make rtl |& tee make-rtl.log;

     echo "--- MAKE GLB_TOP";
     set -o pipefail;  make glb_top |& tee make-glb.log;

     '

# Wait for all three tests to finish
- wait: { continue_on_failure: true }


# Final check for errors and such
- label: 'CHECK'
  commands:
  - set -x; ls -l $BDIR
  - set -x; find $BDIR -name genus.log -exec -exec grep 'Cannot resolve' {} \;
  - set -x; mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
