# 04/20/2022 added init and power steps (2 min each maybe)
# 04/20/2022 make pe and mem tests run at the same time

# Agents are specified in "pipeline settings" now
# agents: { jobsize: "hours" }

##############################################################################
# Use this to test a specific branch/commit:
# Add to env:
#   NOV11: ee214ef77b827f969e4b5f056f5d866cf391be7a
# Add to commands:
# - pwd; git branch; git checkout $$NOV11

##############################################################################
# Note: "echo exit 13" prevents hang at genus/innovus prompt
# To preserve output, can set BDIR to e.g.
# BDIR: '-- build_dir /build/msyn${BUILDKITE_BUILD_NUMBER}'
env:
  TEST: 'echo exit 13 | mflowgen/test/test_module.sh'
  STEPS: '--steps synthesis,init,power'
  BDIR: ''

steps:

##############################################################################
# INDIVIDUAL TILE RUNS
# Builds in dir e.g. mflowgen/full_chip/19-tile_array/16-Tile_MemCore

- label: 'common rtl'
  commands:
  - $TEST --need_space 30G full_chip --steps rtl $BDIR --debug

- wait: { continue_on_failure: true } # One step at a time + continue on failure

- label: '250MHz PE synth 12m'
  commands:
  - $TEST --need_space 30G full_chip tile_array Tile_PE $STEPS $BDIR --debug
  - .buildkite/pipelines/check_pe_area.sh
  - mflowgen/bin/buildcheck.sh full_chip/*tile_array/*Tile_PE --show-all-errors

- label: 'MemCore synth 17m'
  commands:
  - $TEST --need_space 30G full_chip tile_array Tile_MemCore $STEPS $BDIR --debug

# What if we do glb_top?
- label: 'GLB'
  commands:
  - $TEST --need_space 30G full_chip glb_top $STEPS $BDIR --debug




# - label: '250MHz PE synth 12m'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_PE $STEPS $BDIR --debug
#   - .buildkite/pipelines/check_pe_area.sh
#   - mflowgen/bin/buildcheck.sh full_chip/*tile_array/*Tile_PE --show-all-errors
# 
# # NO WAIT let's run them in parallel, why not
# # - wait: { continue_on_failure: true } # One step at a time + continue on failure
# 
# - label: 'MemCore synth 17m'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_MemCore $STEPS $BDIR --debug
# 
# # What if we do glb_top?
# - label: 'GLB'
#   commands:
#   - $TEST --need_space 30G full_chip glb_top $STEPS $BDIR --debug
# 
# - wait: { continue_on_failure: true } # One step at a time + continue on failure





# Final check for errors and such
- label: 'CHECK'
  commands:
  - set -x; ls -l $BDIR
  - set -x; find $BDIR -name genus.log -exec -exec grep 'Cannot resolve' {} \;
  - set -x; mflowgen/bin/buildcheck.sh $BDIR/full_chip/*tile_array/*Tile_MemCore --show-all-errors
