agents: { jobsize: "hours" }

##############################################################################
# Use this to test a specific branch/commit:
# Add to env:
#   NOV11: ee214ef77b827f969e4b5f056f5d866cf391be7a
# Add to commands:
# - pwd; git branch; git checkout $$NOV11

##############################################################################
# Note: "echo exit 13" prevents hang at genus/innovus prompt
env:
  TEST: 'echo exit 13 | mflowgen/test/test_module.sh'

steps:

##############################################################################
# INDIVIDUAL TILE RUNS

# TEMPORARY GLB-TILE TEST. RESTORE ORIG TESTS BELOW before merging with master
- label: 'glb tile 2h'
  commands:
  - set -x; mkdir -p full_chip; cp -rp /build/gold.225/full_chip/9-rtl full_chip/
  - set -x; pwd
  - set -x; ls full_chip/9-rtl
  - set -x; mkdir -p full_chip/14-glb_top/inputs
  - set -x; pushd full_chip/14-glb_top/inputs; ln -s ../../9-rtl/outputs/design.v; popd
  - set -x; pwd
  - $TEST --need_space 3G full_chip glb_top --steps rtl --debug
  - $TEST --need_space 3G full_chip glb_top --steps glb_tile --debug

- wait: { continue_on_failure: true } # One step at a time + continue on failure

# 
# - label: '250MHz PE synth 12m'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_PE --steps synthesis --debug
#   - .buildkite/pipelines/check_pe_area.sh
# - wait: { continue_on_failure: true } # One step at a time + continue on failure
# 
# - label: 'MemCore synth 17m'
#   commands:
#   - $TEST --need_space 30G full_chip tile_array Tile_MemCore --steps synthesis --debug
# - wait: { continue_on_failure: true } # One step at a time + continue on failure
