# Run postroute_hold standalone, with two retry attempts in case of failure.

agents: { queue: "papers" }

env:
  GOLD:      foo
  SETUP_BK:  echo 1. $$GOLD
  PHREF:     echo 2. $GOLD
  SETUP_PRH: /bin/bash -c "echo 3. $$GOLD"
  RUN_PRH:   echo 

steps:

  # postroute_hold, retry if fail.
  - label: "hold"
    commands:
    - 'echo "--- POSTROUTE_HOLD - FIRST ATTEMPT"; set -o pipefail;
       $$SETUP_BK 1G; $$SETUP_PRH; $$RUN_PRH make-prh1.log'
