# Run postroute_hold standalone, with two retry attempts in case of failure.

agents: { queue: "papers" }

env:
  GOLD:  foo
  CMD1:  echo 1. $$GOLD
  CMD2: 'echo 2. $$GOLD'

steps:

  # postroute_hold, retry if fail.
  - label: "hold"
    commands:
    - set -x; echo $GOLD; $CMD1; $CMD2
