# To test QRC robustness, uses helper script qrc.sh to do ten
# consecutive postroute_hold runs, two at a time; this test
# takes about five hours for each run pair, so about 25 hours
# for the entire test.
#
# Each test can retry up to two times incase of failure.

agents: { queue: "papers" }

env:
  # Builds in e.g. "/build/prh-3574/{run0,run1,run2...}", output to "make-prh.log"
  BUILDPIPE : ".buildkite/bin/prh.sh /build/prh${BUILDKITE_BUILD_NUMBER}"

# BIG TEST - run two at a time
steps:
  - label:   "tst0"
    # command: '$$BUILDPIPE/tst0'
    command: 'sleep 10; exit 13'
    key: "0a"

  - label:   "tst0"
    command: 'sleep 4; exit 13'
    key: "0b"
    depends_on: [ { step: 0a , allow_failure: true } ]

  - label:   "tst0"
    command: 'sleep 4; exit 13'
    key: "0c"
    depends_on: [ { step: 0b , allow_failure: true } ]


  - label:   "tst1"
    # command: '$$BUILDPIPE/tst1'
    command: 'sleep 4; exit 13'
    key: "1a"

  - label:   "tst1"
    command: 'sleep 4; exit 13'
    key: "1b"
    depends_on: [ { step: 1a , allow_failure: true } ]

  - label:   "tst1"
    command: 'sleep 4; exit 0'
    key: "1c"
    depends_on: [ { step: 1b , allow_failure: true } ]


  - label:   "tst2"
    # command: '$$BUILDPIPE/tst1'
    command: 'sleep 4; exit 13'
    key: "2a"

  - label:   "tst2"
    command: 'sleep 4; exit 13'
    key: "2b"
    depends_on: [ { step: 2a , allow_failure: true } ]

  - label:   "tst2"
    command: 'sleep 4; exit 0'
    key: "2c"
    depends_on: [ { step: 2b , allow_failure: true } ]

  - wait: { continue_on_failure: true }

  - label:   "END"
    command: 'echo END ; exit 13'




#   - label:   "tst1"
#     command: '$$BUILDPIPE/tst1 || $$BUILDPIPE/tst1 || $$BUILDPIPE/tst1'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst2"
#     command: '$$BUILDPIPE/tst2 || $$BUILDPIPE/tst2 || $$BUILDPIPE/tst2'
#   - label:   "tst3"
#     command: '$$BUILDPIPE/tst3 || $$BUILDPIPE/tst3 || $$BUILDPIPE/tst3'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst4"
#     command: '$$BUILDPIPE/tst4 || $$BUILDPIPE/tst4 || $$BUILDPIPE/tst4'
#   - label:   "tst5"
#     command: '$$BUILDPIPE/tst5 || $$BUILDPIPE/tst5 || $$BUILDPIPE/tst5'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst6"
#     command: '$$BUILDPIPE/tst6 || $$BUILDPIPE/tst6 || $$BUILDPIPE/tst6'
#   - label:   "tst7"
#     command: '$$BUILDPIPE/tst7 || $$BUILDPIPE/tst7 || $$BUILDPIPE/tst7'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst8"
#     command: '$$BUILDPIPE/tst8 || $$BUILDPIPE/tst8 || $$BUILDPIPE/tst8'
#   - label:   "tst9"
#     command: '$$BUILDPIPE/tst9 || $$BUILDPIPE/tst9 || $$BUILDPIPE/tst9'
#   - wait: { continue_on_failure: true }
# 
# 
# # SMALL TEST - One test only, plus two retries
# # steps:
# # 
# #   - label:   "tst0"
# #     command: '$$BUILDPIPE/tst0'
# #   - wait: { continue_on_failure: true }
# # 
# #   - label:   "tst0"
# #     command: '$$BUILDPIPE/tst0'
# #   - wait: { continue_on_failure: true }
# # 
# #   - label:   "tst0"
# #     command: '$$BUILDPIPE/tst0'
# #   - wait: { continue_on_failure: true }
