# To test QRC robustness, uses helper script qrc.sh to do ten
# consecutive postroute_hold runs, two at a time; this test
# takes about five hours for each run pair, so about 25 hours
# for the entire test.
#
# Each test can retry up to two times incase of failure.

agents: { queue: "papers" }

env:
  # Builds in e.g. "/build/qtry-3574*"
  QRC     : ".buildkite/bin/qrc.sh /build/qtry${BUILDKITE_BUILD_NUMBER}"

steps:

- label:    'qrc0'
  commands: 'set -x; $${QRC}-0a || $${QRC}-0b || $${QRC}-0c'
- label:    'qrc1'
  commands: 'set -x; $${QRC}-1a || $${QRC}-1b || $${QRC}-1c'
- wait:     { continue_on_failure: true }


- label:    'qrc2'
  commands: 'set -x; $${QRC}-2a || $${QRC}-2b || $${QRC}-2c'
- label:    'qrc3'
  commands: 'set -x; $${QRC}-3a || $${QRC}-3b || $${QRC}-3c'
- wait:     { continue_on_failure: true }

- label:    'qrc4'
  commands: 'set -x; $${QRC}-4a || $${QRC}-4b || $${QRC}-4c'
- label:    'qrc5'
  commands: 'set -x; $${QRC}-5a || $${QRC}-5b || $${QRC}-5c'
- wait:     { continue_on_failure: true }

- label:    'qrc6'
  commands: 'set -x; $${QRC}-6a || $${QRC}-6b || $${QRC}-6c'
- label:    'qrc7'
  commands: 'set -x; $${QRC}-7a || $${QRC}-7b || $${QRC}-7c'
- wait:     { continue_on_failure: true }

- label:    'qrc8'
  commands: 'set -x; $${QRC}-8a || $${QRC}-8b || $${QRC}-8c'
- label:    'qrc9'
  commands: 'set -x; $${QRC}-9a || $${QRC}-9b || $${QRC}-9c'


# for i in 1 2 3 4 5 6 7 8 9; do cat << eof
# - label:    'qrc$i'
#   commands: 'set -x; \$\${QRC}-${i}a || \$\${QRC}-${i}b || \$\${QRC}-${i}c'
# eof
# echo ""
# done
# 
# # steps:
# # - label:    'qrc0'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-0'
# # - label:    'qrc1'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-1'
# # - wait:     { continue_on_failure: true }
# # 
# # 
# # - label:    'qrc2'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-2'
# # - label:    'qrc3'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-3'
# # - wait:     { continue_on_failure: true }
# # 
# # 
# # - label:    'qrc4'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-4'
# # - label:    'qrc5'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-5'
# # - wait:     { continue_on_failure: true }
# # 
# # 
# # - label:    'qrc6'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-6'
# # - label:    'qrc7'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-7'
# # - wait:     { continue_on_failure: true }
# # 
# # 
# # - label:    'qrc8'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-8'
# # - label:    'qrc9'
# #   commands: '.buildkite/bin/qrc.sh $${DESTDIR}-9'
# # - wait:     { continue_on_failure: true }
# # 
# # 
# # ########################################################################
# # # Builds this data structure...?
# # # {
# # #  'agents' : { 'queue' : 'papers' },
# # #  'env'    : { 'DESTDIR' : '/build/qtry3456' },
# # #  'steps'  : [ 
# # #               { 'label' : 'qrc0' , 'commands' : 'qrc.sh' },
# # #               { 'label' : 'qrc1' , 'commands' : 'qrc.sh' },
# # #               { 'wait'  : { 'cf' : 'true' } }
# # #             ]
# # # }
# 
# 
# 
# # GOOD
# # steps:
# # - label:    'qrc0'
# #   commands:
# #   - set -x; ${QRC}-0a || ${QRC}-0b || ${QRC}-0c
