agents: { jobsize: "hours" }

steps:
- label:    'qrc test 5h'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }




# Builds...?
# {
#  'agents' : { 'jobsize' : 'hours' },
#  'steps'  : [ 
#               { 'label' : 'qrc' , 'commands' : 'qrc.sh' },
#               { 'wait' : { 'cf' : 'true' } }
#             ]
# }
