# To test QRC robustness, uses helper script qrc.sh to do ten
# consecutive postroute_hold runs, two at a time; this test
# takes about five hours for each run pair, so about 25 hours
# for the entire test.
#
# Each test can retry up to two times incase of failure.

agents: { queue: "papers" }

env:
  # Builds in e.g. "/build/prh-3574/{run0,run1,run2...}"
  BUILDPIPE : ".buildkite/bin/prh-onestep.sh /build/prh${BUILDKITE_BUILD_NUMBER}"

# BIG TEST - run two at a time
steps:
  - label:   "tst0"
    command: '$$BUILDPIPE/tst0 || $$BUILDPIPE/tst0 || $$BUILDPIPE/tst0'
  - label:   "tst1"
    command: '$$BUILDPIPE/tst1 || $$BUILDPIPE/tst1 || $$BUILDPIPE/tst1'
  - wait: { continue_on_failure: true }

  - label:   "tst2"
    command: '$$BUILDPIPE/tst2 || $$BUILDPIPE/tst2 || $$BUILDPIPE/tst2'
  - label:   "tst3"
    command: '$$BUILDPIPE/tst3 || $$BUILDPIPE/tst3 || $$BUILDPIPE/tst3'
  - wait: { continue_on_failure: true }

  - label:   "tst4"
    command: '$$BUILDPIPE/tst4 || $$BUILDPIPE/tst4 || $$BUILDPIPE/tst4'
  - label:   "tst5"
    command: '$$BUILDPIPE/tst5 || $$BUILDPIPE/tst5 || $$BUILDPIPE/tst5'
  - wait: { continue_on_failure: true }

  - label:   "tst6"
    command: '$$BUILDPIPE/tst6 || $$BUILDPIPE/tst6 || $$BUILDPIPE/tst6'
  - label:   "tst7"
    command: '$$BUILDPIPE/tst7 || $$BUILDPIPE/tst7 || $$BUILDPIPE/tst7'
  - wait: { continue_on_failure: true }

  - label:   "tst8"
    command: '$$BUILDPIPE/tst8 || $$BUILDPIPE/tst8 || $$BUILDPIPE/tst8'
  - label:   "tst9"
    command: '$$BUILDPIPE/tst9 || $$BUILDPIPE/tst9 || $$BUILDPIPE/tst9'
  - wait: { continue_on_failure: true }


# SMALL TEST - two tests only, two potential retries each,  run one thing at a time
# steps:
# 
#   - label:   "tst0"
#     command: '$$BUILDPIPE/tst0'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst0"
#     command: '$$BUILDPIPE/tst0'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst0"
#     command: '$$BUILDPIPE/tst0'
#   - wait: { continue_on_failure: true }
# 
# 
# 
#   - label:   "tst1"
#     command: '$$BUILDPIPE/tst1'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst1"
#     command: '$$BUILDPIPE/tst1'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst1"
#     command: '$$BUILDPIPE/tst1'
#   - wait: { continue_on_failure: true }
