# To test QRC robustness, uses helper script qrc.sh to do ten
# consecutive postroute_hold runs, two at a time; this test
# takes about five hours for each run pair, so about 25 hours
# for the entire test.
#
# Each test can retry up to two times incase of failure.

agents: { queue: "papers" }

env:
  # Builds in e.g. "/build/prh-3574/{run0,run1,run2...}", output to "make-prh.log"
  QRC : ".buildkite/bin/qrc.sh /build/prh${BUILDKITE_BUILD_NUMBER}"

# BIG TEST - run two at a time
steps:
  - label:   "tst0"
    command: '$$QRC/tst0 || $$QRC/tst0 || $$QRC/tst0'
  - label:   "tst1"
    command: '$$QRC/tst1 || $$QRC/tst1 || $$QRC/tst1'
  - wait: { continue_on_failure: true }

  - label:   "FAIL SUCCESFULLY AND END HERE"
    command: 'exit 13'
  - wait: ~

  - label:   "tst2"
    command: '$$QRC/tst2 || $$QRC/tst2 || $$QRC/tst2'
  - label:   "tst3"
    command: '$$QRC/tst3 || $$QRC/tst3 || $$QRC/tst3'
  - wait: { continue_on_failure: true }

  - label:   "tst4"
    command: '$$QRC/tst4 || $$QRC/tst4 || $$QRC/tst4'
  - label:   "tst5"
    command: '$$QRC/tst5 || $$QRC/tst5 || $$QRC/tst5'
  - wait: { continue_on_failure: true }

  - label:   "tst6"
    command: '$$QRC/tst6 || $$QRC/tst6 || $$QRC/tst6'
  - label:   "tst7"
    command: '$$QRC/tst7 || $$QRC/tst7 || $$QRC/tst7'
  - wait: { continue_on_failure: true }

  - label:   "tst8"
    command: '$$QRC/tst8 || $$QRC/tst8 || $$QRC/tst8'
  - label:   "tst9"
    command: '$$QRC/tst9 || $$QRC/tst9 || $$QRC/tst9'
  - wait: { continue_on_failure: true }


# SMALL TEST - One test only, plus two retries
# steps:
# 
#   - label:   "tst0"
#     command: '$$QRC/tst0'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst0"
#     command: '$$QRC/tst0'
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst0"
#     command: '$$QRC/tst0'
#   - wait: { continue_on_failure: true }



# Alternative approach using "depends_on".
# # THIS WORKS but I don't like it.
# # BIG TEST - run two at a time
# steps:
# 
#   - label:   "tst0"
#     # command: '$$QRC/tst0'
#     command: 'sleep 10; exit 13'
#     key: "0a"
# 
#   - label:   "tst0"
#     command: 'sleep 4; exit 13'
#     key: "0b"
#     depends_on: [ { step: 0a , allow_failure: true } ]
# 
#   - label:   "tst0"
#     command: 'sleep 4; exit 13'
#     key: "0c"
#     depends_on: [ { step: 0b , allow_failure: true } ]
# 
# 
#   - label:   "tst1"
#     # command: '$$QRC/tst1'
#     command: 'sleep 4; exit 13'
#     key: "1a"
# 
#   - label:   "tst1"
#     command: 'sleep 4; exit 13'
#     key: "1b"
#     depends_on: [ { step: 1a , allow_failure: true } ]
# 
#   - label:   "tst1"
#     command: 'sleep 4; exit 0'
#     key: "1c"
#     depends_on: [ { step: 1b , allow_failure: true } ]
# 
#   - wait: { continue_on_failure: true }
# 
#   - label:   "tst2"
#     # command: '$$QRC/tst1'
#     command: 'sleep 4; exit 13'
#     key: "2a"
# 
#   - label:   "tst2"
#     command: 'sleep 4; exit 13'
#     key: "2b"
#     depends_on: [ { step: 2a , allow_failure: true } ]
# 
#   - label:   "tst2"
#     command: 'sleep 4; exit 0'
#     key: "2c"
#     depends_on: [ { step: 2b , allow_failure: true } ]
# 
#   - wait: { continue_on_failure: true }
# 
#   - label:   "END"
#     command: 'echo END ; exit 13'
