agents: { queue: "papers" }

steps:

- label:    'qrc0'
  commands: '.buildkite/bin/qrc.sh'
- label:    'qrc1'
  commands: 'sleep 300; .buildkite/bin/qrc.sh'
  wait:     { continue_on_failure: true }


- label:    'qrc2'
  commands: '.buildkite/bin/qrc.sh'
- label:    'qrc3'
  commands: 'sleep 300; .buildkite/bin/qrc.sh'
- wait:     { continue_on_failure: true }


- label:    'qrc4'
  commands: '.buildkite/bin/qrc.sh'
- label:    'qrc5'
  commands: 'sleep 300; .buildkite/bin/qrc.sh'
- wait:     { continue_on_failure: true }


- label:    'qrc6'
  commands: '.buildkite/bin/qrc.sh'
- label:    'qrc7'
  commands: 'sleep 300; .buildkite/bin/qrc.sh'
- wait:     { continue_on_failure: true }


- label:    'qrc8'
  commands: '.buildkite/bin/qrc.sh'
- label:    'qrc9'
  commands: 'sleep 300; .buildkite/bin/qrc.sh'
- wait:     { continue_on_failure: true }


# Builds this data structure...?
# {
#  'agents' : { 'jobsize' : 'hours' },
#  'steps'  : [ 
#               { 'label' : 'qrc' , 'commands' : 'qrc.sh' },
#               { 'wait' : { 'cf' : 'true' } }
#             ]
# }
