agents: { queue: "papers" }

steps:

- label:    'qrc0 5h'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc1'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc2'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc3'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc4'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc5'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc6'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc7'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc8'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }

- label:    'qrc9'
  commands: ${GARNET_HOME}/.buildkite/bin/qrc.sh
- wait:     { continue_on_failure: true }






# Builds...?
# {
#  'agents' : { 'jobsize' : 'hours' },
#  'steps'  : [ 
#               { 'label' : 'qrc' , 'commands' : 'qrc.sh' },
#               { 'wait' : { 'cf' : 'true' } }
#             ]
# }
