# ##############################################################################
# # Use this to test a specific branch/commit:
# # Add to env:
# #   NOV11: ee214ef77b827f969e4b5f056f5d866cf391be7a
# # Add to commands:
# # - pwd; git branch; git checkout $$NOV11
# 
# ##############################################################################
# # Note: "echo exit 13" prevents hang at genus/innovus prompt
# env:
#   TEST: 'echo exit 13 | mflowgen/test/test_module.sh'
# 
# steps:
# 
# ##############################################################################
# # INDIVIDUAL TILE RUNS
# # Builds in dir e.g. mflowgen/full_chip/19-tile_array/16-Tile_MemCore
# 
# - label: 'FULL_CHIP RTL'
#   commands:
#   - $TEST --need_space 30G full_chip --steps rtl --debug
#   - 'rtl_dir=full_chip/*-rtl;
#      if grep Traceback $$rtl_dir/mflowgen-run.log;
#      then echo oh no failed silently oh no;
#      else exit 0;
#      fi'

env:
  # BUILD: /build/fcrtl-${BUILDKITE_BUILD_NUMBER}
  BUILD: .

  # Compare result to reference build, yes?
  REF_RTL: /build/gold.offload/deleteme.bka/gold.474/full_chip/10-rtl/outputs/design.v

  TEST: 'echo exit 13 | mflowgen/test/test_module.sh'
  SETUP: 'source mflowgen/bin/setup-buildkite.sh'
  TEST_MODULE_SBFLAGS: '--skip_mflowgen'
  WHICH_SOC: amber

steps:

##############################################################################
# COMMON SETUP to initialize mflowgen

- label: 'setup 2m'
  commands:
  - '
     test -f $$REF_RTL || echo "--- ERROR cannot find RTL ref $$REF_RTL";
     test -f $$REF_RTL || echo exit;

     echo "--- SETUP";
     set -o pipefail;
     $$SETUP --dir .;
    '
- wait

- label: 'RTL only'
  commands:
  - $TEST --build_dir $BUILD full_chip --steps rtl --debug
  - 'RTL=$BUILD/full_chip/*-rtl/outputs/design.v;

     echo "--- PRECODER CHECK";
     grep "module precoder_32_1"  $$RTL | sort;
     grep "module precoder_32_19" $$RTL && echo FAIL || echo PASS;
     grep "module precoder_32_19" $$RTL && exit 13   || echo PASS;

     echo "--- RTL COMPARE";
     set -x;
     test -f $$REF_RTL || echo "--- ERROR cannot find RTL ref $$REF_RTL";
     test -f $$REF_RTL || exit 0;
     echo diff $$RTL $$REF_RTL;
     diff $$RTL $$REF_RTL || echo "+++ RTL COMPARE FOUND DIFFS";
     echo "unsorted diff $$RTL $$REF_RTL";
     diff $$RTL $$REF_RTL | wc -l;
     echo "sorted diff $$RTL $$REF_RTL";
     diff <(sort $$RTL | sed "s/,//g") <(sort $$REF_RTL | sed "s/,//g") | wc -l;
     '
