# pre-flowsetup
# To get e.g. icovl-cells into iflow, must do the following:
# - create new step 'pre-flowsetup' whose outputs are icovl cells
# -- link via "command" in pre-iflow/configure.yml
# - connect pre-flowsetup step to flowsetup (iflow) step
# - extend iflow inputs to include icovl cells
# - iflow "setup.tcl" automatically includes "inputs/*.lef"

name: pre-flowsetup

inputs:
  - adk

outputs:
  - icovl-cells.lef
  - dtcd-cells.lef
  - bumpcells.lef

commands:
  - cd outputs
  - cp -p ../inputs/adk/icovl-cells.lef .
  - cp -p ../inputs/adk/dtcd-cells.lef .
  - cp -p ../inputs/adk/bumpcells.lef .
