name: lint

on:
  # Every push
  push:

  # When requested manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: lint
      shell: bash
      run: bin/lint.sh
